### ISSUE TITLE
NPE "this.appenderFuture" is null when closing the partition

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#10227]
**Description**

The following message is logged as a failure:

```
java.lang.NullPointerException: 
    Cannot invoke "io.camunda.zeebe.util.sched.future.ActorFuture.complete(Object)" 
    because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$7(LogStreamImpl.java:310)
```

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.util.sched.future.ActorFuture.complete(Object)" because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$7(LogStreamImpl.java:310) ~[zeebe-logstreams-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:82) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.4.jar:8.0.4]
```

</p>
</details>

The message is logged after a partition is transitioned to `LEADER` and back to `INACTIVE` in a short time (< 5s). 

However, the broker was able to transition to `INACTIVE` successfully. We can consider the log statement as noise and should omit it.  

[Log](https://drive.google.com/file/d/1o7-5Y3js1vqSYn2xUimy-q3VNs58lFrf/view?usp=sharing)

Related to #8757

**Environment:**
- Zeebe Version: `8.0.4`
- Camunda SaaS

**Comment by megglos** [comment]
Triage: converted to a bug,
