### ISSUE TITLE
Reported error TimeoutException: Timeout after: 300 SECONDS

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#10311]
**Describe the bug**

This error was reported 4 times, during closing:
- https://console.cloud.google.com/errors/detail/CLy1tYn3t_rpkQE;service=zeebe;filter=%5B%22Timeout%22%5D;time=P7D?project=camunda-cloud-240911
- https://console.cloud.google.com/errors/detail/CPqM-bHmt7eEQw;service=zeebe;filter=%5B%22Timeout%22%5D;time=P7D?project=camunda-cloud-240911
- https://console.cloud.google.com/errors/detail/CKmUnNL9t9GXTw;service=zeebe;filter=%5B%22Timeout%22%5D;time=P7D?project=camunda-cloud-240911
- https://console.cloud.google.com/errors/detail/CKj0mO7x8ZKbgQE;service=zeebe;filter=%5B%22Timeout%22%5D;time=P7D?project=camunda-cloud-240911

**To Reproduce**

🤷 

**Expected behavior**

We should investigate whether this is really an error, and otherwise avoid it being reported as such.

**Log/Stacktrace**

<details><summary>Logs</summary>
 <p>

```
2022-09-05 23:49:42.570 CEST
zeebe
RaftServer{raft-partition-partition-3}{role=FOLLOWER} - Accepted VoteRequest{term=176, candidate=0, lastLogIndex=208, lastLogTerm=175}: candidate's log is up-to-date
2022-09-05 23:49:42.574 CEST
zeebe
RaftServer{raft-partition-partition-3} - Found leader 0
2022-09-05 23:54:25.428 CEST
zeebe
Closing Broker-2 [1/10]: upgrade manager failed to close.
2022-09-05 23:54:25.430 CEST
zeebe
Closing Broker-2 [2/10]: register diskspace usage listeners
2022-09-05 23:54:25.430 CEST
zeebe
Closing Broker-2 [2/10]: register diskspace usage listeners closed in 0 ms
2022-09-05 23:54:25.430 CEST
zeebe
Closing Broker-2 [3/10]: zeebe partitions
2022-09-05 23:59:25.434 CEST
zeebe
java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
2022-09-05 23:59:25.437 CEST
zeebe
RaftServer{raft-partition-partition-3} - Transitioning to INACTIVE
2022-09-05 23:59:25.438 CEST
zeebe
RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
2022-09-05 23:59:25.438 CEST
zeebe
RaftServer{raft-partition-partition-2} - Transitioning to INACTIVE
2022-09-05 23:59:25.442 CEST
zeebe
Closing segment: JournalSegment{id=1, index=1}
2022-09-05 23:59:25.442 CEST
zeebe
Closing segment: JournalSegment{id=1, index=1}
2022-09-05 23:59:25.442 CEST
zeebe
Closing segment: JournalSegment{id=1, index=1}
2022-09-05 23:59:25.446 CEST
zeebe
Stopped
2022-09-05 23:59:25.446 CEST
zeebe
Stopped
2022-09-05 23:59:25.447 CEST
zeebe
java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
2022-09-06 00:04:25.448 CEST
zeebe
Closing Broker-2 [3/10]: zeebe partitions failed to close.
2022-09-06 00:04:25.450 CEST
zeebe
Closing Broker-2 [4/10]: leader management request handler
2022-09-06 00:09:25.451 CEST
zeebe
Closing Broker-2 [4/10]: leader management request handler failed to close.
2022-09-06 00:09:25.453 CEST
zeebe
Closing Broker-2 [5/10]: disk space monitor
2022-09-06 00:14:25.453 CEST
zeebe
Closing Broker-2 [5/10]: disk space monitor failed to close.
2022-09-06 00:14:25.455 CEST
zeebe
Closing Broker-2 [6/10]: embedded gateway
2022-09-06 00:14:25.462 CEST
zeebe
Closing gateway broker client ...
2022-09-06 00:19:25.463 CEST
zeebe
Exception when closing client. Ignoring
2022-09-06 00:19:25.465 CEST
zeebe
topology manager closed
2022-09-06 00:19:25.465 CEST
zeebe
Gateway broker client closed.
2022-09-06 00:19:25.465 CEST
zeebe
Closing Broker-2 [6/10]: embedded gateway closed in 300010 ms
2022-09-06 00:19:25.466 CEST
zeebe
Closing Broker-2 [7/10]: cluster services
2022-09-06 00:19:25.466 CEST
zeebe
Closing Broker-2 [7/10]: cluster services closed in 0 ms
2022-09-06 00:19:25.466 CEST
zeebe
Closing Broker-2 [8/10]: subscription api
2022-09-06 00:24:25.466 CEST
zeebe
Closing Broker-2 [8/10]: subscription api failed to close.
2022-09-06 00:24:25.468 CEST
zeebe
Closing Broker-2 [9/10]: command api transport and handler
2022-09-06 00:29:25.469 CEST
zeebe
Closing Broker-2 [9/10]: command api transport and handler failed to close.
2022-09-06 00:29:25.471 CEST
zeebe
Closing Broker-2 [10/10]: Migrated Startup Steps
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.get(CompletableActorFuture.java:131) ~[zeebe-util-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.util.sched.FutureUtil.join(FutureUtil.java:32) ~[zeebe-util-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.util.sched.future.CompletableActorFuture.join(CompletableActorFuture.java:201) ~[zeebe-util-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.util.sched.Actor.close(Actor.java:96) ~[zeebe-util-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.lambda$closingStepByStep$0(CloseProcess.java:59) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:93) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.closingStepByStep(CloseProcess.java:59) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:93) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.bootstrap.CloseProcess.closeReverse(CloseProcess.java:40) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.Broker.lambda$close$14(Broker.java:397) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.Broker.lambda$close$15(Broker.java:395) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.Broker.close(Broker.java:390) ~[zeebe-broker-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.StandaloneBroker.onApplicationEvent(StandaloneBroker.java:84) ~[camunda-cloud-zeebe-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.StandaloneBroker.onApplicationEvent(StandaloneBroker.java:32) ~[camunda-cloud-zeebe-1.2.12.jar:1.2.12]
	at io.camunda.zeebe.broker.StandaloneBroker$$EnhancerBySpringCGLIB$$e548e3c0.onApplicationEvent(<generated>) ~[camunda-cloud-zeebe-1.2.12.jar:1.2.12]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.6.jar:2.6.6]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145) ~[spring-boot-2.6.6.jar:2.6.6]
	at java.lang.Iterable.forEach(Unknown Source) [?:?]
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114) [spring-boot-2.6.6.jar:2.6.6]
	at java.lang.Thread.run(Unknown Source) [?:?] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by megglos** [comment]
Put into backlog with `later` for now as a release is imminent.

**Comment by npepinpe** [comment]
Closing, please reopen if it occurs again, and save some logs for investigation :)
