### ISSUE TITLE
Create process instance with start instructions exceeding record batch size leads to errors 

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#10336]
**Describe the bug**

Starting a process instance anywhere (#9366) using CreateProcessInstance with start instructions can lead to reported unexpected errors when the resulting records exceed the maximum record batch size. Some examples that can cause this are:
 - when very large variables are passed along to the start instructions;
 - when there are many start instructions; 
 - or when the start instructions need to create many element instances.

It may be unclear to the user what happened, and the exception may be reported as an error while we consider it an expected user error. 

The error is handled as unexpected. This means that no process instance is available after this error occurred, which is the same effect as when it would be rejected, so this issue is not as important as:
- #9728 

**To Reproduce**

- deploy a simple process
- create an instance with start instructions and pass along very large variables
- notice the logged errors

**Expected behavior**

Reject the command on the log and respond the rejection to the client, with a clear rejection message.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
12:12:35.211 [Broker-0-StreamProcessor-1] ERROR io.camunda.zeebe.processor - Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, intentValue=255, intent=CREATE, requestStreamId=-2147483648, requestId=-1, protocolVersion=3, valueType=PROCESS_INSTANCE_CREATION, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.0}, value={"bpmnProcessId":"process-id","processDefinitionKey":-1,"processInstanceKey":-1,"version":-1,"variables":"gaF42wA//AB4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eH...}' without errors, but exception occurred with message 'Can't append entry: '' with size: 259 this would exceed the maximum batch size. [ currentBatchEntryCount: 3, currentBatchSize: 4193975]'.
io.camunda.zeebe.engine.api.records.RecordBatch$ExceededBatchRecordSizeException: Can't append entry: '' with size: 259 this would exceed the maximum batch size. [ currentBatchEntryCount: 3, currentBatchSize: 4193975]
	at io.camunda.zeebe.engine.api.records.RecordBatch.appendRecord(RecordBatch.java:67) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.DirectProcessingResultBuilder.appendRecordReturnEither(DirectProcessingResultBuilder.java:64) ~[classes/:?]
	at io.camunda.zeebe.engine.api.ProcessingResultBuilder.appendRecord(ProcessingResultBuilder.java:37) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedTypedCommandWriter.appendRecord(ResultBuilderBackedTypedCommandWriter.java:37) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedTypedCommandWriter.appendFollowUpCommand(ResultBuilderBackedTypedCommandWriter.java:32) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.ElementActivationBehavior.activateElementByCommand(ElementActivationBehavior.java:230) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.ElementActivationBehavior.activateElement(ElementActivationBehavior.java:96) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.common.ElementActivationBehavior.activateElement(ElementActivationBehavior.java:69) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor.lambda$activateElementsForStartInstructions$19(CreateProcessInstanceProcessor.java:411) ~[classes/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor.activateElementsForStartInstructions(CreateProcessInstanceProcessor.java:408) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor.createProcessInstance(CreateProcessInstanceProcessor.java:162) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor.lambda$onCommand$1(CreateProcessInstanceProcessor.java:116) ~[classes/:?]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.processinstance.CreateProcessInstanceProcessor.onCommand(CreateProcessInstanceProcessor.java:115) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessor.onCommand(CommandProcessor.java:34) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:79) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:125) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:260) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:256) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:205) ~[classes/:?]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:181) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[classes/:?]
```

</p>
</details>

**Comment by korthout** [comment]
Happened in https://console.cloud.google.com/errors/detail/CPWQkMjm56Kz5QE;service=zeebe;time=P7D?project=camunda-cloud-240911 (may have been without start instructions, but result is the same)
