### ISSUE TITLE
TestOAuthIntegration Go test is flaky

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#10370]
**Summary**

- How often does the test fail? More than 5 times this week
- Does it block your work? Not yet but it is failing on `main`
- Do we suspect that it is a real failure? no

**Failures**

<details><summary>Assertion failure 1</summary>
<pre>
[2022-09-15T10:24:06.423Z]     oauth_integration_test.go:138: 

[2022-09-15T10:24:06.423Z]         	Error Trace:	/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:138

[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:66

[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/suite.go:132

[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:47

[2022-09-15T10:24:06.423Z]         	Error:      	Received unexpected error:

[2022-09-15T10:24:06.423Z]         	            	Post "http://localhost:49155/clients": EOF

[2022-09-15T10:24:06.424Z]         	Test:       	TestOAuthIntegration
</pre>
</details>

<details><summary>Assertion failure 2</summary>
<pre>

[2022-09-15T10:06:06.337Z]     oauth_integration_test.go:138: 

[2022-09-15T10:06:06.337Z]         	Error Trace:	/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:138

[2022-09-15T10:06:06.337Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:66

[2022-09-15T10:06:06.337Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/suite.go:132

[2022-09-15T10:06:06.337Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:47

[2022-09-15T10:06:06.337Z]         	Error:      	Received unexpected error:

[2022-09-15T10:06:06.337Z]         	            	Post "http://localhost:49155/clients": read tcp 127.0.0.1:55968->127.0.0.1:49155: read: connection reset by peer

[2022-09-15T10:06:06.337Z]         	Test:       	TestOAuthIntegration
</pre>
</details>

**Hypotheses**

Connection binding issues.

**Logs**

<details><summary>Logs</summary>
<pre>
[2022-09-15T10:22:59.223Z] + .ci/scripts/distribution/test-go.sh
[2022-09-15T10:22:59.223Z] + ORG_DIR=/go/src/github.com/camunda
[2022-09-15T10:22:59.223Z] + cd /go/src/github.com/camunda/zeebe/clients/go
[2022-09-15T10:22:59.223Z] + gotestsum --raw-command --junitfile TEST-go.xml go test -mod=vendor -v -json ./...
[2022-09-15T10:23:12.735Z] [32m✓[0m  pkg/entities (40ms)
[2022-09-15T10:23:12.735Z] [32m✓[0m  internal/utils (51ms)
[2022-09-15T10:23:12.735Z] [32m✓[0m  pkg/commands (60ms)
[2022-09-15T10:23:13.316Z] [32m✓[0m  pkg/worker (272ms)
[2022-09-15T10:23:13.817Z] [32m✓[0m  pkg/zbc (206ms)
[2022-09-15T10:23:47.947Z] [31m✖[0m  test (31.848s)
[2022-09-15T10:24:06.423Z] [32m✓[0m  cmd/zbctl (50.57s)
[2022-09-15T10:24:06.423Z] [33m∅[0m  cmd/zbctl/internal/commands
[2022-09-15T10:24:06.423Z] [33m∅[0m  internal/containersuite
[2022-09-15T10:24:06.423Z] [33m∅[0m  internal/embedded
[2022-09-15T10:24:06.423Z] [33m∅[0m  internal/mock_pb
[2022-09-15T10:24:06.423Z] [33m∅[0m  pkg/pb
[2022-09-15T10:24:06.423Z] 
[2022-09-15T10:24:06.423Z] === [31mFailed[0m
[2022-09-15T10:24:06.423Z] === [31mFAIL[0m: test TestOAuthIntegration (13.60s)
[2022-09-15T10:24:06.423Z] 2022/09/15 10:23:35 Starting container id: 407eb7d81ed5 image: oryd/hydra:v1.11
[2022-09-15T10:24:06.423Z] 2022/09/15 10:23:36 Waiting for container id 407eb7d81ed5 image: oryd/hydra:v1.11
[2022-09-15T10:24:06.423Z] 2022/09/15 10:23:45 Container is ready id: 407eb7d81ed5 image: oryd/hydra:v1.11
[2022-09-15T10:24:06.423Z]     oauth_integration_test.go:138: 
[2022-09-15T10:24:06.423Z]         	Error Trace:	/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:138
[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:66
[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/suite.go:132
[2022-09-15T10:24:06.423Z]         	            				/go/src/github.com/camunda/zeebe/clients/go/test/oauth_integration_test.go:47
[2022-09-15T10:24:06.423Z]         	Error:      	Received unexpected error:
[2022-09-15T10:24:06.423Z]         	            	Post "http://localhost:49155/clients": EOF
[2022-09-15T10:24:06.424Z]         	Test:       	TestOAuthIntegration
[2022-09-15T10:24:06.424Z] 
[2022-09-15T10:24:06.424Z] 
[2022-09-15T10:24:06.424Z] DONE 189 tests, 1 failure in 65.342s
script returned exit code 1[2022-09-15T10:24:08.825Z] Recording test results
[2022-09-15T10:24:13.127Z] [Checks API] No suitable checks publisher found.
[2022-09-15T10:39:35.326Z] Send slack message
[2022-09-15T10:39:35.341Z] Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: camunda, channel: #zeebe-ci, color: <empty>, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
</pre>
</details>

**Comment by remcowesterhoud** [comment]
I haven't been able to see this behavior locally. I tried running it 100s of times. I did just see another build where this failed though: https://ci.zeebe.camunda.cloud/job/camunda/job/zeebe/job/main/873/testReport/junit/github/com_camunda_zeebe_clients_go_v8_test/Verify___Test__Go____TestOAuthIntegration/

**Comment by Zelldon** [comment]
Happen again https://github.com/camunda/zeebe/actions/runs/3384521982/jobs/5621578476

```
=== RUN   TestOAuthIntegration
2022/11/03 09:43:31 Starting container id: f8ee9f6cb4d2 image: oryd/hydra:v1.11
2022/11/03 09:43:32 Waiting for container id f8ee9f6cb4d2 image: oryd/hydra:v1.11
2022/11/03 09:43:40 Container is ready id: f8ee9f6cb4d2 image: oryd/hydra:v1.11
    oauth_integration_test.go:138: 
        	Error Trace:	/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:138
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:66
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/suite.go:132
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:47
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:49155/clients": read tcp [::1]:35584->[::1]:49155: read: connection reset by peer
        	Test:       	TestOAuthIntegration
--- FAIL: TestOAuthIntegration (11.34s)
```

**Comment by npepinpe** [comment]
Happened again: https://github.com/camunda/zeebe/commit/d20d1003b8cd954108d09e60af18dcd427df0ca5

**Comment by npepinpe** [comment]
Another: https://github.com/camunda/zeebe/actions/runs/3445373633/jobs/5749012560

**Comment by menski** [comment]
> Happened again: https://github.com/camunda/zeebe/actions/runs/3426390258/jobs/5708139693

This one failed in a different test

```
=== RUN   TestZbctlWithInsecureGateway/TestCommonCommands/using_insecure_env_var
    main_test.go:290: using insecure env var: diff (-want +got):
          []string{
          	... // 5 identical elements
          	"  Broker 0 - 0.0.0.0:26501",
          	"    Version: 3.41.1-alpha1",
        - 	"    Partition 1 : Leader, Healthy",
        + 	"    Partition 1 : Leader, Unhealthy",
          	"",
          }
=====================================
Test case 'using insecure env var' failed, printing container logs up until now
=====================================
Container logs
NOTE: these logs are for all tests in the same suite!
=====================================
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands
    suite.go:77: test panicked: runtime error: slice bounds out of range [8:6]
        goroutine 70 [running]:
        runtime/debug.Stack()
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/debug/stack.go:24 +0x65
        github.com/stretchr/testify/suite.failOnPanic(0xc000340340, {0xbf88c0, 0xc000041320})
        	/home/runner/work/zeebe/zeebe/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:77 +0x3b
        github.com/stretchr/testify/suite.Run.func1.1()
        	/home/runner/work/zeebe/zeebe/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:161 +0x252
        panic({0xbf88c0, 0xc000041320})
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1038 +0x215
        github.com/camunda/zeebe/clients/go/v8/internal/containersuite.sanitizeDockerLogs({0xc0004fa000, 0xc000680000})
        	/home/runner/work/zeebe/zeebe/clients/go/internal/containersuite/containerSuite.go:115 +0x265
        github.com/camunda/zeebe/clients/go/v8/internal/containersuite.printFailedContainerLogs({0xd5e6c0, 0xc0004d25a0})
        	/home/runner/work/zeebe/zeebe/clients/go/internal/containersuite/containerSuite.go:95 +0x31b
        github.com/camunda/zeebe/clients/go/v8/internal/containersuite.(*ContainerSuite).PrintFailedContainerLogs(0xd45f80)
        	/home/runner/work/zeebe/zeebe/clients/go/internal/containersuite/containerSuite.go:174 +0x30
        github.com/camunda/zeebe/clients/go/v8/cmd/zbctl.(*integrationTestSuite).TestCommonCommands(0xc000010008)
        	/home/runner/work/zeebe/zeebe/clients/go/cmd/zbctl/main_test.go:258 +0x1eb
        reflect.Value.call({0xc0000b7680, 0xc000010d28, 0x13}, {0xc45694, 0x4}, {0xc000575e70, 0x1, 0x1})
        	/opt/hostedtoolcache/go/1.17.13/x64/src/reflect/value.go:556 +0x845
        reflect.Value.Call({0xc0000b7680, 0xc000010d28, 0xc000010008}, {0xc00005de70, 0x1, 0x1})
        	/opt/hostedtoolcache/go/1.17.13/x64/src/reflect/value.go:339 +0xc5
        github.com/stretchr/testify/suite.Run.func1(0xc000340340)
        	/home/runner/work/zeebe/zeebe/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:175 +0x4b6
        testing.tRunner(0xc000340340, 0xc00033d950)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x35a
--- FAIL: TestZbctlWithInsecureGateway (46.90s)
    --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands (0.05s)
        --- PASS: TestZbctlWithInsecureGateway/TestCommonCommands/print_help (0.01s)
        --- PASS: TestZbctlWithInsecureGateway/TestCommonCommands/print_version (0.01s)
        --- PASS: TestZbctlWithInsecureGateway/TestCommonCommands/missing_insecure_flag (0.01s)
        --- FAIL: TestZbctlWithInsecureGateway/TestCommonCommands/using_insecure_env_var (0.02s)
FAIL
FAIL	github.com/camunda/zeebe/clients/go/v8/cmd/zbctl	46.913s
```

**Comment by aleksander-dytko** [comment]
Discus with ZDP if we should remove the Go test.

**Comment by Zelldon** [comment]
Failed again https://github.com/camunda/zeebe/actions/runs/4281446234/jobs/7454482591

**Comment by Zelldon** [comment]
Failed again here https://github.com/camunda/zeebe/pull/13033 -> https://github.com/camunda/zeebe/actions/runs/5219060999/jobs/9420471993

But with different error

```
2023/06/09 06:50:02 ✅ Container created: 8d92885dc107
2023/06/09 06:50:02 🐳 Starting container: 8d92885dc107
2023/06/09 06:50:02 🚧 Waiting for container id 8d92885dc107 image: oryd/hydra:v1.11
2023/06/09 06:50:06 ✅ Container started: 8d92885dc107
    oauth_integration_test.go:139: 
        	Error Trace:	/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:139
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:66
        	            				/home/runner/work/zeebe/zeebe/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:154
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:47
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 201
        	Test:       	TestOAuthIntegration
--- FAIL: TestOAuthIntegration (7.07s)
FAIL
FAIL	github.com/camunda/zeebe/clients/go/v8/test	28.305s
FAIL
Error: Process completed with exit code 1.
```

**Comment by Zelldon** [comment]
Failed again https://github.com/camunda/zeebe/actions/runs/5902564478/job/16010835896

```
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:32770/clients": read tcp [::1]:53152->[::1]:32770: read: connection reset by peer
```

**Comment by koevskinikola** [comment]
And again: https://github.com/camunda/zeebe/actions/runs/6872984283/job/18692316861

```
deadline:<nil> Strategies:[0xc00004d3e0 0xc00004d400]}
    oauth_integration_test.go:139: 
        	Error Trace:	/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:139
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:66
        	            				/home/runner/work/zeebe/zeebe/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:154
        	            				/home/runner/work/zeebe/zeebe/clients/go/test/oauth_integration_test.go:47
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 201
        	Test:       	TestOAuthIntegration
--- FAIL: TestOAuthIntegration (6.29s)
FAIL
FAIL	github.com/camunda/zeebe/clients/go/v8/test	20.434s
```

**Comment by megglos** [comment]
closing as not reported for a couple of months

**Comment by ana-vinogradova-camunda** [comment]
Happened again:

```
    oauth_integration_test.go:139: 
        	Error Trace:	/home/runner/work/camunda/camunda/clients/go/test/oauth_integration_test.go:139
        	            				/home/runner/work/camunda/camunda/clients/go/test/oauth_integration_test.go:66
        	            				/home/runner/work/camunda/camunda/clients/go/vendor/github.com/stretchr/testify/suite/suite.go:157
        	            				/home/runner/work/camunda/camunda/clients/go/test/oauth_integration_test.go:47
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 201
        	Test:       	TestOAuthIntegration
--- FAIL: TestOAuthIntegration (5.28s)
```

Build: https://github.com/camunda/camunda/actions/runs/10268252170/job/28410852394

**Comment by megglos** [comment]
would not spend any more time on the go client considering https://github.com/camunda/product-hub/issues/2438 and rather invest into moving it to a community project going forward.
