### ISSUE TITLE
Cluster out of disk space due to consecutive ES exporter errors

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#12232]
**Describe the bug**

The last release benchmark was out of the disk space when it received multiple consecutive errors while trying to export to Elastic. Over the course of 14 hours, it received variations of the following error:

```
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 345 item(s) of bulk request [type: index_not_found_exception, reason: no such index [zeebe-record_process-instance_8.2.0-snapshot_2023-04-04]]]
	at io.camunda.zeebe.exporter.ElasticsearchClient.throwCollectedBulkError(ElasticsearchClient.java:183) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:166) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:107) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:166) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.flushAndReschedule(ElasticsearchExporter.java:152) ~[zeebe-elasticsearch-exporter-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

This occurred typically when curator was deleting an index while the exporting would occur. There were quite a lot of these errors over 14 hours, which we assume is the reason for us running out of disk space, as the exporter works on a backoff, retrying the whole bulk every time an error occurs.

Once it stabilized, the exporter never managed to catch up to the backlog of unexported records built up, and we stayed at a ~7 million (though fairly stable).

**To Reproduce**

Run a normal benchmark, and delete/curate indexes more aggressively than usual.

**Expected behavior**

The cluster should be able to cope with data being deleted on Elastic, and once exporting starts up again, it should be able to recover. Might be interesting to look into https://github.com/camunda/zeebe/issues/6723

**Environment:**
- Zeebe Version: 8.2.0-rc1

**Comment by korthout** [comment]
ZPA triage:
- workaround when it happens: bump diskspace
- workaround to avoid it: delete data less aggressively
- should be resolved by re-creating the index automatically and then retrying the bulk

**Comment by abbasadel** [comment]
ZPA Planning:
- Since the next iteration is short, we will not consider working on this issue.

**Comment by oleschoenburg** [comment]
This occured again in a medic benchmark.

**Comment by megglos** [comment]
What confuss me is that a missing index should get created on write if missing based on the template. This raises the question whether some other issue (diskspace on elastic?) prevented index creation. I would close this issue until we observe this again to root-cause this, as given the last comment is nearly one year old it didn't seem to surface often.
