### ISSUE TITLE
NPE when receiving a log stream writer while shutting down

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#12254]
**Describe the bug**

There seems to be a slight race condition when partitions are transitioning to leader while shutting down (note: this may also occur while transitioning to follower, but I haven't observed it).

In various places, we try to get a log stream writer. When the future completes, we assume that no error means there is something. Turns out that while shutting down, we seem to have some race conditions, because the writer returned is sometimes null (which is fine during shutdown).

This triggers 3 different but related NPEs (see stack traces below). Note that for other actors, an error is propagated instead, which hints at a race condition:

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createNewLogStreamWriter(LogStreamImpl.java:191) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:175) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.lambda$onBecomingLeader$3(CommandApiServiceImpl.java:112) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p></details>

**To Reproduce**

**Expected behavior**

There is no unnecessary noisy errors. We also don't expect race conditions in our startup/shutdown, so I would have expected the shutdown to wait for the writer to have been initially obtained, then the ongoing transition step to finish, and then shutdown to occur.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:602) ~[agrona-1.18.0.jar:1.18.0]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiRequestHandler.lambda$addPartition$0(CommandApiRequestHandler.java:149) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT] 
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:602) ~[agrona-1.18.0.jar:1.18.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:588) ~[agrona-1.18.0.jar:1.18.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:44) ~[agrona-1.18.0.jar:1.18.0]
	at io.camunda.zeebe.broker.transport.queryapi.QueryApiRequestHandler.lambda$addPartition$0(QueryApiRequestHandler.java:62) ~[zeebe-broker-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.future.ActorFuture.complete(Object)" because "this.appenderFuture" is null
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$openAppender$6(LogStreamImpl.java:282) ~[zeebe-logstreams-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0-SNAPSHOT

**Comment by megglos** [comment]
ZDP Triage:
- there is chance to simplify the related code
- we could make acquiring the writer sync instead of async
- could also be an issue in the shutdown process not being strictly sequential
- @npepinpe actually got an idea what the issue is during triage

**Comment by npepinpe** [comment]
What happens is when we create a writer, we return a future which is the result of opening the appender (itself a future) chained with returning the sequencer.

When we close, we close the appender future _successfully_, returning null. So the previous future we returned is completed successfully, and returns the value of `sequencer`, which at this point is null.

My expectation would be that when I create a writer, and the log stream is closed before I get it, I would get an error, not a null value.

**Comment by koevskinikola** [comment]
This occured again on a production cluster with version `8.2.5` ([internal logs link](https://drive.google.com/file/d/1AAPcQv2_l7z88MP6HASj-j-6GbBZXAeF/view)).
