### ISSUE TITLE
Unhelpful error message when setting configuration for non-existing exporter

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#12678]
**Describe the bug**

When I set configuration for an exporter that does not exist, for example because I make a typo in the exporter name, Zeebe fails to start and logs a very unhelpful error message that gives me no indication on what went wrong or how to fix it.

**To Reproduce**

``` shell
$ docker run --rm -e ZEEBE_BROKER_EXPORTERS_OOPS_ARGS_INDEX_NUMBEROFREPLICAS=1 camunda/zeebe:latest
...
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) [spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) [spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-3.0.5.jar:3.0.5]
        at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.2.4.jar:8.2.4]
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.putIfAbsent(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.getClassLoadingLock(Unknown Source) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source) ~[?:?]
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at io.camunda.zeebe.broker.exporter.repo.ExporterRepository.load(ExporterRepository.java:79) ~[zeebe-broker-8.2.4.jar:8.2.4]
        at io.camunda.zeebe.broker.Broker.buildExporterRepository(Broker.java:147) ~[zeebe-broker-8.2.4.jar:8.2.4]
        at io.camunda.zeebe.broker.Broker.<init>(Broker.java:70) ~[zeebe-broker-8.2.4.jar:8.2.4]
        at io.camunda.zeebe.broker.Broker.<init>(Broker.java:49) ~[zeebe-broker-8.2.4.jar:8.2.4]
        at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:91) ~[camunda-zeebe-8.2.4.jar:8.2.4]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-3.0.5.jar:3.0.5]
        ... 3 more
...
```

**Expected behavior**

This should result in an easy to understand error message or be ignored silently.

**Comment by megglos** [comment]
ZDP-Triage:
- typo in an environment variable name caused this error, as the exporter config wasn't complete
- would be nice to do but not urgent
