### ISSUE TITLE
Failed to activate jobs for type "name" from partition 1

### ISSUE THREAD

**Issue by IceNiro** [camunda/camunda#12755]
hello ,i have been bothering by this problem for a long time.
here is the the situation:
- we always find the error log below:
Failed to activate jobs for type auto-download-complete from partition 1
   java.util.concurrent.TimeoutException: Request ProtocolRequest{id=89973, subject=command-api-1, sender=0.0.0.0:26502, 
   payload=byte[]{length=148, hash=1907244980}} to 0.0.0.0:26501 timed out in PT15S
   at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:230) ~ 
  [zeebe-atomix-cluster-8.0.3.jar:8.0.3]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]

like we always fix this issue before ,we think it`s because the hardware（by this case is the SSD ).
but when we stop our services and test the SSD ,it show great proformance：

![image](https://github.com/camunda/zeebe/assets/16775141/365de715-bf1a-4eba-b727-3a947847bb8d)

as you can see : 
   IOPS : 32K
   BW : 63MB/S

which is great and theoretical is more then enought to our applications.

but when we run a stress testing on our business paltform with zeebe cluster in  'embedded gateway'
we get the error message like the title.
and the same time the IO monitor show like below :
![image](https://github.com/camunda/zeebe/assets/16775141/b51c3600-e53b-4af5-a76f-c77e46b327d3)

it look like the SSD can not afford the requriment of our applications
and i'm pretty sure that the biggest io comsuption is `Zeebe Broker`
<img width="1389" alt="image" src="https://github.com/camunda/zeebe/assets/16775141/69b11512-eb68-4ae3-ac7b-6bbd417791a7">

if I can get any direction where to look at, that would be a great help !!!
or if there is any configuration about io performance ? 
we have take the config of  `ZEEBE_BROKER_THREADS_IOTHREADCOUNT` , doesn's much help

Environment:
- Zeebe Version: 8.0.*
- we build a zeebe cluster by docker on the k8s enviroment
- it only happend while we run stress test
- cluster info :
<img width="864" alt="image" src="https://github.com/camunda/zeebe/assets/16775141/d7dbd06c-8568-4fc7-9740-e4cfe59c8142">

**Comment by korthout** [comment]
ZPA triage:
- this is about the performance of the system based on hardware
- it makes most sense that `@camunda/zeebe-distributed-platform` looks into this

**Comment by megglos** [comment]
Hey @IceNiro ,

thanks for reaching out! Zeebe metrics like processing per partition would be extremely helpful to better understand the load on your broker, I would recommend you to make use of the [Grafana dashboard](https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/metrics/#grafana) we provide to better investigate. It might also just be that you hit the limit of what you can achieve with a single broker, for any reasonable performance testing I would recommend you to go with at least 3 brokers and two partitions.

Is there any particular reason you are running with 8.0? With the latest stable 8.2 we actually have implemented a couple of performance improvements that might help you as well.

**Comment by shahamit** [comment]
@megglos - we are facing this error but with slight variation in the root cause. We have deploying zeebe version 8.2.12 in self-managed mode on aws. We see this error intermittently - on executing 200 workflows around 1-5 fail with this connection closed error.

```
2024-01-17 13:47:18.782 [Gateway-sunrise-workflow-zeebe-gateway-55c94b7459-872l8] [zb-actors-0] [ActivateJobsHandler] WARN
      io.camunda.zeebe.gateway - Failed to activate jobs for type http from partition 1
java.net.ConnectException: Connection RemoteClientConnection{channel=[id: 0x3608f0ad, L:/10.42.8.69:50538 ! R:sunrise-workflow-zeebe-0.sunrise-workflow-zeebe.default.svc/10.42.11.56:26501]} was closed
        at io.atomix.cluster.messaging.impl.AbstractClientConnection.close(AbstractClientConnection.java:76) ~[zeebe-atomix-cluster-8.2.12.jar:8.2.12]
``` 

On enabling TRACE logs on zeebe-gateway we see more details that can help in understanding the issue
```
2024-01-17 13:01:50.750 [Gateway-sunrise-workflow-zeebe-gateway-5564855558-sbnws] [zb-actors-0] [AtomixClientTransportAdapter] TRACE
      io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter - Request 806792795 failed, will not retry!
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=222296, subject=command-api-1, sender=10.42.10.47:26502, payload=byte[]{length=786, hash=-2130652735}} to sunrise-workflow-zeebe-0.sunrise-workflow-zeebe.default.svc:26501 timed out in PT30S
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.12.jar:8.2.12]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.96.Final.jar:4.1.96.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
2024-01-17 13:01:50.750 [Gateway-sunrise-workflow-zeebe-gateway-5564855558-sbnws] [zb-actors-0] [BrokerRequestManager] DEBUG
      io.camunda.zeebe.gateway - Expected to handle gRPC request, but request timed out between gateway and broker
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=222296, subject=command-api-1, sender=10.42.10.47:26502, payload=byte[]{length=786, hash=-2130652735}} to sunrise-workflow-zeebe-0.sunrise-workflow-zeebe.default.svc:26501 timed out in PT30S
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.12.jar:8.2.12]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.96.Final.jar:4.1.96.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Note the issue appears even when we deploy the zeebe gateway (1) and broker (1) on the same ec2 instance. The error is indicating that the gateway pod isn't able to connect with broker pod intermittently.

Kindly guide us on what could be the root cause and possible workarounds 
Thanks.

**Comment by amitonlentra** [comment]
@korthout @megglos - I am reaching out to get inputs on this issue since we are blocked on workflow executions 

One observation meanwhile was that for the bpmn file that resulted in the above error had configured 0 retries for the service tasks. On adding retries to the service task we could see this bpmn file working fine (not resulting the above failed from partition error) but unfortunately the same trick didn't work for another bpmn file. The difference with the second one is that it results in raising an incident while the first one completes successfully.

Could you please share any insights based on the above details?

Thanks.

**Comment by shahamit** [comment]
@korthout @megglos  - I am reaching out to get inputs on this issue since we are blocked on workflow executions

One observation meanwhile was that for the bpmn file that resulted in the above error had configured 0 retries for the service tasks. On adding retries to the service task we could see this bpmn file working fine (not resulting the above failed from partition error) but unfortunately the same trick didn't work for another bpmn file. The difference with the second one is that it results in raising an incident while the first one completes successfully.

Could you please share any insights based on the above details?

Thanks.
