### ISSUE TITLE
When submitting a payload lower than the configured `maxMessageSize`, the request fails with `EXCEEDED_BATCH_RECORD_SIZE`

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda#12873]
**Describe the bug**

When starting a process instance with a ~2MB payload, in the client, it fails with

```
Exception in thread "main" io.camunda.zeebe.client.api.command.ClientStatusException: Command 'CREATE' rejected with code 'EXCEEDED_BATCH_RECORD_SIZE': 
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at io.camunda.getstarted.DeployAndStartInstance.main(DeployAndStartInstance.java:43)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: Command 'CREATE' rejected with code 'EXCEEDED_BATCH_RECORD_SIZE': 
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Command 'CREATE' rejected with code 'EXCEEDED_BATCH_RECORD_SIZE': 
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

And in Zeebe the following exception is logged:

```
2023-05-26 15:03:41.938 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR
      io.camunda.zeebe.broker.process - Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE_CREATION, intent=CREATE}, value={"bpmnProcessId":"foo","processDefinitionKey":2251799813685251,"processInstanceKey":2251799813685253,"version":2,"variables":"ga9tZXNzYWdlX2NvbnRlbnTbACqqrEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU...}' without errors, but exception occurred with message 'Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE_CREATION, intent=CREATED}, key=2251799813685255, sourceIndex=-1, unifiedRecordValue={"bpmnProcessId":"foo","processDefinitionKey":2251799813685251,"processInstanceKey":2251799813685253,"version":2,"variables":"ga9tZXNzYWdlX2NvbnRlbnTbACqqrEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU...' with size: 2796416 this would exceed the maximum batch size. [ currentBatchEntryCount: 2, currentBatchSize: 2796660]'.
io.camunda.zeebe.stream.api.records.ExceededBatchRecordSizeException: Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE_CREATION, intent=CREATED}, key=2251799813685255, sourceIndex=-1, unifiedRecordValue={"bpmnProcessId":"foo","processDefinitionKey":2251799813685251,"processInstanceKey":2251799813685253,"version":2,"variables":"ga9tZXNzYWdlX2NvbnRlbnTbACqqrEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU...' with size: 2796416 this would exceed the maximum batch size. [ currentBatchEntryCount: 2, currentBatchSize: 2796660]
        at io.camunda.zeebe.stream.impl.records.RecordBatch.appendRecord(RecordBatch.java:67) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.BufferedProcessingResultBuilder.appendRecordReturnEither(BufferedProcessingResultBuilder.java:62) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.api.ProcessingResultBuilder.appendRecord(ProcessingResultBuilder.java:38) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:40) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:75) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:346) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.5.jar:8.2.5]
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.5.jar:8.2.5]
```

When processing the command to create a process instance, it creates following follow-up events (and command):
1. An event that the variable with the respective value has been created, i.e., it contains the variable value (2MB)
2. A command to activate the respective element instance
3. And it tries to add a follow-up event to mark the command as processed (in that case the process instance creation command). At this point, it fails with the shown exception above.

Basically, when trying to add the follow-up event to mark the command as processed, the event contains again the variable value, i.e., the 2MB. That way it will exceed the default 4MB `maxMessageSize`, resulting in the exception above.

**To Reproduce**
1. Start Zeebe
2. Execute the following client
```java
public class DeployAndStartInstance {

  private static final Logger LOG = LogManager.getLogger(DeployAndStartInstance.class);

  public static void main(String[] args) {
    try (ZeebeClient client = ZeebeClientFactory.getZeebeClient()) {
      final var modelInstance = Bpmn.createExecutableProcess("foo")
          .startEvent()
          .serviceTask()
            .zeebeJobType("foo")
          .endEvent()
          .done();

      client.newDeployResourceCommand()
          .addProcessModel(modelInstance, "foo.bpmn")
          .send()
          .join();

      final var byteArray = new byte[(int) 1024*1024*2];

      for (int i = 0; i < 1; i++) {
        final ProcessInstanceEvent event = client.newCreateInstanceCommand()
            .bpmnProcessId("foo")
            .latestVersion()
            .variables(Map.of("message_content", byteArray))
            .send()
            .join();
        
        LOG.info(
            "Started instance for processDefinitionKey='{}', bpmnProcessId='{}', version='{}' with processInstanceKey='{}'",
            event.getProcessDefinitionKey(), event.getBpmnProcessId(), event.getVersion(),
            event.getProcessInstanceKey());
      }

      client.newWorker().jobType("foo").handler((jobClient, job) -> {
        jobClient.newCompleteCommand(job.getKey()).send()
          .whenComplete((result, exception) -> {
            if (exception == null) {
              LOG.info("Completed job successful with result:" + result);
            } else {
              LOG.error("Failed to complete job", exception);
            }
          });
      }).open();

      waitUntilSystemInput("exit");
    }
  }

  private static void waitUntilSystemInput(final String exitCode) {
    try (final Scanner scanner = new Scanner(System.in)) {
      while (scanner.hasNextLine()) {
        final String nextLine = scanner.nextLine();
        if (nextLine.contains(exitCode)) {
          return;
        }
      }
    }
  }
}
```

**Expected behavior**
* It succeeds in processing the command.
* The variables are not dragged along with the follow-up events (when not necessary). For example, when marking the command as processed, then the variable is not required, therefore.
* The same may apply to other types of commands as well (like publishing a message or completing a job with variables, etc.).

**Please Note**
* This issue is not to prevent the `EXCEEDED_BATCH_RECORD_SIZE` in all cases.
* This issue is more about preventing dragging the variables along the follow-up event when it is actually not necessary. That way, the likelihood of the `EXCEEDED_BATCH_RECORD_SIZE` will be reduced.

---

related to [SUPPORT-16962](https://jira.camunda.com/browse/SUPPORT-16962)

**Comment by romansmirnov** [comment]
For awareness, the documentation tells the following

>Generally, there is a limit of 4 MB for the payload of a process instance. This 4 MB includes the variables and the workflow engine internal data, which means there is slightly less memory available for variables. The exact limitation depends on a few factors, but you can consider 3 MB as being safe. If in doubt, run a quick test case.

(https://docs.camunda.io/docs/components/concepts/variables/#variable-size-limitation)

In my interpretation, it suggests that I can "safely" submit a variable with a size of up to 3MB, and the engine can handle that. But this is not true, because every variable bigger than 1MB already fails with `EXCEEDED_BATCH_RECORD_SIZE`.

Based on the documentation, I consider this as a bug and not as a feature.

**Comment by korthout** [comment]
That's a good point @romansmirnov 

Marking it as a bug again, ready for next triage (in time for next planning).

**Comment by korthout** [comment]
ZPA triage:
- seems low effort, let's do it soon (`upcoming`)
- seems reasonable (although it may be breaking user space for exporter consumers that specifically depend on the variables in the ProcessInstanceCreation:CREATED event)
- we discussed additionally documenting the workaround somewhere for users and support, but the effort seems so low that this is not worth the effort
- workaround is anyways documented in the issue here

**Comment by Zelldon** [comment]
Was part of a game day https://confluence.camunda.com/display/ZEEBE/2023-06-06+Game+Day

**Comment by korthout** [comment]
I just want to highlight that this will be resolved for single partition cluster by the solution to:
- https://github.com/camunda/zeebe/issues/13233

For multi-partition clusters, the limit stays at about half the `maxMessageSize` because the process/drg resource is written in two events: `Process/DecisionRequirements:CREATED` and `CommandDistribution:STARTED`

**Comment by korthout** [comment]
@berkaycanbc Can you have a look whether this is resolved by your recent bug fix?

**Comment by berkaycanbc** [comment]
@korthout I just had a look to the issue. The `maxMessageSize` bug fix applied only to job activation. But this issue occurs on process instance creation and with its follow-up . Meaning that it will not resolve the exceeding batch record size for process instance creation. We need to handle this one separately.

**Comment by lev-safro** [comment]
@berkaycanbc @korthout 

This bug was created around three years ago, and the last activity on it was about two years ago.
I have a couple of questions:
- Is this still an issue?
- Is the urgency set correctly? One could argue that if the issue hasn’t been addressed for three years, it might not actually be that urgent.

Thank you in advance.

**Comment by korthout** [comment]
>Is this still an issue?

I believe so, but I'd have to test it again - let's first see if we want to prioritize it now

>Is the urgency set correctly? 

- severity seems fitting
- likelihood as well

>One could argue that if the issue hasn’t been addressed for three years, it might not actually be that urgent.

I think this just means that other things were given higher priority, so far.

**Comment by berkaycanbc** [comment]
Verified that the issue still exists with the following test:

```java
  @Test
  public void shouldCreateProcessInstanceWithLargeVariablesBelowMaxMessageSize() {
    // given - deploy a simple process
    engine
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(PROCESS_ID)
                .startEvent()
                .serviceTask("task", t -> t.zeebeJobType("test"))
                .endEvent()
                .done())
        .deploy();

    // A ~2MB variable value. This is well below the 4MB maxMessageSize, so the user
    // would reasonably expect this to work. The issue is that internally the engine
    // produces follow-up records that duplicate the variable, causing the batch to exceed
    // the limit.
    final int variableSize = (int) ByteValue.ofMegabytes(2);
    final String largeValue = "x".repeat(variableSize);

    // when - create a process instance with the large variable
    final long processInstanceKey =
        engine
            .processInstance()
            .ofBpmnProcessId(PROCESS_ID)
            .withVariable("large_variable", largeValue)
            .create();

    // then - the process instance should be created successfully
    // If issue #12873 is still present, this will fail because the command gets rejected
    // with EXCEEDED_BATCH_RECORD_SIZE instead of being processed.
    assertThat(processInstanceKey).isGreaterThan(0);

    // Verify the CREATED event was produced for the process instance creation
    assertThat(
            RecordingExporter.processInstanceCreationRecords()
                .withIntent(ProcessInstanceCreationIntent.CREATED)
                .withBpmnProcessId(PROCESS_ID)
                .findFirst())
        .isPresent();

    // Verify the variable was actually created
    assertThat(
            RecordingExporter.variableRecords(VariableIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .withName("large_variable")
                .findFirst())
        .isPresent();

    // Verify the process instance was activated (i.e., not stuck)
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
                .withProcessInstanceKey(processInstanceKey)
                .withElementType(BpmnElementType.PROCESS)
                .findFirst())
        .isPresent();
  }
```

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by marcosgvieira** [comment]
🔄 **Iteration updated automatically (Core Features)**

**From:** None  
**To:** Iteration 8  

**Reason:** The issue is In Progress, so it should be part of the current iteration.
