### ISSUE TITLE
NullPointerException in ActivateProcessInstanceBatchProcessor.createChildInstanceRecord

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#12918]
**Describe the bug**

NPE is thrown when creating instance of process with multiinstance and a large input collection. 

Instance is created:

```
2023-05-31 14:41:06.222  INFO 36794 --- [pool-6-thread-1] i.c.cloud.gameday.ProcessApplication     : Created process instances with large collection. [order-id: '7c7014f4-16fe-4609-9ef2-d017546416af']
```

But can't be executed. 
[It looks like the instance get banned.](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%2229c46b01-ab7a-4b96-9262-10a28257dfe5-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0A-resource.labels.container_name%3D%22zeebe-analytics%22%0A-resource.labels.container_name%3D%22zeebe-gateway%22;timeRange=2023-05-31T11:29:31.241992Z%2F2023-05-31T13:36:09.546Z;pinnedLogId=2023-05-31T12:36:40.822878656Z%2F8qiahd3sixyvvbf4;cursorTimestamp=2023-05-31T12:36:40.822878656Z?project=camunda-saas-int-chaos)

**To Reproduce**

Follow https://github.com/camunda-cloud/game-day-cookbook/tree/main/mains/large-multi-instance and change 

```diff
--- a/mains/large-multi-instance/src/main/java/io/camunda/cloud/gameday/ProcessApplication.java
+++ b/mains/large-multi-instance/src/main/java/io/camunda/cloud/gameday/ProcessApplication.java
@@ -49,15 +49,15 @@ public class ProcessApplication implements CommandLineRunner {
   public void run(final String... args) {
     final var executor = Executors.newSingleThreadScheduledExecutor();
     executor.scheduleAtFixedRate(
            () -> createInstanceOfProcess(10), 1, 30, TimeUnit.SECONDS);

     executor.scheduleAtFixedRate(
         () -> {
-          final var orderId = createInstanceOfProcess(20_000);
+          final var orderId = createInstanceOfProcess(2_000_000);
           LOG.info("Created process instances with large collection. [order-id: '{}']", orderId);
 
-        }, 5, 15, TimeUnit.MINUTES);
+        }, 0, 15, TimeUnit.MINUTES);
   }

          final var orderId = createInstanceOfProcess(2_000_000);
```

**Expected behavior**

Correct batching and not failing of creating such instance, or if possible rejection.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getValue()" because "parentElementInstance" is null
	at io.camunda.zeebe.engine.processing.processinstance.ActivateProcessInstanceBatchProcessor.createChildInstanceRecord(ActivateProcessInstanceBatchProcessor.java:66) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.processing.processinstance.ActivateProcessInstanceBatchProcessor.processRecord(ActivateProcessInstanceBatchProcessor.java:45) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:346) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.5.jar:8.2.5]

```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.x
- Configuration: G3-S

**Comment by korthout** [comment]
ZPA triage:
- this ceiling seems rather high and not a common case
- therefore we're not considering this as urgent
- however since the process instance is blacklisted we can tackle it along with our efforts to remove blacklisting 
- the root cause is unclear, there's a likelihood that this happens when the parent element instance is completed/terminated before the child batch activation, we should analyze it beforehand because that would be a bigger impact
- therefore let's prioritize the analysis of this issue `upcoming` and depend on the outcome we can provide a better priority.

**Comment by remcowesterhoud** [comment]
I've verified my hypothesis about what's happening here.

The multi-instance activates the children in batches. This all works fine. However it can occur that the multi-instance is completed **before** all batches have been processed. This will result in the NPE as the parent element instance no longer exists when processing a batch.

Imagine the batch size is 100. What happens is the following:
1. We have a process with an input collection of 200 elements
2. These will be split in 3 batches. At first only the first batch is written to the log
3. The first batch writes 100 Activate commands to the log and follow up with the second batch command
4. These 100 Activate commands are processed, and the elements are completed **before** the processing of the next batch command. As a result the multi-instance is **completed**.
5. We process the next batch command. The multi-instance is completed and no longer available in the state. This results in this NPE. 

The instance will be blacklisted as mentioned in the description.

I think this could have a bigger impact as this is a risk for any size of multi-instance.

**Comment by remcowesterhoud** [comment]
@Zelldon Did you remove the job workers from this process when you were testing this by any chance?

**Comment by Zelldon** [comment]
Not sure, but could be that there were some restarts in between of the application.

**Comment by korthout** [comment]
ZPA triage:
- impact would be high if this also affects processes without straight-through processing
- `upcoming` because we want to resolve this sooner rather than later
- fixing it would likely be done by keeping track of how many children still need to be activated and using this to decide whether the flowscope may complete or not
- size `medium`

**Comment by berkaycanbc** [comment]
Happened in:

Environment: `SaaS Prod Trial Cluster`
Zeebe version: `8.5.1`
GC logs (internal) : [link](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CKyq6I-X2d-f6QE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22ed7863d6-2fa9-45cf-8e4d-1b7d15c3b2aa-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22;cursorTimestamp=2024-05-28T19:08:39.101329813Z;startTime=2024-05-28T18:39:09.101Z;endTime=2024-05-28T19:39:09.101Z?project=camunda-cloud-240911)
GC logs downloaded (internal): [link](https://drive.google.com/file/d/1feTWN8a1SxZhNVsYetpJN47fOs1voSUP/view?usp=sharing)

**Comment by berkaycanbc** [comment]
Happened again.

Environment: `SaaS Prod Enterprise Cluster`
Zeebe version: `8.5.3`
GC logs (internal) : [link](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CMnnmo7wzt_WNw%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22c9d29464-8def-41ae-9d7b-5ecde18638cb-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22;cursorTimestamp=2024-07-01T16:28:19.538810787Z;startTime=2024-07-01T15:58:49.538Z;endTime=2024-07-01T16:58:49.538Z?project=camunda-cloud-240911)
GC logs downloaded (internal): [link](https://drive.google.com/file/d/1Wq1js_tvlw3m7mx3I5vCxlgCJzn0HNtC/view?usp=share_link)

**Comment by deepthidevaki** [comment]
Happened again in the same cluster as [above](https://github.com/camunda/camunda/issues/12918#issuecomment-2205745857)

```
exception: "java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "parentElementInstance" is null
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.getParentElementInstanceContext(BpmnStateBehavior.java:110) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:469) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementActivating(BpmnStateTransitionBehavior.java:447) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:160) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
```

**Comment by Zelldon** [comment]
I think it makes more sense to revert the change if we now what caused it

**Comment by mustafadagher** [comment]
I'm looking at a solution at this issue, and I understand that a possible solution is to `NOT complete instance with children that are yet to be activated` (i.e. has children with intent = `SEQUENCE_FLOW_TAKEN`, ❓ right?). 
But I'm unsure what would be the correct behavior in this case. 
❓ Should we:
1. just ignore element completion
2. append rejection
3. or raise an incident?

**Comment by remcowesterhoud** [comment]
@mustafadagher I believe we need to keep track in the state if there's another batch coming. This way, upon completing the first batch, and we [check if the execution path is completed](https://github.com/camunda/camunda/blob/c13de0443cc87b4d8740ab27d5fe0d57dff87266/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/MultiInstanceBodyProcessor.java#L195), we can check the state if there's another batch coming. If there is, we shouldn't complete the multi-instance body.

[Here](https://github.com/camunda/camunda/blob/c13de0443cc87b4d8740ab27d5fe0d57dff87266/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceBatchActivateProcessor.java#L55) is where we decide if another batch must be written and write the followup batch. I think we'll need to introduce a new event (`ProcessInstanceBatch.ACTIVATING`) which can write the followup batch to the state. And of course we must also clean the state afterwards.

Let me know if you have additional questions. It's not an easy fix.

**Comment by korthout** [comment]
Happened again:
- [logs](https://cloudlogging.app.goo.gl/EG8pyjMHbnE8oXqbA)
- [drive with persisted logs](https://drive.google.com/drive/folders/1JcFCwWnLaYhMG1QIme3LRyfpG9e-PzpD)
