### ISSUE TITLE
Improve gateway timeout logging message

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#13000]
**Description**

[Right now we can see quite often messages like:](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-20-d2345cc-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2023-cw-20-d2345cc-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;timeRange=PT6H;pinnedLogId=2023-06-07T06:00:29.441117780Z%2F2rzuuf3pp7ehiryi;cursorTimestamp=2023-06-07T06:00:29.441117780Z?project=zeebe-io)

```
Expected to handle gRPC request, but request timed out between gateway and broker
```

the message itself is not really helpful, it is lacking lot of context.

Like:

1. What type of request
2. Who was the target broker
3. To which partition this request was sent
4. More?

For better debuggability and understandability of our logs we should improve them otherwise they are just useless and noise.

**Comment by megglos** [comment]
ZDP-Triage:
- may be small scoped enough to do sooner

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Gateway is a shared responsibility, this part might be more related to ZDP, but we're unsure.
- Users will see this message in the client as a response
- The type of request makes total sense to add here
- Are SaaS users interested in the target broker and partition?
- Marking it as `later`. As the scope is unclear we will size it as `medium`.

**Comment by multani** [comment]
I don't have the details of the original log events when this ticket was created, but it seems we (now?) have more information in the stacktrace:

```
Expected to handle gRPC request, but request timed out between gateway and broker

java.util.concurrent.TimeoutException: Request default-command-api-2 to camunda-1.camunda:26501 timed out in PT14.997S
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:307)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

<img width="1111" height="846" alt="Image" src="https://github.com/user-attachments/assets/1ae505bf-0088-4d8b-ae08-1a88dd41d43a" />

At least, it seems:

> What type of request

This seems to be logged now (`default-command-api-2`)

> Who was the target broker

The broker is now logged (`camunda-1`)

> To which partition this request was sent

This doesn't seem to be part of the error message

> More?

The duration is also present.

* [Reference](https://camunda.slack.com/archives/C0ANMGS3D4Y/p1788145472676339)
* [Log events](https://cloudlogging.app.goo.gl/1WeDZpcFTAWeH7Eh6)

**Comment by ChrisKujawa** [comment]
> > To which partition this request was sent

> This doesn't seem to be part of the error message


This is the number at the end of:

> default-command-api-2 

Lets close it then 👍🏼
