### ISSUE TITLE
Reduce noise of the gateway logging

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#13001]
**Description**

This came up on the recent game day that the gateway logs a lot of errors and noise and the logs are not really useful to track errors/issues.

https://confluence.camunda.com/display/ZEEBE/2023-06-06+Game+Day

Examples of these are:

* https://github.com/camunda/zeebe/issues/12780
* https://github.com/camunda/zeebe/issues/13000

But there are more if you just take a look at our normal medic benchmarks you see a lot of not useful logging, either they are missing context or they are just too noisy, etc.

![gw](https://github.com/camunda/zeebe/assets/2758593/ff30ff16-e158-4834-83c3-86638a11d638)

You can see this issue as a overarching issue to improve the logging in the gateway.

**Comment by korthout** [comment]
ZPA triage:
- makes sense to us, and it's a broad topic with many possibilities for improvements
- it's not clearly connected to anything relevant to our team right now
- priority `later` we see no need to improve this right now

**Comment by multani** [comment]
Additionally, this debug event can be logged quite frequently: we had a load test logging about 100 event per second of this debug message for ~20 minutes, creating a short spike in our logging costs:

```
Expected to handle gRPC request, but request timed out between gateway and broker

java.util.concurrent.TimeoutException: Request default-command-api-2 to camunda-1.camunda:26501 timed out in PT14.997S
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:307)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

by `loggerName: "io.camunda.zeebe.gateway"`


<img width="1111" height="846" alt="Image" src="https://github.com/user-attachments/assets/1ae505bf-0088-4d8b-ae08-1a88dd41d43a" />

* [Reference](https://camunda.slack.com/archives/C0ANMGS3D4Y/p1788145472676339)

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ℹ️ Later |
| **Confidence** | 0.96 |

---

### 📝 Rationale

Broad gateway log-noise and debuggability improvement: operational quality-of-life work, not a new capability or single incorrect behavior. It fits medium impact and later timing; #12780 and #13000 are cited examples, not duplicates. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
