### ISSUE TITLE
Error on ProcessInstanceCreation with large variable size

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#13016]
**Describe the bug**

An error was raised due to a large payload on process instance creation. The question to me is whether we want to have this as an error log, or the instance creation will be rejected (the client hopefully gets a response see as an example https://github.com/camunda/zeebe/issues/12873).

Error group https://console.cloud.google.com/errors/detail/CPWQkMjm56Kz5QE;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**To Reproduce**

Create an instance with a large payload, e.g. 2 million entries in an input collection.

**Expected behavior**

We don't see an error, the client got a rejection there is no need to raise here an error. There is nothing we can do as operators.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.stream.api.records.ExceededBatchRecordSizeException: Can't append entry: 'RecordBatchEntry[recordMetadata=RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE_CREATION, intent=CREATED}, key=2251799813686000, sourceIndex=-1, unifiedRecordValue={"bpmnProcessId":"order-process","processDefinitionKey":2251799813685271,"processInstanceKey":2251799813685996,"version":1,"variables":"g6dvcmRlcklk2SRiYTY1YjU5Yi0xNTg0LTQ4YmItYWYwNS0zNzI0ZWExNWZhYzmqdHJhY2tpbmdJZAGlaXRlbXPdAAPQkIGiaWQAgaJpZAGBomlkAoGiaWQDgaJpZASBomlkBYGiaWQGgaJpZAeBomlkCIGiaWQJgaJpZAqBomlkC4GiaWQMgaJpZA2BomlkDoGiaWQPgaJpZBCBomlkEYGiaWQSgaJpZBOBomlkFIGiaWQVgaJpZBaBomlkF4GiaWQYgaJpZBmBomlkGoGiaWQbgaJpZByBomlkHYGiaWQegaJpZB+BomlkIIGiaWQhgaJpZCKBomlkI4GiaWQkgaJpZCWBomlkJoGiaWQngaJpZCiBomlkKYGiaWQqgaJpZCuBomlkLIGiaWQtgaJpZC6BomlkL4GiaWQwgaJpZDGBomlkMoGiaWQzgaJpZDSBomlkNYGiaWQ2gaJpZDeBomlkOIGiaWQ5gaJpZDqBomlkO4GiaWQ8gaJpZD2BomlkPoGiaWQ/gaJpZECBomlkQYGiaWRCgaJpZEOBomlkRIGiaWRFgaJpZEaBomlkR4GiaWRIgaJpZEmBomlkSoGiaWRLgaJpZEyBomlkTYGiaWROgaJpZE+BomlkUIGiaWRRgaJpZFKBomlkU4GiaWRUgaJpZFWBomlkVoGiaWRXgaJpZFiBomlkWYGiaWRagaJpZFuBomlk...' with size: 2118814 this would exceed the maximum batch size. [ currentBatchEntryCount: 4, currentBatchSize: 2119422]
	at io.camunda.zeebe.stream.impl.records.RecordBatch.appendRecord(RecordBatch.java:67) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.BufferedProcessingResultBuilder.appendRecordReturnEither(BufferedProcessingResultBuilder.java:62) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.api.ProcessingResultBuilder.appendRecord(ProcessingResultBuilder.java:38) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:40) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:75) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:346) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.5.jar:8.2.5] 

```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by korthout** [comment]
ZPA triage:
- makes sense to us
- impact is small because reported error is already marked as Acknowledged
- priority `later`

**Comment by koevskinikola** [comment]
Similar occurence but with setting a very large variable ([internal logs link](https://console.cloud.google.com/logs/query;query=error_group%2528%22CN6dsM6mmY3fIw%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.namespace_name%3D%227fa89653-3f58-4c82-9b22-87eeff42dd50-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2023-06-14T07:20:47.491Z%2F2023-06-14T08:20:47.491Z;cursorTimestamp=2023-06-14T07:50:17.491618179Z?project=camunda-saas-int)).

**Comment by berkaycanbc** [comment]
Same issue for event triggering on `8.8.0-alpha7`:

GCP logs: [LINK](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-7%22%0Aresource.labels.location%3D%22asia-southeast1%22%0Aresource.labels.project_id%3D%22camunda-saas-prod-sin%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%22079496f5-5be4-4fb5-82d6-4ebf8d3e788f-zeebe%22;pinnedLogId=2025-10-10T04:28:36.345406270Z%2Fdb2hjfou2xdnph9u;cursorTimestamp=2025-10-10T04:30:23.921271209Z;startTime=2025-10-10T03:59:06.345Z;endTime=2025-10-10T04:59:06.345Z?project=camunda-saas-prod-sin)
GCP logs downloaded: [LINK](https://drive.google.com/file/d/1bChqCSFEhFRkCCGY9apeCoaqul8XhS_Q/view?usp=share_link)
