### ISSUE TITLE
Reject static duration which is too large

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#13879]
**Description**

Related to https://github.com/camunda/zeebe/issues/2108

We decided once to skip this but it turns out that actually, users deploy (who could know this 🤔) such models. This recently caused an error on prod https://console.cloud.google.com/errors/detail/CI_6pI2Uhor3aQ;service=zeebe;time=P7D?project=camunda-cloud-240911

```
java.lang.RuntimeException: java.lang.ArithmeticException: long overflow
	at io.camunda.zeebe.stream.impl.BufferedResult.executePostCommitTasks(BufferedResult.java:57) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.executePostCommitTasks(ProcessingStateMachine.java:591) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$executeSideEffects$18(ProcessingStateMachine.java:566) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:45) ~[zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.11.jar:8.2.11]
Caused by: java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Unknown Source) ~[?:?]
	at java.time.Duration.toNanos(Unknown Source) ~[?:?]
	at io.camunda.zeebe.scheduler.ActorControl.scheduleTimer(ActorControl.java:140) ~[zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.scheduler.ActorControl.runDelayed(ActorControl.java:115) ~[zeebe-scheduler-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$runDelayed$0(ProcessingScheduleServiceImpl.java:50) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.useActorControl(ProcessingScheduleServiceImpl.java:77) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.runDelayed(ProcessingScheduleServiceImpl.java:50) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.runDelayed(ProcessingScheduleServiceImpl.java:55) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.ExtendedProcessingScheduleServiceImpl.runDelayed(ExtendedProcessingScheduleServiceImpl.java:56) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.engine.processing.scheduled.DueDateChecker.schedule(DueDateChecker.java:54) ~[zeebe-workflow-engine-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.engine.processing.timer.DueDateTimerChecker.scheduleTimer(DueDateTimerChecker.java:41) ~[zeebe-workflow-engine-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToTimerEvent$9(CatchEventBehavior.java:293) ~[zeebe-workflow-engine-8.2.11.jar:8.2.11]
	at io.camunda.zeebe.stream.impl.BufferedResult.executePostCommitTasks(BufferedResult.java:55) ~[zeebe-stream-platform-8.2.11.jar:8.2.11]
	... 10 more
```

The duration contained `PT9999999990S` 

![errorprocessduration-process](https://github.com/camunda/zeebe/assets/2758593/6120d063-2747-4cd1-a230-7b5ee39cde50)

Likely this was a test process model, but still we should simply such models if the duration is static.

**Comment by remcowesterhoud** [comment]
Individual triage:
- Easily reproducible.
- The chance of this happening seems quite small, especially when it's a static duration like in the example. Of course having an expression makes it less obvious.
- We could catch static expressions during runtime.
- We should check the result of the duration expressions and create an incident it overflows.
- Worst-case this causes a banned instance.
- We should discuss with the Modeler team about listing rules surrounding this.

Marking as `upcoming` as banned instances should be avoided.
Sizing as `small` as it's easy to reproduce
Marking impact as `medium`. We don't see this happening often, but when it happens it causes banning which is always bad.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ℹ️ Low |
| **Confidence** | 0.93 |

---

### 📝 Rationale

Reproducible timer-duration overflow in a released version can ban a process instance; Core Features owns Zeebe execution. Impact is MID and likelihood LOW based on the documented criteria and existing triage evidence. Related issue #13880 addresses runtime incident handling, not the static-duration rejection, so this is not a duplicate.    

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ℹ️ Low |
| **Confidence** | 0.96 |

---

### 📝 Rationale

Concrete production bug: an excessively large static timer duration causes long overflow and can ban an instance; impact is noticeable but rare, with no evidence of data loss. It belongs to Core Features because Zeebe engine execution is in scope. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
