### ISSUE TITLE
No executable process found while processing Deployment:Create command

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#14055]
**Describe the bug**

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE}, value={...}' without errors, but exception occurred with message 'Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.'.


java.util.NoSuchElementException: Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lambda$updateInMemoryState$2(DbProcessState.java:231) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:228) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupProcessByIdAndPersistedVersion(DbProcessState.java:375) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getLatestProcessVersionByProcessId(DbProcessState.java:271) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.isLatestProcess(StartEventSubscriptionManager.java:64) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:55) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processDistributedCommand(DeploymentCreateProcessor.java:105) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:31) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:126) ~[zeebe-workflow-engine-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:353) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha4.jar:8.3.0-alpha4]

```

The error is repeatedly occurring in partitions 2 and 3. But didn't see it in Partition 1. The error is logged every time, partition 1 retries to distribute the deployment. It looks like the deployment was created successfully in partition 1, but it cannot distributed it to partitions 2 and 3. So the users would assume the deployment was successful, but they cannot create instances on other partitions.

**To Reproduce**

Not sure. Further data for analysis is [here](https://drive.google.com/drive/folders/1g6HlGdY3RwJO1yd1zl3Ld3T7r_CJUxto)

**Expected behavior**

A deployment successfully created in partition 1 should be accepted by other partitions.

**Log/Stacktrace**

[Link to logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-08-29T12:56:18.601486031Z;endTime=2023-08-30T07:23:27.338991Z;pinnedLogId=2023-08-29T12:56:18.601486031Z%2Fenfqgfrxijsl5m8x;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2225697942-1bb8-47f8-9c2e-2d7e6b348a75-zeebe%22%0Aresource.labels.location%3D%22australia-southeast1%22%0Aresource.labels.cluster_name%3D%22prod-worker-4%22%0Atimestamp%3D%222023-08-29T12:56:18.601486031Z%22%0AinsertId%3D%22enfqgfrxijsl5m8x%22;startTime=2023-08-25T12:33:36.208Z;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252FpartitionId:false:32:beginning?project=camunda-cloud-240911)

```

DEBUG 2023-08-29T12:56:18.012401245Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 1] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.490833810Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.492924797Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.493531262Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
DEBUG 2023-08-29T12:56:18.493878660Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Ignoring unknown BPMN element 'http://camunda.org/schema/1.0/bpmn:inputOutput'
ERROR 2023-08-29T12:56:18.601486031Z [resource.labels.podName: zeebe-2] [jsonPayload.context.partitionId: 3] Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE}, value={"resources":...}' without errors, but exception occurred with message 'Expected to find executable process in persisted process with key '2251799813685388', but after transformation no such executable process could be found.'.


```

**Environment:**
- Zeebe Version: 8.3.0-alpha4

Support
https://jira.camunda.com/browse/SUPPORT-24946

**Comment by korthout** [comment]
ZPA Triage:
- potential regression to 8.2 due to generalized distribution for deployments
- possibly something with a race condition between different versions of a process
- size medium, because unclear for now
- priority `upcoming` because this could be quite severe

**Comment by deepthidevaki** [comment]
There were two similar errors, for which I think the root cause might be the same even though it occurred at different places.


[Logs](https://console.cloud.google.com/errors/detail/CL3C3rOOkMXdRw;service=zeebe;time=P7D?project=camunda-cloud-240911)
```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=JOB, intent=COMPLETE}, value={"deadline":-1,"worker":"","retries":-1,"retryBackoff":0,"recurringTime":-1,"type":"","customHeaders":[packed value (length=1)],"variables":"...","errorMessage":"","errorCode":"","bpmnProcessId":"","processDefinitionVersion":-1,"processDefinitionKey":-1,"processInstanceKey":-1,"elementId":"","elementInstanceKey":-1}}' without errors, but exception occurred with message 'No value present'.

java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:178) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupProcessByIdAndPersistedVersion(DbProcessState.java:319) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getLatestProcessVersionByProcessId(DbProcessState.java:215) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.getLatestProcessVersion(BpmnStateBehavior.java:120) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.getProcessForProcessId(CallActivityProcessor.java:170) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:66) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.container.CallActivityProcessor.onActivate(CallActivityProcessor.java:29) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:144) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:143) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:92) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:89) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:140) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:352) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
```

[Logs](https://console.cloud.google.com/errors/detail/CLe7o6_LmPTh4AE;service=zeebe;time=P7D?project=camunda-cloud-240911)

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=DISTRIBUTE}, value={"resources":[{"resourceName":"xxx.bpmn","resource":"...}' without errors, but exception occurred with message 'No value present'.

java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:178) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupProcessByIdAndPersistedVersion(DbProcessState.java:319) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getLatestProcessVersionByProcessId(DbProcessState.java:215) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.isLatestProcess(StartEventSubscriptionManager.java:64) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:55) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.processing.deployment.distribute.DeploymentDistributeProcessor.processRecord(DeploymentDistributeProcessor.java:46) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:140) ~[zeebe-workflow-engine-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:352) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:269) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:228) ~[zeebe-stream-platform-8.2.12.jar:8.2.12]

```

**Comment by korthout** [comment]
Thanks @deepthidevaki That's useful input!

**Comment by nicpuppa** [comment]
Started to look at it last week 👀 Didn't figured out yet how to reproduce.

Could be related to this [PR](https://github.com/camunda/zeebe/pull/13505), but idk

**Comment by rodrigo-lourenco-lopes** [comment]
This error seems to have happened again [here](https://drive.google.com/file/d/171ponXBSGzJyOHyjayfmCceY-44ouQLt/view?usp=sharing) in version 8.5.

**Comment by nicpuppa** [comment]
This error happened in a [support case](https://jira.camunda.com/browse/SUPPORT-23774)

**Comment by remcowesterhoud** [comment]
There is another case https://jira.camunda.com/browse/SUPPORT-24287

**Comment by megglos** [comment]
keeping as upcoming given high severity but in overall still low likelihood

**Comment by remcowesterhoud** [comment]
FWIW, I spend some time digging into this due to the support case I mentioned above and I cannot find any way in which this data incosistency could occur.

**Comment by daniel-ewing** [comment]
Hi @remcowesterhoud, could [this issue](https://github.com/camunda/camunda/issues/25822) be related?

**Comment by remcowesterhoud** [comment]
> Hi @remcowesterhoud, could [this issue](https://github.com/camunda/camunda/issues/25822) be related?

@daniel-ewing I don't think so. @korthout explained that issue quite well https://github.com/camunda/camunda/issues/25822#issuecomment-2532788096

**Comment by megglos** [comment]
Pushing to inbox as the issue surfaced in support once more today (see @nicpuppa 's comment).

**Comment by nicpuppa** [comment]
There is another support case: [SUPPORT-24946](https://jira.camunda.com/browse/SUPPORT-24946)

**Comment by remcowesterhoud** [comment]
Alright, so I looked through the different support cases. I still cannot provide a proper root cause here. My suspicion is that this is caused by deployment distirbutions overtaking each other. We already had [an issue](https://github.com/camunda/camunda/issues/21357) where this made it possible to create process instances for deleted process definitions. It's not a stretch to think the same could happen vice versa, especially as the error occurred on partitions 2 and 3, but not on 1. This problem was solved by [ensuring deployments and deletions are ordered](https://github.com/camunda/camunda/pull/24099).

This fix is already available on all supported versions. To be sure I've also checked the error reporting for all our environments. In the last 30 days (the max I could check) there was no occurrences of this error. This further makes me believe that this problem is likely already fixed by the distribution ordering.

As of now I don't think it's sensible to keep digging deeper. I will close this issue and if it occurs again it should get reopened.
