### ISSUE TITLE
BPMN deployment fails on s390x server

### ISSUE THREAD

**Issue by shahamit** [camunda/camunda#14545]
**Describe the bug**

Deploying a bpmn file on a running zeebe cluster fails with an `IllegalArgumentException` 

**To Reproduce**

We need to deploy zeebe on IBM s390x servers. We made appropriate changes in the Dockerfile (used the right sha256 hash for ubuntu and jdk) to create the docker image. The image is uploaded [here on dockerhub](https://hub.docker.com/layers/shahamitatwork/zeebe/s390x.8.2.12/images/sha256-775abbe548c099053008885d7da8d455150c820be8e677acfaeaf6965862b62a?context=repo). We are using 8.2.12 release and are deploying it through kubernetes and helm chart. The k8s cluster comes up and running well. No errors in the gateway or the broker logs. 

Once we try to deploy a bpmn file through a zeebe client we get an exception in the zeebe logs. 

While going through the logs and zeebe code, I understand that this could be because of byte ordering. Zeebe is designed and coded to work with systems that have LITTLE_ENDIAN byte order while since s390x has BIG_ENDIAN byte ordering the broker fails to read the log stream from the disk.

To start with could someone from the development team confirm that byte ordering is the root cause of the below exception? We can later understand what changes would be needed in zeebe to support systems like s390x. 

**Expected behavior**

The BPMN file deployment and execution should complete successfully.

**Log/Stacktrace**

Below is the java stacktrace in the zeebe broker logs when bpmn deployment is done
```
[Broker-0] [zb-actors-0] [StreamProcessor-1] ERROR       io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED. 

java.lang.IllegalArgumentException: offset=0 length=873267200 not valid for capacity=3384 at org.agrona.concurrent.UnsafeBuffer.boundsCheckWrap(UnsafeBuffer.java:2435) ~[agrona-1.17.2.jar:1.17.2] 
at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:277) ~[agrona-1.17.2.jar:1.17.2] 
at io.camunda.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:59) ~[zeebe-logstreams-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.logstreams.impl.log.LogStreamReaderImpl.next(LogStreamReaderImpl.java:24) ~[zeebe-logstreams-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:225) ~[zeebe-stream-platform-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:204) ~[zeebe-stream-platform-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.12.jar:8.2.12] 
at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.12.jar:8.2.12] 
```

**Environment:**
- OS: Linux
- Processor Architecture s390x
- Zeebe Version: 8.2.12
- Configuration: helm chart

**Comment by megglos** [comment]
Hey @shahamit ,

thanks for reaching out on this. We indeed have never considered support for BIG_ENDIAN and thus also don't have experience with issues caused by this. In fact in some cases we hardcoded a LITTLE_ENDIAN byte order.

Given the error you shared, we also think it may be caused by a lack of BIG_ENDIAN support.

Are you by any means a paying customer of Camunda? In such a case I would recommend you to raise a feature request through our Jira https://jira.camunda.com/ from there our Product Management would pick up and evaluate your request.

**Comment by shahamit** [comment]
@megglos - thanks for reviewing this issue. Could you please help me understand why did we need to hard code the byte ordering instead of letting the default native byte order come into play? Given that both the writer and reader applications were internal components of zeebe I am wondering the need of hard coding the endianness. It would be great if you could elaborate. 
Thanks.

**Comment by npepinpe** [comment]
FYI there is no need to hard code it, but it's important that all nodes in the same cluster use the same encoding, since data is replicated as is, so they need to be able to read what the others are writing.
