### ISSUE TITLE
InvalidConfigurationException when GCS store is not accessible on startup

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#14593]
**Describe the bug**

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-3.1.2.jar:3.1.2]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.2.15.jar:8.2.15]
Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException: Failed configuring backup store GCS
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:132) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: io.camunda.zeebe.backup.gcs.GcsBackupStoreException$ConfigurationException$CouldNotAccessBucketException: Bucket Expected to access bucket 'camunda-saas-int-backup-worker-3', but failed does not exist
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:200) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: com.google.cloud.storage.StorageException: Error getting access token for service account: oauth2.googleapis.com, iss: backups-worker-3@camunda-saas-int.iam.gserviceaccount.com
	at com.google.cloud.storage.StorageException.translate(StorageException.java:165) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:297) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:441) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: oauth2.googleapis.com, iss: backups-worker-3@camunda-saas-int.iam.gserviceaccount.com
	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointIOException(GoogleAuthException.java:166) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:543) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.1-jre.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:938) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc$InvocationIdInitializer.initialize(HttpStorageRpc.java:152) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:431) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more
Caused by: java.net.UnknownHostException: oauth2.googleapis.com
	at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.1-jre.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:581) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:232) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:182) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:938) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96) ~[google-auth-library-oauth2-http-1.16.0.jar:?]
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109) ~[google-cloud-core-http-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc$InvocationIdInitializer.initialize(HttpStorageRpc.java:152) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91) ~[google-http-client-1.43.1.jar:1.43.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:442) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603) ~[google-api-client-2.2.0.jar:2.2.0]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:431) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.lambda$listBlobs$11(StorageImpl.java:421) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.3.jar:2.23.3]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.13.0.jar:2.13.0]
	at com.google.cloud.storage.Retrying.run(Retrying.java:60) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.listBlobs(StorageImpl.java:418) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:384) ~[google-cloud-storage-2.20.2.jar:2.20.2]
	at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig(GcsBackupStore.java:197) ~[zeebe-backup-store-gcs-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg(SystemContext.java:124) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig(SystemContext.java:116) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration(SystemContext.java:71) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.initSystemContext(SystemContext.java:60) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.system.SystemContext.<init>(SystemContext.java:56) ~[zeebe-broker-8.2.15.jar:8.2.15]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:87) ~[camunda-zeebe-8.2.15.jar:8.2.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 3 more

```

Impact:
Fails broker startup. But restart succeeds.

**To Reproduce**

I don't think this is due to an actual configuration error, but because we validate GCS store configuration by trying to connect to the storage. If it is temporarily unavailable, validation fails. 

**Expected behavior**

Temporary errors should not cause validation failures.

**Log/Stacktrace**

[link to logs](https://console.cloud.google.com/errors/detail/CNeMl4mEyt_8NA;service=zeebe;time=P7D?project=camunda-saas-int)

**Environment:**
- Zeebe Version: 8.2.15

**Comment by koevskinikola** [comment]
Happened again:
* Zeebe `8.4.0-alpha1`
* SaaS chaos cluster
* [GCP logs (internal)](https://drive.google.com/file/d/1CZ04r49GIVkeMp4EcMK0BDu1wtzLYqIg/view?usp=sharing)

**Comment by berkaycanbc** [comment]
Happened again:

* Zeebe 8.3.5
* SaaS Enterprise
* [GCP logs (internal)](https://drive.google.com/file/d/15WGbm33pzDtC_a-BxnpP4o16tnJMjMid/view)
* [GCP logs link (internal)](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CITRlba61cf0_gE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22bd9a51f7-d13b-4138-b03b-708e13ee8124-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22;cursorTimestamp=2024-01-26T16:05:20.973500217Z;startTime=2024-01-26T15:35:50.973Z;endTime=2024-01-26T16:35:50.973Z?project=camunda-cloud-240911)

**Comment by berkaycanbc** [comment]
Happened again:

* Zeebe `8.4.1`
* SaaS Enterprise
* [GCP logs link (internal)](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CKXrlLebrZffNA%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%229d2798e3-9f7f-4b0d-8a52-5b1006383505-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.container_name%3D%22zeebe%22;cursorTimestamp=2024-01-29T17:21:22.282114823Z;startTime=2024-01-29T16:51:52.282Z;endTime=2024-01-29T17:51:52.282Z?project=camunda-cloud-240911)
* [GCP logs (internal)](https://drive.google.com/file/d/1KP7vN95YlnuTXQPuif9cDy0CQBmsu3mJ/view)

**Comment by koevskinikola** [comment]
Happened again:
* Zeebe `8.6.0-alpha1-rc4`
* SaaS Int chaos
* [GCP logs JSON (internal)](https://drive.google.com/file/d/1ym_Kw2_qeZmK_QZOBNlJrAS_H-uHrR9v/view?usp=sharing)
* [GCP logs link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22b9eb2392-48c9-4b00-b9bf-486168cb0a3e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22;pinnedLogId=2024-05-14T06:33:57.224095841Z%2F23dp3rl84t4zomat;cursorTimestamp=2024-05-14T06:34:26.198302828Z;startTime=2024-05-14T06:04:27.224Z;endTime=2024-05-14T07:04:27.224Z?project=camunda-saas-int-chaos)

**Comment by korthout** [comment]
Happened again:
- Zeebe `8.5.1`
- SaaS Prod (Suspended - Trial with Low Hardware)
- [GCP logs JSON (internal)](https://drive.google.com/file/d/1dbz9SewJesDZkgI_IO4RbX-nXssKRdgC/view?usp=drive_link)
- [GCP logs links](https://cloudlogging.app.goo.gl/GWpuHUxUxvCtPJhH6)

**Comment by koevskinikola** [comment]
Happened again:
* SaaS Int and Int chaos
* Zeebe `8.4.9` and `8.5.4`
* [GCP link 1](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%220dcca303-985a-409c-b9aa-e4517e9544ab-zeebe%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22;pinnedLogId=2024-08-15T08:03:34.886777001Z%2Fsi7rs0xe9naen1yw;cursorTimestamp=2024-08-15T08:03:34.953398285Z;startTime=2024-08-15T08:00:48.468Z;endTime=2024-08-15T09:00:48.468Z?project=camunda-saas-int)
* [GCP link 2](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%223ea26c44-c431-459c-a1df-566a67936551-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2024-08-15T03:01:37.453546316Z%2F6xffznoco1klr7lv;cursorTimestamp=2024-08-15T03:01:37.512135111Z;startTime=2024-08-15T02:32:07.453Z;endTime=2024-08-15T03:32:07.453Z?project=camunda-saas-int-chaos)
* [GCP logs (internal) 1](https://drive.google.com/file/d/1GDNlojPTOd_y0q9i1XSzAB4EZ41m3h8M/view?usp=sharing)
* [GCP logs (internal) 2](https://drive.google.com/file/d/1sdiJvS3rKC5FWwFceO8q1d5BHlapfTbC/view?usp=sharing)

**Comment by korthout** [comment]
Dropping the validation 'can access gcs store' on startup means we're changing the documented behavior. Let's be conscious about this, as users may rely on this. Please adjust the documentation and mention this change in the update guide accordingly.

>The bucket specified with bucketName must already exist, Zeebe will not try to create one for you. To prevent misconfiguration, **Zeebe will check at startup that the specified bucket** exists and **can be accessed**. - [docs](https://docs.camunda.io/docs/next/self-managed/operational-guides/backup-restore/zeebe-backup-and-restore/)

**Comment by berkaycanbc** [comment]
Happened again:

Zeebe 8.5.10
SaaS Prod
[GCP logs downloaded (internal)](https://drive.google.com/file/d/1XPuDZ8cxg2DJ58ARlFc0qaBRHCM-mhzG/view?usp=share_link)
[GCP error link (internal)](https://console.cloud.google.com/errors/detail/COCr6s-f2ND5ugE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbmX9w&project=camunda-saas-prod)

Cc: @entangled90
