### ISSUE TITLE
Zeebe gateway and brokers spamming atomix-cluster-heartbeat-sender logs, failed to probe

### ISSUE THREAD

**Issue by josepht96** [camunda/camunda#14845]
**Describe the bug**

Zeebe Gateway and Brokers are spamming logs regarding atomix-cluster-heartbeat-sender: Failed to synchronize membership with x, Failed to probe x, Member unreachable, etc... These info and warn messages are present in all of our environments running on Openshift. They have been present since we upgrade to 8.1.12 or so, whenever the verbosity of atomix was changed. We are seeing these errors regardless of whether Istio service mesh is enabled or disabled. We are experiencing general instability around Zeebe, and I would like to get some more information on what might be causing these messages as they might be related. 

Should also mention I have Camunda 8.2.15 running on a Kind cluster on Ubuntu, and this issue is not present (nor has it ever been). If this issue is too specific to our environment/Openshift, I wonder what you might suggest investigating as a potential root cause.

**To Reproduce**

Run Camunda Platform 8.x.x on Openshift
Set logging level to Logger name="io.atomix" level="${env:ATOMIX_LOG_LEVEL:-info}"
(I recognize I can set this to 'error' and not see the messages, but I think the messages might indicate some underlying issue that might be contributing to instability in our installation.)

**Expected behavior**

These messages are not spammed. As long as containers are in a ready state I don't see why probes would be failing.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2023-10-24 20:47:35.767 [] [atomix-cluster-heartbeat-sender] [] INFO
io.atomix.cluster.protocol.swim.probe - 2 - Failed to probe camunda-zeebe-gateway-556fc8687c-fht8z
2023-10-24 20:47:36.311 [] [atomix-cluster-heartbeat-sender] [] INFO
io.atomix.cluster.protocol.swim - 2 - Member unreachable Member{id=camunda-zeebe-gateway-556fc8687c-fht8z, address=10.128.17.208:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
2023-10-24 20:47:40.155 [] [atomix-cluster-heartbeat-sender] [] INFO
io.atomix.cluster.protocol.swim - 2 - Member reachable Member{id=camunda-zeebe-gateway-556fc8687c-fht8z, address=10.128.17.208:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
2023-10-24 20:47:45.280 [] [atomix-cluster-heartbeat-sender] [] WARN
io.atomix.cluster.protocol.swim.probe - 2 - Failed to probe 1
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=6636, subject=atomix-membership-probe, sender=camunda-zeebe-2.camunda-zeebe.camunda-dev.svc:26502, payload=byte[]{length=846, hash=-1592017160}} to camunda-zeebe-1.camunda-zeebe.camunda-dev.svc:26502 timed out in PT0.1S
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.98.Final.jar:4.1.98.Final]
at java.lang.Thread.run(Unknown Source) [?:?]
2023-10-24 20:47:48.979 [] [atomix-cluster-heartbeat-sender] [] WARN
io.atomix.cluster.protocol.swim.sync - 2 - Failed to synchronize membership with Member{id=camunda-zeebe-gateway-556fc8687c-6lw84, address=10.128.10.116:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.2.15, timestamp=1698157587437, state=ALIVE, incarnationNumber=1698157587642}
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=6643, subject=atomix-membership-sync, sender=camunda-zeebe-2.camunda-zeebe.camunda-dev.svc:26502, payload=byte[]{length=441, hash=1468265487}} to 10.128.10.116:26502 timed out in PT0.1S
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.98.Final.jar:4.1.98.Final]
at java.lang.Thread.run(Unknown Source) [?:?]
2023-10-24 20:49:09.475 [] [atomix-cluster-heartbeat-sender] [] INFO
io.atomix.cluster.protocol.swim - 2 - Member unreachable Member{id=1, address=camunda-zeebe-1.camunda-zeebe.camunda-dev.svc:26502, properties={brokerInfo=EADJAAAAAwABAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkzAAAAY2FtdW5kYS16ZWViZS0xLmNhbXVuZGEtemVlYmUuY2FtdW5kYS1kZXYuc3ZjOjI2NTAxBQADAQAAAAECAAAAAAMAAAABDAABAgAAAEUKAAAAAAAABgAAADguMi4xNQUAAwEAAAABAgAAAAEDAAAAAQ==}}
2023-10-24 20:49:10.190 [] [atomix-cluster-heartbeat-sender] [] INFO
io.atomix.cluster.protocol.swim - 2 - Member reachable Member{id=1, address=camunda-zeebe-1.camunda-zeebe.camunda-dev.svc:26502, properties={brokerInfo=EADJAAAAAwABAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkzAAAAY2FtdW5kYS16ZWViZS0xLmNhbXVuZGEtemVlYmUuY2FtdW5kYS1kZXYuc3ZjOjI2NTAxBQADAQAAAAECAAAAAAMAAAABDAABAgAAAEUKAAAAAAAABgAAADguMi4xNQUAAwEAAAABAgAAAAEDAAAAAQ==}}
2023-10-24 20:49:52.008 [] [atomix-cluster-heartbeat-sender] [] WARN
io.atomix.cluster.protocol.swim.probe - 2 - Failed to probe 0
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=6778, subject=atomix-membership-probe, sender=camunda-zeebe-2.camunda-zeebe.camunda-dev.svc:26502, payload=byte[]{length=862, hash=2131899045}} to camunda-zeebe-0.camunda-zeebe.camunda-dev.svc:26502 timed out in PT0.1S
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.98.Final.jar:4.1.98.Final]
at java.lang.Thread.run(Unknown Source) [?:?]
2023-10-24 20:50:03.214 [] [atomix-cluster-heartbeat-sender] [] WARN
io.atomix.cluster.protocol.swim.probe - 2 - Failed to probe camunda-zeebe-gateway-556fc8687c-6lw84
java.util.concurrent.TimeoutException: Request ProtocolRequest{id=6793, subject=atomix-membership-probe, sender=camunda-zeebe-2.camunda-zeebe.camunda-dev.svc:26502, payload=byte[]{length=716, hash=-643724944}} to 10.128.10.116:26502 timed out in PT0.1S
at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAndReceive$4(NettyMessagingService.java:251) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.98.Final.jar:4.1.98.Final]
at java.lang.Thread.run(Unknown Source) [?:?]
```

</p>
</details>

**Environment:**
- OS: Openshift / RHEL
- Zeebe Version: Camunda Platform 8.1.12 - 8.2.15
- Configuration: No exporters, pretty standard configuration. Using standard Camunda 8 Platform helm chart

**Comment by deepthidevaki** [comment]
Could you verify if the network latency is high between the pods? 
If the network latency is high between the brokers
- you could experiment by increasing the configured timeouts. See config parameters under [zeebe.broker.cluster.membership](https://github.com/camunda/zeebe/blob/main/dist/src/main/config/broker.standalone.yaml.template#L492). 
- try enabling compression in the network `ZEEBE_BROKER_CLUSTER_MESSAGECOMPRESSION`

If the network latency is not high, it could be that Zeebe pods are not able to process the requests in time. 
- Do you observe this even when there is no load in the system?

Another potential root cause is https://github.com/camunda/zeebe/issues/13722. Do you see DNS resolution error among the cause for these failures? The error message could be something like `java.net.ConnectException: xxx cannot be resolved`.

**Comment by josepht96** [comment]
I will test increasing the timeout window.

Do you observe this even when there is no load in the system?
Yes

Do you see DNS resolution error among the cause for these failures?
No

**Comment by Zelldon** [comment]
Triage:

@npepinpe wants to check whether it is related to our current DNS issues.

**Comment by josepht96** [comment]
Is atomix using UDP? 
`UDP server listening for connections on 0.0.0.0:26502`

**Comment by deepthidevaki** [comment]
> Is atomix using UDP?

Yes. gossip messages are sent over UDP, everything else is over TCP.

**Comment by namero999** [comment]
Following, since we are experiencing the same issue.

**Comment by namero999** [comment]
How can we override `probeTimeout` via helm charts values?

**Comment by oleschoenburg** [comment]
@namero999 The env var should be correct but you might need to set the same for the gateway with `ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT`

**Comment by namero999** [comment]
Sorry for abusing the thread, but since deployments take a while and you seem online, I might attempt to fix this as well in the same commit...

We are also experiencing a number of `{\"errors\":[{\"code\":\"START_WORKLOAD_ERROR\",\"message\":\"Time out between gateway and broker: Request command-api-1 to camunda-0.camunda.camunda.svc:26501 timed out in PT0.065S\"}],\"kind\":\"errorResponse\",\"kindVersion\":\"1.0.0\"}`

We are not sure where that 60ms timeout comes from... we have not configured it as such in the Java Zeebe client. Is there a config flag to tweak command timeout?

**Comment by oleschoenburg** [comment]
That should be controlled by `ZEEBE_BROKER_GATEWAY_CLUSTER_REQUESTTIMEOUT` if I'm not mistaken. We don't use 65ms as the default anywhere so that would be something that you configured.

**Comment by shahamit** [comment]
We experienced this issue (stacktrace) in our self-managed zeebe cluster (8.2.12).  We tried increasing the probeTimeout on both the broker and gateway but that didn't help. Finally we had to delete the broker's persistent volumes to get workflows running again. The stacktrace showed probe errors, heartbeat failures between the gateway and the broker but the network communication wasn't the root cause. The fix doesn't explain the root cause of what could have caused this.

This had a massive impact on our business operations as the whole zeebe cluster was done.

@deepthidevaki @Zelldon @oleschoenburg -  Any hints on what could have gone wrong so that we can safeguard against such failures? 

Thanks.

**Comment by deepthidevaki** [comment]
@shahamit If deleting persistent volumes fixed the issue, then it is highly likely that the probe errors are not the real reason for the outage you observed.

- What was the actual impact of probe timeouts? Seeing a few such warnings are usually OK. It is not expected if there are no network issues or if the nodes gets restarted. But it is also not the end of the world.
- Was there other errors? Was the system reported as healthy/unhealthy? You can observe a lot of details from the metrics.

**Comment by alexmeise** [comment]
Same experience over here, its a bit counterintuitive to see this logs all the time even if they are "info and warning" they include words like "Failed" "Exception" maybe they should be moved to DEBUG? I would expect a clean INFO log stream if the cluster is healhty.

**Comment by deepthidevaki** [comment]
> Same experience over here, its a bit counterintuitive to see this logs all the time even if they are "info and warning" they include words like "Failed" "Exception" maybe they should be moved to DEBUG? I would expect a clean INFO log stream if the cluster is healhty.

@alexmeise 
As you said, these logs are not expected in a healthy cluster. If such failures are persistent (like in your case) then it indicates some problems and calls for debugging it further. It could be a configuration issue or an unknown bug. Right now, I don't have much insight other than what I have shared [here](https://github.com/camunda/zeebe/issues/14845#issuecomment-1778677875). My suggestion is to look into metrics, logs, heap dumps, tcpdump etc.. to further debug it.

> Since the zeebe cluster started working again after deleting the volumes, could there be a possibility of broker data corruption?

@shahamit 
Could be. But with out any other details, we cannot confirm anything.

**Comment by amitonlentra** [comment]
@deepthidevaki - what details should we capture if such situations arise again? In this case, the logs were the same as posted in the issue description here. 
1. Not sure if heap dumps or metrics would help because the errors were appearing even on multiple restarts and without any new requests being sent for execution. If they help let me know how can we get these metrics through REST apis.
2. In our usage of zeebe, we do end up having a lot of activated processes. These are processes that have incidents. Since there is no manual or automated way of fixing the incidents the processes remain in running state. During the data corruption, we had seen job worker logs of failures in allocating jobs to the workers. These appeared even on restarts which probably indicated that some of the past process executions were attempted. Could you share any insights on this to see if this could somehow be related to the cluster execution failure?

Thanks.

**Comment by shahamit** [comment]
@deepthidevaki  - what details should we capture if such situations arise again? In this case, the logs were the same as posted in the issue description here.

1. Not sure if heap dumps or metrics would help because the errors were appearing even on multiple restarts and without any new requests being sent for execution. If they help let me know how can we get these metrics through REST apis.
2. In our usage of zeebe, we do end up having a lot of activated processes. These are processes that have incidents. Since there is no manual or automated way of fixing the incidents the processes remain in running state. During the data corruption, we had seen job worker logs of failures in allocating jobs to the workers. These appeared even on restarts which probably indicated that some of the past process executions were attempted. Could you share any insights on this to see if this could somehow be related to the cluster execution failure?
Thanks.

**Comment by deepthidevaki** [comment]
@shahamit  You can get metrics via REST api, but analysing it is going to be very difficult. I would recommend to deploy [prometheus + grafana](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/metrics/#grafana). 

The second problem is different. Please open a new issue with relevant information.

**Comment by CanEkinci** [comment]
Hello Everyone,

I experienced similar problems with our Zeebe cluster, where the Zeebe nodes and the gateway were spamming logs with communication and probe issues to gateway nodes.

#### Environment
Kubernetes Cluster
Self-Managed Zeebe Cluster
#### Solution
The issue was due to communication problems related to the Kubernetes configuration with the ClusterIP service for the external gateway. To resolve this, I added a headless service for the internal communication port for the gateway. This allows direct communication to the gateway.

Hope this helps.

**Comment by shahamit** [comment]
@CanEkinci - appreciate your inputs in sharing the fix. I have a question on the implementation

> To resolve this, I added a headless service for the internal communication port for the gateway. This allows direct communication to the gateway.

Could you please elaborate on which files were modified and what changes were done? I am assuming you modified the helm `values.yaml` file to add the headless service for zeebe-gateway but your detailed input would help to get more clarification.

**Comment by CanEkinci** [comment]
@shahamit 

I deployed Zeebe in Version 8.2.19 and used the standard values.yaml. 
I saw that the communication port of the gateway (26502) is not exposed in the gateway service. 
So i added a extra service which is shown below.


```
apiVersion: v1
kind: Service
metadata:
  name: zeebe-gateway-headless
  namespace: zeebe
  labels:
    app: camunda-platform
    app.kubernetes.io/component: zeebe-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/version: 8.2.19
    helm.sh/chart: camunda-platform-8.2.19
    version: 8.2.19
spec:
  selector:
    app: camunda-platform
    app.kubernetes.io/component: zeebe-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/part-of: camunda-platform
    version: 8.2.19
  ports:
    - name: tcp-internal
      protocol: TCP
      port: 26502
      targetPort: 26502
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
```
