### ISSUE TITLE
Flaky test: engine.processing.resource.ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#15388]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances
Error:    Run 1: ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances:259 » Runtime Unexpected error occurred during RocksDB transaction.

---------

Error:  Tests run: 26, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.266 s <<< FAILURE! -- in io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest
Error:  io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances -- Time elapsed: 0.352 s <<< ERROR!
java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction.
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:42)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:324)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.upsert(TransactionalColumnFamily.java:111)
	at io.camunda.zeebe.engine.state.processing.DbBannedInstanceState.banInstance(DbBannedInstanceState.java:68)
	at io.camunda.zeebe.engine.state.processing.DbBannedInstanceState.banProcessInstance(DbBannedInstanceState.java:114)
	at io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances(ResourceDeletionTest.java:259)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: org.rocksdb.RocksDBException: WriteBatch has wrong count
	at org.rocksdb.Transaction.commit(Native Method)
	at org.rocksdb.Transaction.commit(Transaction.java:207)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:136)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInNewTransaction(DefaultTransactionContext.java:62)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33)
	... 6 more
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

Build link: https://github.com/camunda/zeebe/actions/runs/7019579999/job/19097314743?pr=15365

**Comment by berkaycanbc** [comment]
We can mark this one as `later` since it occurred only once for now. We can re-prioritise when it happens again.

**Comment by megglos** [comment]
let's close flakes not having reported for a longer time

**Comment by rodrigo-lourenco-lopes** [comment]
Seems to have happened here again: https://github.com/camunda/camunda/actions/runs/9561067227/job/26354459617?pr=19466
[Unit Test Results (4).zip](https://github.com/user-attachments/files/15905337/Unit.Test.Results.4.zip)

**Comment by nicpuppa** [comment]
Happened again: https://github.com/camunda/camunda/actions/runs/9647064930/job/26605072910

**Comment by megglos** [comment]
I suspect the cause is the direct modification of the state from the test thread, similar to this fix https://github.com/camunda/camunda/issues/13424

**Comment by lenaschoenburg** [comment]
This still occurs, now with a slightly different error message but I think the underlying cause is still the same:
```
  shouldWriteEventsForDeletedProcessWithBannedInstances (Flaky Test): io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest

java.lang.RuntimeException: Unexpected error occurred during RocksDB transaction.
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:42)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.upsert(TransactionalColumnFamily.java:121)
	at io.camunda.zeebe.engine.state.processing.DbBannedInstanceState.banInstance(DbBannedInstanceState.java:68)
	at io.camunda.zeebe.engine.state.processing.DbBannedInstanceState.banProcessInstance(DbBannedInstanceState.java:114)
	at io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances(ResourceDeletionTest.java:264)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: org.rocksdb.RocksDBException: WriteBatch has wrong count
	at org.rocksdb.Transaction.commit(Native Method)
	at org.rocksdb.Transaction.commit(Transaction.java:216)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.commitInternal(ZeebeTransaction.java:147)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInNewTransaction(DefaultTransactionContext.java:62)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:33)
	... 6 more
```
from https://github.com/camunda/camunda/actions/runs/10212076887#summary-28254664910

I'd suggest to use a new transaction when banning the instance. That's what happens in production code too.

**Comment by ana-vinogradova-camunda** [comment]
Happened again:

```
Error:    Run 1: ResourceDeletionTest.shouldWriteEventsForDeletedProcessWithBannedInstances:264 ? Runtime Unexpected error occurred during RocksDB transaction.
```

Build: https://github.com/camunda/camunda/actions/runs/10292928256/job/28488293200

**Comment by Zelldon** [comment]
https://github.com/camunda/camunda/actions/runs/10609717190/job/29405906418

**Comment by tmetzke** [comment]
Mob programming:
* We interpret the flakiness as the following:
  * At least two threads (engine and test thread) alter the `WriteBatch` of RocksDB concurrently.
  * The `WriteBatch` is not thread-safe, thus both threads might increase the number of entries without respecting the additions of the other.
  * Even `Engine::pauseProcessing` doesn't prevent 100% that no further adjustments to RocksDB are made after it's called. Thus, the test thread and the engine threads can still concurrently alter RocksDB and lead to a wrong number in the `WriteBatch`
* As proposed by @lenaschoenburg, using a separate transaction to ban the instance should prevent this as the `WriteBatch` exists per transaction and thus cannot be altered concurrently by the test thread and the engine thread.
