### ISSUE TITLE
LongPollingActivateJobsTest `shouldOnlyMakeJobsReactivatableInCurrentIterationWhenJobsAreNotReturned` is flaky

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#16751]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 1
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 

Right cannot be returned by isAborted()
isAborted() should return boolean
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  Tests run: 28, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.27 s <<< FAILURE! -- in io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsTest
Error:  io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsTest.shouldOnlyMakeJobsReactivatableInCurrentIterationWhenJobsAreNotReturned -- Time elapsed: 0.078 s <<< ERROR!
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 

Right cannot be returned by isAborted()
isAborted() should return boolean
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

	at io.camunda.zeebe.gateway.impl.job.InflightActivateJobsRequest.isAborted(InflightActivateJobsRequest.java:186)
	at io.camunda.zeebe.test.util.TestUtil.lambda$waitUntil$2(TestUtil.java:36)
	at io.camunda.zeebe.test.util.TestUtil$Invocation.lambda$until$4(TestUtil.java:89)
	at io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:179)
	at io.camunda.zeebe.test.util.TestUtil$Invocation.whileConditionHolds(TestUtil.java:149)
	at io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:88)
	at io.camunda.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)
	at io.camunda.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)
	at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsTest.shouldOnlyMakeJobsReactivatableInCurrentIterationWhenJobsAreNotReturned(LongPollingActivateJobsTest.java:833)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

- [CI logs](https://github.com/camunda/zeebe/actions/runs/8164569795/job/22320078151)
- [Downloaed logs](https://drive.google.com/file/d/1XG1ij49UMqRXrzoWNBtYqH9iznDlaa42/view?usp=drive_link) (internal)

**Comment by korthout** [comment]
Please investigate, and set priority based on ease of fix vs potential hidden bug

**Comment by berkaycanbc** [comment]
Had a quick Look at this one. Might be related to stubbing the mock inside a thread:

https://github.com/camunda/zeebe/blob/81ccc8982bd1f4ac9ab63454f4f34338223b9893/zeebe/gateway/src/test/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsTest.java#L820-L833

Above, we are stubbing the mock while handling the request. Then, we are calling the activate jobs here:
https://github.com/camunda/zeebe/blob/81ccc8982bd1f4ac9ab63454f4f34338223b9893/zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/LongPollingActivateJobsHandler.java#L269-L282

It is discouraged in Mockito docs: https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe

I am not sure about how likely is it since we have only 2 jobs to activate in the test class.

**Comment by korthout** [comment]
Unassigned due to unavailability

**Comment by deepthidevaki** [comment]
Failed again https://github.com/camunda/camunda/actions/runs/9353493685
[Test results for unit tests.zip](https://github.com/user-attachments/files/15543705/Test.results.for.unit.tests.2.zip)

**Comment by mustafadagher** [comment]
I managed to repeatedly reproduce this locally by debugging the test, adding a break point at the line `doReturn(responseNotSent).when(request).tryToSendActivatedJobs(any());` and stepping into the method `tryToSendActivatedJobs`

or by debugging too slow until there's a TimeoutException thrown by the actor scheduler.

I think, like the error message suggests, this has something to do with mockito `spy` and multi-currency tests. 

I'm still not sure at this point what would be a solution.

**Comment by mustafadagher** [comment]
Zeebe Mob-programming (@korthout , @koevskinikola  and @mustafadagher):
Let's try to deeper understand the following: 
- what this test is trying to verify 
- understand the need for this test
- if there other ways to verify this functionality or whether we already have another test that cover it
- and whether this functionality needs a re-write so it's better testable.

**Comment by mustafadagher** [comment]
for reference, this is the [PR](https://github.com/camunda/camunda/pull/8879) where this test was created.

**Comment by Zelldon** [comment]
https://github.com/camunda/camunda/commit/551a9013f876f5159e6373d839ce571c8e2c310f again

**Comment by megglos** [comment]
@mustafadagher given you have context, let's sync if you can take this

**Comment by mustafadagher** [comment]
Hi @megglos, I managed to reproduced earlier indeed, but I couldn't spot the root-cause. I had doubts that the issue lies in the test setup.
I also brought it before to the mob-programming were I presented all my research and findings, and still we couldn't put our hands on the issue as a group. But we couldn't even understand what the test was trying to verify, the need for it, and we suggested it needs an effort to analyze, understand, and re-write it.
That makes the scope bigger than just fixing a flake, and I'm not sure if I'm up to take this effort right now.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ⚠️ Mid |
| **When** | ℹ️ Later |
| **Confidence** | 0.95 |

---

### 📝 Rationale

Concrete flaky-test/CI maintenance issue, not a confirmed product defect: it occurred once, does not block work, and is not suspected to be real; discussion points to Mockito concurrency in the test setup.  This is a medium-impact reliability improvement that can wait because it is rare and non-blocking.  Gateway and Zeebe execution are within Core Features ownership. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.
