### ISSUE TITLE
Incompatible versions between Zeebe broker, Operate and hazelcast when I use DMN in process

### ISSUE THREAD

**Issue by portugalw** [camunda/camunda#16925]
**Describe the bug**

I have a problem when I use DMN in zeebe new versions.

Incompatible versions between Zeebe broker, Operate and hazelcast when I use DMN in process:

Zeebe 8.1.9 Operate 8.1.9  zeebe-hazelcast-exporter 1.2.1 = Works Fine!
Zeebe 8.2.12 Operate 8.2.12  zeebe-hazelcast-exporter 1.2.1 = Doesn't Work!
Zeebe 8.2.12 Operate 8.2.12  zeebe-hazelcast-exporter 1.4.0 = Doesn't Work!
Zeebe 8.3.7 Operate 8.3.7  zeebe-hazelcast-exporter 1.2.1 = Doesn't Work!
Zeebe 8.3.7 Operate 8.3.7  zeebe-hazelcast-exporter 1.4.0 = Doesn't Work!

Every time when the process pass through the DMN, the following error was thrown:

2024-03-14 17:09:02 2024-03-14 20:09:02.428 [Broker-0] [zb-fs-workers-1] [Exporter-1] ERROR
2024-03-14 17:09:02       io.camunda.zeebe.broker.exporter - Actor 'Exporter-1' failed in phase STARTED with: java.lang.NoSuchMethodError: 'long io.camunda.zeebe.protocol.record.value.EvaluatedDecisionValue.getDecisionVersion()' .
2024-03-14 17:09:02 java.lang.NoSuchMethodError: 'long io.camunda.zeebe.protocol.record.value.EvaluatedDecisionValue.getDecisionVersion()'

**To Reproduce**

0 - Use DOCKER enviroment to Zeebe and OPERATE and ElasticSearch
1 - Create a process with DMN.
2 - Advance the tasks and pass through DMN
3 - The greeen signal stops in the DMN and run forever
4 - When I starts new process, it doesn't appear in the operate.

**Expected behavior**

**Log/Stacktrace**

2024-03-14 17:09:02 2024-03-14 20:09:02.428 [Broker-0] [zb-fs-workers-1] [Exporter-1] ERROR
2024-03-14 17:09:02       io.camunda.zeebe.broker.exporter - Actor 'Exporter-1' failed in phase STARTED with: java.lang.NoSuchMethodError: 'long io.camunda.zeebe.protocol.record.value.EvaluatedDecisionValue.getDecisionVersion()' .
2024-03-14 17:09:02 java.lang.NoSuchMethodError: 'long io.camunda.zeebe.protocol.record.value.EvaluatedDecisionValue.getDecisionVersion()'
2024-03-14 17:09:02     at io.zeebe.exporter.proto.RecordTransformer.toEvaluatedDecision(RecordTransformer.java:612) ~[?:?]
2024-03-14 17:09:02     at io.zeebe.exporter.proto.RecordTransformer.toDecisionEvaluationRecord(RecordTransformer.java:571) ~[?:?]
2024-03-14 17:09:02     at io.zeebe.exporter.proto.RecordTransformer.toProtobufMessage(RecordTransformer.java:163) ~[?:?]
2024-03-14 17:09:02     at io.zeebe.exporter.proto.RecordTransformer.toGenericRecord(RecordTransformer.java:174) ~[?:?]
2024-03-14 17:09:02     at io.zeebe.hazelcast.exporter.HazelcastExporter.recordToProtobuf(HazelcastExporter.java:160) ~[?:?]
2024-03-14 17:09:02     at io.zeebe.hazelcast.exporter.HazelcastExporter.export(HazelcastExporter.java:147) ~[?:?]
2024-03-14 17:09:02     at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:181) ~[zeebe-broker-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:180) ~[zeebe-broker-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:167) ~[zeebe-broker-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:528) ~[zeebe-broker-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02     at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.12.jar:8.2.12]
2024-03-14 17:09:02 2024-03-14 20:09:02.440 [Broker-0] [zb-actors-0] [ZeebePartition-1] WARN 
2024-03-14 17:09:02       io.camunda.zeebe.broker.system - Exporter-1 failed, marking it as unhealthy: Exporter-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=java.lang.NoSuchMethodError: 'long io.camunda.zeebe.protocol.record.value.EvaluatedDecisionValue.getDecisionVersion()', cause=null]}
2024-03-14 17:13:58 2024-03-14 20:13:58.708 [Broker-0] [zb-fs-workers-0] [SnapshotStore-1] INFO 
2024-03-14 17:13:58       io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 3584-1-5344-4063
</p>
</details>

**Environment:**
- OS: Docker on LINUX
: compose:

services:
  elasticsearch: # https://hub.docker.com/_/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.17.0}
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      # allow running with low disk space
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - camunda-platform

  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: MYREGISTRY/camunda/zeebe:${CAMUNDA_PLATFORM_VERSION:-8.2.12}
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      # allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: always
    volumes:
      - zeebe:/usr/local/zeebe/data
      - ./.compose-configs/zeebe-hazelcast-exporter-1.2.1-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./.compose-configs/application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

  operate: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#operate
    image: MYREGISTRY/operate:${CAMUNDA_PLATFORM_VERSION:-8.2.12}
    container_name: operate
    ports:
      - "8081:8080"
    environment: # https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - camunda-platform
      - identity-network
    depends_on:
      - zeebe
      - elasticsearch

volumes:
  zeebe:
  elastic:
  postgres:

networks:
  # Note there are two bridge networks: One for Camunda Platform and one for Identity.
  camunda-platform:
  identity-network:

**Comment by npepinpe** [comment]
This seems to be an incompatibility issue specifically with the proto encoder, i.e. https://github.com/camunda-community-hub/zeebe-exporter-protobuf/tree/main used by the Hazelcast exporter. Please raise this issue there, or with the [Hazelcast exporter](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter), are both are community projects.
