### ISSUE TITLE
Flaky test `RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut`

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#17029]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? just [once](https://github.com/camunda/zeebe/actions/runs/8375596556/job/22933276898)
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut
Error:    Run 1: RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut:109 » ConditionTimeout Condition with alias 'Snapshot chunk-0 is resend' didn't complete within 10 seconds because assertion condition defined as a Lambda expression in io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest [Should resent snapshot chunk] 
expected: 2
 but was: 3.
Error:    Run 2: RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut:109 » ConditionTimeout Condition with alias 'Snapshot chunk-0 is resend' didn't complete within 10 seconds because assertion condition defined as a Lambda expression in io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest [Should resent snapshot chunk] 
expected: 2
 but was: 3.
[INFO]   Run 3: PASS
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

Full test results: [Google Drive](https://drive.google.com/file/d/1D12F1Qwm7UAqiROVTBr36WpI_jm6-N8G/view?usp=drive_link)

<details><summary>Logs</summary>
<pre>
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.59 s <<< FAILURE! -- in io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest
Error:  io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut -- Time elapsed: 11.58 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'Snapshot chunk-0 is resend' didn't complete within 10 seconds because assertion condition defined as a Lambda expression in io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest [Should resent snapshot chunk] 
expected: 2
 but was: 3.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest.shouldResentSnapshotIfFirstChunkTimedOut(RaftSnapshotReplicationFailureHandlingTest.java:109)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: org.opentest4j.AssertionFailedError: [Should resent snapshot chunk] 
expected: 2
 but was: 3
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.atomix.raft.RaftSnapshotReplicationFailureHandlingTest.lambda$shouldResentSnapshotIfFirstChunkTimedOut$1(RaftSnapshotReplicationFailureHandlingTest.java:113)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Comment by korthout** [comment]
Occurred again:
- https://github.com/camunda/zeebe/actions/runs/8377885853/job/22941056785
- [Drive](https://drive.google.com/file/d/1JAZXAZqwkkJdwwNaDtMsEHol6iX-V4SW/view?usp=drive_link)

**Comment by korthout** [comment]
And again: https://github.com/camunda/zeebe/actions/runs/8378783498/job/22944170157

**Comment by Zelldon** [comment]
Caused failing to merge a PR https://github.com/camunda/zeebe/actions/runs/8419829648/job/23053285031

**Comment by Zelldon** [comment]
Failed again on main https://camunda.slack.com/archives/C013MEVQ4M9/p1711371411740999

**Comment by mustafadagher** [comment]
Failed a few times with me this afternoon. Here is a sample run logs.

- [Unit tests summary](https://github.com/camunda/zeebe/actions/runs/8435584500/attempts/3#summary-23104116087)

- [Raw logs](https://productionresultssa3.blob.core.windows.net/actions-results/ab1d9765-0656-4467-a929-35747867b425/workflow-job-run-b8245a8d-c8fe-58cd-5361-3fdfc2c073c3/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-26T13%3A37%3A06Z&sig=FT%2B8sRaWekEgKMkorSHjAhO7HhqI8iifKY7Q5vDQUks%3D&sp=r&spr=https&sr=b&st=2024-03-26T13%3A27%3A01Z&sv=2021-12-02)

**Comment by berkaycanbc** [comment]
Occurred again: https://github.com/camunda/zeebe/actions/runs/8516472140/job/23325549252

**Comment by berkaycanbc** [comment]
Occurred again: https://github.com/camunda/zeebe/actions/runs/8530722345/job/23369041205#step:8:4173

**Comment by mustafadagher** [comment]
happened again [here](https://github.com/camunda/camunda/actions/runs/10579572748) (in a merge queue run to stable/8.5)
Logs: [Test results for unit tests](https://drive.google.com/file/d/1XexSm-EBQ6jVFqUQMojThz3gFx6oPgH2/view?usp=drive_link)

**Comment by npepinpe** [comment]
Not planned for now, has not occurred in the last week.
