### ISSUE TITLE
Partition stays in force configuration after force failover

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#17334]
In some failed e2e multi-region failover test, failback took long time because a partition did not come out of forced configuration for almost 1hr. Eventually it succeeds though, but the test failed because of the timeout. It is not expected to take so long. Coming out of force configuration should be done with in seconds after force configuration is succeeded.
 
Example of such a run: https://camunda.slack.com/archives/C013MEVQ4M9/p1711523599459309 

We can see the following error repeated for almost 1 hour. Then eventually the operation succeeds (probably after a leader change.)
```
java.util.concurrent.CompletionException: io.atomix.primitive.PrimitiveException$Unavailable: Force configuration change is in progress. Cannot accept request from 3 which is not a member of the new configuration.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at io.atomix.raft.impl.ReconfigurationHelper.lambda$joinWithRetry$5(ReconfigurationHelper.java:135) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.atomix.primitive.PrimitiveException$Unavailable: Force configuration change is in progress. Cannot accept request from 3 which is not a member of the new configuration.
	at io.atomix.raft.RaftError$Type$5.createException(RaftError.java:139) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.atomix.raft.RaftError.createException(RaftError.java:65) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.atomix.raft.impl.ReconfigurationHelper.lambda$joinWithRetry$5(ReconfigurationHelper.java:133) ~[zeebe-atomix-cluster-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	... 10 more
```

related to #16126

**Comment by koevskinikola** [comment]
@deepthidevaki we encountered the same problem on a `8.9.0-SNAPSHOT` cluster that was involved in an E2E test, same as the description in this issue.

I've downloaded the logs [here (internal link)](https://drive.google.com/file/d/10WYEFKkpG2N1XywcAfD0JMHdq7kechLo/view?usp=sharing).

The GCP logs can be viewed [here (internal link)](https://console.cloud.google.com/logs/query;query=resource.labels.namespace_name%3D%22b4aef7e1-a0a3-4bd8-ba53-50b168ea0c09-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2025-12-15T07:23:24.321918347Z%2F1bhr1qamye60v9iw;cursorTimestamp=2025-12-15T07:23:26.779692714Z;startTime=2025-12-15T05:53:11.489Z;endTime=2025-12-15T10:10:38.297Z?project=camunda-saas-int-chaos).

We also opened an incident for it [here](https://camunda.slack.com/archives/C0A3HMQRTLM).

I'll re-open the issue for re-evaluation.
