### ISSUE TITLE
Improve error mapping of REST API

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#17441]
**Description**

Several common errors may be thrown in the REST API which are currently incorrectly mapped to the internal server error code (500):

- [x] `BrokerClient` `TimeoutException`, which should be mapped to gateway timeout (502).
- [x] `MessagingException$ConnectionClosed`, which should be mapped to gateway timeout (502).
- [x] `BrokerClient` `ConnectException`, which should be mapped to service unavailable (503).
- [x] `BrokerClient` `ConnectTimeoutException`, which should be mapped to service unavailable (503).
- [x] `BrokerClient` `PartitionNotFoundException`, which should be mapped to service unavailable (503).
- [x] `MsgPackException`, `JsonParseException`, `IllegalArgumentException`, which should all map to 400 (or some variant), indicating the request is the issue.
- [x] `RequestRetriesExhaustedException` should be mapped to 429.

Possibly I missed some. But the above are important to allow us to continue computing the SLI/SLO/SLA correctly, so I would urge the priority to be increased. While it's not a bug per se (since, well, this isn't "breaking" anything), happy to have it treated as one.

**Comment by npepinpe** [comment]
FYI @tmetzke - please make sure it gets discussed next triage session for ZPA :) (of course if there's a lack of capacity I can also take a look, but I don't want to step on your toes).

**Comment by tmetzke** [comment]
@npepinpe, thanks for bringing this up 👍 
It's in the backlog for the Zeebe REST API now with an `Upcoming` priority so it's tackled as one of the next tasks.
Please feel free to move ahead here if you have time, no worries about my toes 😃

**Comment by npepinpe** [comment]
Please add `MessagingException$ConnectionClosed` and handle it like `ConnectException`. See https://github.com/camunda/zeebe/issues/18339 for context.

**Comment by ana-vinogradova-camunda** [comment]
Observed for zeebe-SNAPSHOT  in [Saas Int](https://console.cloud.google.com/errors/detail/CKmWxbyurL2coQE;service=zeebe;time=P7D;locations=global?project=camunda-saas-int):

```
io.camunda.zeebe.broker.client.api.PartitionNotFoundException: Expected to execute command on partition 0, but either it does not exist, or the gateway is not yet aware of it

at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.determineBrokerNodeIdProvider ( io/camunda.zeebe.broker.client.impl/BrokerRequestManager.java:215 )
at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.sendRequestInternal ( io/camunda.zeebe.broker.client.impl/BrokerRequestManager.java:114 )
at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.lambda$sendRequestInternal$1 ( io/camunda.zeebe.broker.client.impl/BrokerRequestManager.java:102 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:83 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
```

**Comment by npepinpe** [comment]
Re Ana's latest stack trace, there is no partition 0, so this is definitely wrong :)

**Comment by rodrigo-lourenco-lopes** [comment]
Also observed in again in [camunda-cloud for 8.5.8](https://console.cloud.google.com/errors/detail/CKmWxbyurL2coQE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911), but I guess the improvements were not backported.

```
io.camunda.zeebe.broker.client.api.PartitionNotFoundException: Expected to execute command on partition 0, but either it does not exist, or the gateway is not yet aware of it
	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.determineBrokerNodeIdProvider(BrokerRequestManager.java:209) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:113) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.lambda$sendRequestInternal$1(BrokerRequestManager.java:101) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	```

**Comment by tmetzke** [comment]
> Also observed in again in [camunda-cloud for 8.5.8](https://console.cloud.google.com/errors/detail/CKmWxbyurL2coQE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911), but I guess the improvements were not backported.
> 
> ```
> io.camunda.zeebe.broker.client.api.PartitionNotFoundException: Expected to execute command on partition 0, but either it does not exist, or the gateway is not yet aware of it
> 	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.determineBrokerNodeIdProvider(BrokerRequestManager.java:209) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.sendRequestInternal(BrokerRequestManager.java:113) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.broker.client.impl.BrokerRequestManager.lambda$sendRequestInternal$1(BrokerRequestManager.java:101) ~[zeebe-broker-client-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
> 	```
> ```

Good point, I'll have a look whether we can easily backport this change to 8.5 or not 👍

**Comment by tmetzke** [comment]
✅ Backported to `stable/8.5` now as well, thanks @koevskinikola 🦖
