### ISSUE TITLE
Several flaky tests in  io.camunda.zeebe.it.client.command.AssignUserTaskTest

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#17668]
**Summary**

- How often does the test fail? Once
- Does it block your work? No 
- Do we suspect that it is a real failure?

**Failures**

shouldRejectIfUserTaskIsAlreadyAssignedWithProhibitedOverride: io.camunda.zeebe.it.client.command.AssignUserTaskTest
```
[Expected a created user task] 
Expecting actual:
  -1L
to be greater than:
  0L
java.lang.AssertionError: 
[Expected a created user task]
Expecting actual:
-1L
to be greater than:
0L


at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:187)
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:173)
at io.camunda.zeebe.it.client.command.AssignUserTaskTest.initClientAndInstances(AssignUserTaskTest.java:42)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

shouldRejectIfMissingAssignee: io.camunda.zeebe.it.client.command.AssignUserTaskTest
```
java.lang.AssertionError: 
[Expected a created user task] 
Expecting actual:
  -1L
to be greater than:
  0L
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:187)
at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:173)
at io.camunda.zeebe.it.client.command.AssignUserTaskTest.initClientAndInstances(AssignUserTaskTest.java:42)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
**Hypotheses**

None

**Logs**
https://github.com/camunda/zeebe/actions/runs/8786220325

[Test results for [IT] QA Integration Tests.zip](https://github.com/camunda/zeebe/files/15072345/Test.results.for.IT.QA.Integration.Tests.zip)

**Comment by korthout** [comment]
Unassigning due to unavailability.

**Comment by berkaycanbc** [comment]
There is a chance that the flakiness might not be resolved with PR https://github.com/camunda/camunda/pull/19081. Please re-open the issue if it occurs again.

**Comment by berkaycanbc** [comment]
Happened again but for only one test `shouldRejectIfUserTaskIsAlreadyAssignedWithProhibitedOverride`.

CI: https://github.com/camunda/camunda/actions/runs/9777969604/job/26993855015
[Test results](https://github.com/user-attachments/files/16085480/9_.IT.Zeebe.QA.-.Integration.Tests.txt.zip)

**Comment by Zelldon** [comment]
```  shouldRejectIfUserTaskIsAlreadyAssignedWithProhibitedOverride (Flaky Test): io.camunda.zeebe.it.client.command.AssignUserTaskTest
java.lang.AssertionError: 
[Expected a created user task] 
Expecting actual:
  -1L
to be greater than:
  0L

	at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:187)
	at io.camunda.zeebe.it.util.ZeebeResourcesHelper.createSingleUserTask(ZeebeResourcesHelper.java:173)
	at io.camunda.zeebe.it.client.command.AssignUserTaskTest.initClientAndInstances(AssignUserTaskTest.java:41)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

https://github.com/camunda/camunda/actions/runs/9790688195

**Comment by megglos** [comment]
as it occurred again, please revisit @berkaycanbc

**Comment by lenaschoenburg** [comment]
Happened again: https://github.com/camunda/camunda/actions/runs/10077333110/job/27859638369
