### ISSUE TITLE
 io.atomix.raft.ReconfigurationTest$Joining.shouldFormNewQuorum is flaky

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#18054]
**Summary**

- How often does the test fail? - Once
- Does it block your work? - No
- Do we suspect that it is a real failure? -Not sure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:781)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at io.atomix.raft.impl.ReconfigurationHelper.lambda$joinWithRetry$5(ReconfigurationHelper.java:123)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Logs**

Link to the build: https://github.com/camunda/zeebe/actions/runs/8877407846/job/24370945897?pr=17504

**Comment by korthout** [comment]
Removing from ZPA board, as this is in atomix

**Comment by berkaycanbc** [comment]
Happened again:

Build: https://github.com/camunda/camunda/actions/runs/9226598236/job/25386731965
Downloaded logs: [link (internal)](https://drive.google.com/drive/folders/1_Gr5pTxwGIlghj4Ovf-UoE0eMNQgadId)

**Comment by deepthidevaki** [comment]
@berkaycanbc The files you have uploaded are not useful. What we need is the Artifacts from the failed test. Here it is from the previous failed run. 

[Test results for unit tests.zip](https://github.com/camunda/camunda/files/15496315/Test.results.for.unit.tests.1.zip)

**Comment by nicpuppa** [comment]
It happened again: https://github.com/camunda/camunda/actions/runs/10450168824

[Test results for unit tests (1).zip](https://github.com/user-attachments/files/16658554/Test.results.for.unit.tests.1.zip)

**Comment by deepthidevaki** [comment]
> It happened again: https://github.com/camunda/camunda/actions/runs/10450168824 https://github.com/camunda/camunda/actions/runs/10451253160/job/28937304725
> 
> [Test results for unit tests (1).zip](https://github.com/user-attachments/files/16658554/Test.results.for.unit.tests.1.zip)

This is a different test. Opened a new issue #21759
