### ISSUE TITLE
How to deploy gateway and broker independently zeebe

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/camunda#18640]
How to deploy gateway and broker independently zeebe？
I deployed the zeebe gateway and broker separately according to the documentation, but when requesting the gateway, I received a prompt or error.
`io.camunda.zeebe.client.api.command.ClientStatusException: Expected to send the request to a partition in the topology, but gateway does not know broker topology. Please try again later. If the error persists contact your zeebe operator.
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:93)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:50)
	at com.qzing.orchestration.config.Test.main(Test.java:29)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Expected to send the request to a partition in the topology, but gateway does not know broker topology. Please try again later. If the error persists contact your zeebe operator.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:48)
	... 1 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Expected to send the request to a partition in the topology, but gateway does not know broker topology. Please try again later. If the error persists contact your zeebe operator.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ChrisKujawa** [comment]
I think this issue is stale/obsolete
