### ISSUE TITLE
Zeebe partition term resets to 0

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#19290]
**Describe the bug**

We observed a cluster where one partition exhibits strange behavior after all brokers were restarted. Partition 1 reset from term 890 back to term 0. We only noticed this because shortly after the following error occurred:

```
java.lang.IllegalStateException: Expected to delete index after 405346786, but it is lower than the commit index 405346787. Deleting committed entries can lead to inconsistencies and is prohibited.
	at io.atomix.raft.storage.log.RaftLog.deleteAfter(RaftLog.java:168) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.roles.PassiveRole.tryToAppend(PassiveRole.java:565) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:511) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:367) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:50) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:187) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$14(RaftContext.java:292) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$21(RaftContext.java:303) ~[zeebe-atomix-cluster-8.2.15.jar:8.2.15]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.2.15.jar:8.2.15]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Some time later, the partition recovered, at least in the sense that it was healthy on all replicas.
Additional investigation of the logs is needed.

Logs: https://cloudlogging.app.goo.gl/Tsmpqw4dGXit1d7K6
Error group: https://console.cloud.google.com/errors/detail/CIeaxavmhN308QE?project=camunda-cloud-240911

**Environment:**
- Zeebe Version: 8.2.15

**Comment by lenaschoenburg** [comment]
A rough collection of relevant log messages:
## Before restart

### Zeebe-0
```
2024-06-11 18:54:00.551 zeebe-0 1 RaftServer{raft-partition-partition-1} - Commit index is 405349346. RaftServer is ready
2024-06-11 18:54:23.783 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 1
2024-06-11 18:54:23.865 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=890, candidate=1, lastLogIndex=405349346, lastLogTerm=889}: candidate's log i
2024-06-11 18:54:29.664 zeebe-0 1 Transition to FOLLOWER on term 890 completed
```
### Zeebe-1
```
2024-06-11 18:54:00.397 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 0
2024-06-11 18:54:05.503 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 0 since 5000ms
2024-06-11 18:54:05.722 zeebe-1 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 405349347. RaftServer is ready only after it has committed events upto this index
2024-06-11 18:54:25.894 zeebe-1 1 Transition to LEADER on term 890 completed
```

### Zeebe-2
```
2024-06-11 18:54:05.641 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 18:54:13.220 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 1 since 7503ms
2024-06-11 18:54:25.332 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 18:54:25.341 zeebe-2 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 405349347. RaftServer is ready only after it has committed events upto this index
2024-06-11 18:54:30.026 zeebe-2 1 Transition to FOLLOWER on term 890 completed
```
## After restart
### Zeebe-0
```
2024-06-11 19:04:02.094 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from a known leader since 2508ms
2024-06-11 19:04:02.321 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 0
2024-06-11 19:04:02.421 zeebe-0 1 RaftServer{raft-partition-partition-1} - Commit index is 405346787. RaftServer is ready
2024-06-11 19:04:27.133 zeebe-0 1 Aborted installation of partition 1, cause: Expected that current term '1' is same as raft term '2', but was not. Failing installation of 'LogStoragePartitionStep' on partition 1.
2024-06-11 19:04:27.130 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 2
2024-06-11 19:04:27.241 zeebe-0 1 Transition to FOLLOWER on term 2 starting
2024-06-11 19:04:27.325 zeebe-0 1 Recovering state from available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/405335697-888-405940943-405940970, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/405335697-888-405940943-405940970.checksum, checksum=1119397924, snapshotId=FileBasedSnapshotId{index=405335697, term=888, processedPosition=405940943, exporterPosition=405940970}, metadata=FileBasedSnapshotMetadata[version=1, processedPosition=405940943, exportedPosition=405940970, lastFollowupEventPosition=405940970]}
2024-06-11 19:04:27.751 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:27.825 zeebe-0 1 RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role
2024-06-11 19:04:28.138 zeebe-0 1 Transition to INACTIVE on term 1 completed
2024-06-11 19:04:32.895 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 1 since 5074ms
2024-06-11 19:04:37.972 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=4, candidate=2, lastLogIndex=405346788, lastLogTerm=3}: candidate's log is up-to-date
2024-06-11 19:04:37.979 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:38.037 zeebe-0 1 RaftServer{raft-partition-partition-1} - An uncaught exception occurred, transition to inactive role
```
## Zeebe-1
```
2024-06-11 19:04:02.327 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 0
2024-06-11 19:04:02.330 zeebe-1 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 0. RaftServer is ready only after it has committed events upto this index
2024-06-11 19:04:07.339 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 0 since 5000ms
2024-06-11 19:04:12.166 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:12.167 zeebe-1 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 0. RaftServer is ready only after it has committed events upto this index
2024-06-11 19:04:17.663 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 2 since 5001ms
2024-06-11 19:04:27.745 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:30.453 zeebe-1 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 405346788. RaftServer is ready only after it has committed events upto this index
2024-06-11 19:04:52.109 zeebe-1 1 Partition role transitioning from null to LEADER in term 3
2024-06-11 19:04:52.112 zeebe-1 1 Aborted installation of partition 1, cause: Expected that current term '3' is same as raft term '4', but was not. Failing installation of 'LogStoragePartitionStep' on partition 1.
2024-06-11 19:04:52.113 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 2
2024-06-11 19:04:52.119 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:06:52.505 zeebe-1 1 Snapshot is older than the latest snapshot FileBasedSnapshotId{index=405335697, term=888, processedPosition=405940943, exporterPosition=405940970}. Snapshot FileBasedSnapshotId{index=405363729, term=4, processedPosition=405968984, exporterPosition=405968972} won't be committed.
```
## Zeebe-2
```
2024-06-11 19:04:04.572 zeebe-2 1 RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
2024-06-11 19:04:12.074 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from a known leader since 7507ms
2024-06-11 19:04:12.162 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:12.666 zeebe-2 1 RaftServer{raft-partition-partition-1} - Setting firstCommitIndex to 405346787. RaftServer is ready only after it has committed events upto this index
2024-06-11 19:04:30.387 zeebe-2 1 Transition to LEADER on term 2 requested.
2024-06-11 19:04:30.394 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 1
2024-06-11 19:04:30.443 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:37.951 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - No heartbeat from 1 since 7500ms
```

**Comment by lenaschoenburg** [comment]
So let's look at the timeline.
![image](https://github.com/camunda/camunda/assets/1379753/f615a999-faa0-4139-a543-4481ae575a49)

```
2024-06-11 19:04:02.321 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 0
2024-06-11 19:04:02.327 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 0
2024-06-11 19:04:12.162 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:12.166 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:27.140 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:27.745 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:27.751 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:30.443 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 1
2024-06-11 19:04:37.976 zeebe-2 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:37.979 zeebe-0 1 RaftServer{raft-partition-partition-1} - Found leader 2
2024-06-11 19:04:52.119 zeebe-1 1 RaftServer{raft-partition-partition-1} - Found leader 2
```

**Comment by lenaschoenburg** [comment]
We could look at a sub-problem here: Why did the following occur?

```
2024-06-11 19:04:02.133 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=0, candidate=0, lastLogIndex=405346786, lastLogTerm=888}: candidate's log is up-to-date
```

Here we see that zeebe-0 uses term 0 even though the last term of the last log entry is 888!
In `ActiveRole#onPoll` we call `updateTermAndLeader` with `leader=null`. We don't check the result. Because the provided term 0 cannot be larger than the local term, we don't update the term and leader and don't reset cluster configuration. The poll is then accepted which means that either the `lastLogTerm` is higher than what we have locally or because the `lastLogTerm` is the same but `lastLogIndex` is higher.

**Comment by lenaschoenburg** [comment]
Just looking at the votes:
```
2024-06-11 18:54:00.304 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=889, candidate=0, lastLogIndex=405349345, lastLogTerm=888}: candidate's log is up-to-date
2024-06-11 18:54:00.474 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=889, candidate=0, lastLogIndex=405349345, lastLogTerm=888}: candidate's log is up-to-date
2024-06-11 18:54:05.598 zeebe-2 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=890, candidate=1, lastLogIndex=405349346, lastLogTerm=889}: candidate's log is up-to-date
2024-06-11 18:54:23.865 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=890, candidate=1, lastLogIndex=405349346, lastLogTerm=889}: candidate's log is up-to-date
2024-06-11 19:04:02.232 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=1, candidate=0, lastLogIndex=405346786, lastLogTerm=888}: candidate's log is up-to-date
2024-06-11 19:04:12.153 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=2, candidate=2, lastLogIndex=405346786, lastLogTerm=888}: candidate's log is up-to-date
2024-06-11 19:04:27.134 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=2, candidate=2, lastLogIndex=405346786, lastLogTerm=888}: candidate's log is up-to-date
2024-06-11 19:04:27.739 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=3, candidate=1, lastLogIndex=405346787, lastLogTerm=2}: candidate's log is up-to-date
2024-06-11 19:04:37.972 zeebe-0 1 RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Accepted VoteRequest{term=4, candidate=2, lastLogIndex=405346788, lastLogTerm=3}: candidate's log is up-to-date
2024-06-11 19:04:52.117 zeebe-1 1 RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=4, candidate=2, lastLogIndex=405346788, lastLogTerm=3}: candidate's log is up-to-date
```

It seems that log entries were lost between 18:54:23 and 19:04:02. The `lastLogTerm` and `lastLogIndex` decreases.

**Comment by lenaschoenburg** [comment]
Not a new bug, just a symptom of https://github.com/camunda/camunda/issues/14509 :relieved:
