### ISSUE TITLE
ScaleDownBrokersTest: shouldScaleDownCluster and shouldScaleDownClusterAgain flaky in the same run.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19435]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? - once so far.
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

```
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownCluster -- Time elapsed: 30.72 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Process instances are created in all partitions' didn't complete within 20 seconds because condition with Lambda expression in io.camunda.zeebe.it.clustering.dynamic.Utils was not fulfilled.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at io.camunda.zeebe.it.clustering.dynamic.Utils.createInstanceWithAJobOnAllPartitions(Utils.java:109)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownCluster(ScaleDownBrokersTest.java:73)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

```
Error:  io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownClusterAgain -- Time elapsed: 29.75 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Process instances are created in all partitions' didn't complete within 20 seconds because condition with Lambda expression in io.camunda.zeebe.it.clustering.dynamic.Utils was not fulfilled.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
	at io.camunda.zeebe.it.clustering.dynamic.Utils.createInstanceWithAJobOnAllPartitions(Utils.java:109)
	at io.camunda.zeebe.it.clustering.dynamic.ScaleDownBrokersTest.shouldScaleDownClusterAgain(ScaleDownBrokersTest.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

[IT QA Integration Test results (1).zip](https://github.com/user-attachments/files/15866604/IT.QA.Integration.Test.results.1.zip)

**Comment by deepthidevaki** [comment]
Should be fixed by https://github.com/camunda/camunda/pull/19466
