### ISSUE TITLE
Flaky ConcurrentTimerEventTest actor is closed before completion.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19633]
**Summary**

Likely relates to https://github.com/camunda/camunda/issues/19604

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:    Run 1: ConcurrentTimerEventTest.setup:47 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.timer.ConcurrentTimerEventTest.shouldRejectTriggerCommandIfTimerIsCanceled
Error:    Run 1: ConcurrentTimerEventTest.shouldRejectTriggerCommandIfTimerIsCanceled:62 ? Execution Actor is closed
[INFO]   Run 2: PASS</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

https://github.com/camunda/camunda/actions/runs/9602398800/job/26483174114

[Uploading Unit Test Results.zip…]()

**Comment by mustafadagher** [comment]
This is the log of the thrown error
```
Error:  io.camunda.zeebe.engine.processing.timer.ConcurrentTimerEventTest.shouldRejectTriggerCommandIfTimerIsCanceled -- Time elapsed: 0.272 s <<< ERROR!
java.util.concurrent.ExecutionException: Actor is closed
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:147)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:114)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:203)
	at io.camunda.zeebe.logstreams.util.SyncLogStream.newLogStreamWriter(SyncLogStream.java:77)
	at io.camunda.zeebe.engine.util.TestStreams$LogContext.newLogStreamWriter(TestStreams.java:442)
	at io.camunda.zeebe.engine.util.TestStreams.newLogStreamWriter(TestStreams.java:171)
	at io.camunda.zeebe.engine.util.StreamProcessingComposite.writeBatch(StreamProcessingComposite.java:145)
	at io.camunda.zeebe.engine.util.StreamProcessorRule.writeBatch(StreamProcessorRule.java:194)
	at io.camunda.zeebe.engine.util.EngineRule.writeRecords(EngineRule.java:356)
	at io.camunda.zeebe.engine.processing.timer.ConcurrentTimerEventTest.shouldRejectTriggerCommandIfTimerIsCanceled(ConcurrentTimerEventTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:159)
	... 8 more
```

I'm hoping this might have been fixed with https://github.com/camunda/camunda/pull/20339
