### ISSUE TITLE
Expected to find same MemberState at same version.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19646]
**Describe the bug**

This issue is potentially related to https://github.com/camunda/camunda/issues/14509 

Hard to have further context on this issue other than the logged error, due to the high frequency of this error message and the fact that this cluster had already been deleted when we started investigating, so we did not have other metrics to go by.

The only other useful logs is the constant failure to probe member 2.

```
java.lang.IllegalStateException: Expected to find same MemberState at same version, but found MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={elasticsearch=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty], MetricsExporter=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty]}]]], 2=PartitionState[state=ACTIVE, priority=3, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={elasticsearch=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty], MetricsExporter=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty]}]]], 3=PartitionState[state=ACTIVE, priority=1, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={elasticsearch=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty], MetricsExporter=ExporterState[metadataVersion=0, state=ENABLED, initializedFrom=Optional.empty]}]]]}] and MemberState[version=0, lastUpdated=-1000000000-01-01T00:00:00Z, state=ACTIVE, partitions={1=PartitionState[state=ACTIVE, priority=2, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={}]]], 2=PartitionState[state=ACTIVE, priority=3, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={}]]], 3=PartitionState[state=ACTIVE, priority=1, config=DynamicPartitionConfig[exporting=ExportersConfig[exporters={}]]]}]
	at io.camunda.zeebe.dynamic.config.state.MemberState.merge(MemberState.java:123) ~[zeebe-cluster-config-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.HashMap.merge(Unknown Source) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source) ~[?:?]
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.camunda.zeebe.dynamic.config.state.ClusterConfiguration.merge(ClusterConfiguration.java:144) ~[zeebe-cluster-config-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.dynamic.config.ClusterConfigurationManagerImpl.lambda$onGossipReceived$5(ClusterConfigurationManagerImpl.java:191) ~[zeebe-cluster-config-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]

```

**To Reproduce**

Unclear.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

https://console.cloud.google.com/errors/detail/CJqB_vSnpqis4wE;service=zeebe;time=P7D?project=camunda-saas-dev

[Logs 20240621 172018.json](https://github.com/user-attachments/files/15929501/Logs.20240621.172018.json)

**Environment:**
- OS: 
- Zeebe Version: 8.6.0-SNAPSHOT
- Configuration: "G3_S_HA"

**Comment by korthout** [comment]
@rodrigo-lourenco-lopes Is ZPA expected to do something for this? It seems like a ZDP issue to me

**Comment by deepthidevaki** [comment]
In this cluster, one broker rolled back to an older version.

```
DEBUG 2024-06-17T13:03:25.006371552Z [jsonPayload.context."actor-scheduler": Broker-2] [labels."k8s-pod.cloudCamundaIo.generation": Console_Test_Suite] Current exporter state {elasticsearch={position=8063963, metadata={"recordCountersByValueType":{"JOB":11,"DEPLOYMENT":4,"PROCESS_INSTANCE":18,"INCIDENT":2,"PROCESS_INSTANCE_CREATION":2,"PROCESS":1,"COMMAND_DISTRIBUTION":24}}}, MetricsExporter={position=8063963, metadata=}}
DEBUG 2024-06-17T13:04:26.531700278Z [jsonPayload.context."actor-scheduler": Broker-2] [labels."k8s-pod.cloudCamundaIo.generation": Console_Test_Suite] Current exporter state {elasticsearch={position=8064201, metadata={"recordCountersByValueType":{"JOB":11,"DEPLOYMENT":4,"PROCESS_INSTANCE":18,"INCIDENT":2,"PROCESS_INSTANCE_CREATION":2,"PROCESS":1,"COMMAND_DISTRIBUTION":24}}}, MetricsExporter={position=8064201, metadata=}}
DEBUG 2024-06-17T13:05:08.273670788Z [jsonPayload.context."actor-scheduler": Broker-2] [labels."k8s-pod.cloudCamundaIo.generation": Camunda_8_5_gen1] Shutdown was called with context: BrokerStartupContextImpl{broker=2}
INFO 2024-06-17T13:05:08.274194201Z [jsonPayload.context."actor-scheduler": Broker-2] [labels."k8s-pod.cloudCamundaIo.generation": Camunda_8_5_gen1] Shutdown Broker Admin Interface
INFO 2024-06-17T13:05:08.279376665Z [jsonPayload.context."actor-scheduler": Broker-2] [labels."k8s-pod.cloudCamundaIo.generation": Camunda_8_5_gen1] Shutdown Partition Manager
```

`Console_Test_Suite` is using either an alpha version on the snaphsot. It contains some of the changes to ClusterTopology introduced in #16126. Broker-2 was rolled back to 8.5. The other brokers are still in the snapshot version. This causes the inconsistency exception, because the Broker-2 in old version do not contain the new fields that are available in Broker-1 and Broker-0 (as evident from the logs). 

This is not a bug. This is an unexpected scenario where we do not support a roll back to an older version.
