### ISSUE TITLE
Clear scroll request fails on Opensearch on AWS

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#19869]
### Describe the bug

Users report that when running Operate on Opensearch on AWS, max scroll contexts are being exhausted at some point. Logs show error in clearing scroll context (log is not very informative unfortunately):

```
2024-06-11 10:43:59.021  WARN 7 --- [   postimport_1] i.c.o.s.o.c.s.RichOpenSearchClient       : Error occurred when clearing the scroll with id [FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoDRZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVAWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVEWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVIWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVMWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVQWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVUWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVYWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVcWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVkWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVgWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVoWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVsWR1dET0drTmNUNW1iRHFyamF0cERZdxZEaXphaVJnQlFNeThSWTBjNDFKM1NRAAAAAAF2qVwWR1dET0drTmNUNW1iRHFyamF0cERZdw==]
2024-06-11 10:43:59.021 ERROR 7 --- [   postimport_1] i.c.o.s.o.c.s.RichOpenSearchClient       : Failed to search index: [operate-list-view-8.3.0_alias]! Reason: Shards failed executing request (request=org.opensearch.client.opensearch.core.SearchRequest@540864b0, failed shards=[org.opensearch.client.opensearch._types.ShardFailure@3f7acf64, org.opensearch.client.opensearch._types.ShardFailure@29566ca0, org.opensearch.client.opensearch._types.ShardFailure@9dedfd8, org.opensearch.client.opensearch._types.ShardFailure@1ee407b7, org.opensearch.client.opensearch._types.ShardFailure@770cfae0, org.opensearch.client.opensearch._types.ShardFailure@6d25abcd, org.opensearch.client.opensearch._types.ShardFailure@127a99ae, org.opensearch.client.opensearch._types.ShardFailure@2c1dfde9, org.opensearch.client.opensearch._types.ShardFailure@3cd6c970, org.opensearch.client.opensearch._types.ShardFailure@7ced66e4, org.opensearch.client.opensearch._types.ShardFailure@3a9c273e, org.opensearch.client.opensearch._types.ShardFailure@792d6731, org.opensearch.client.opensearch._types.ShardFailure@73babc2d, org.opensearch.client.opensearch._types.ShardFailure@64f72ef8, org.opensearch.client.opensearch._types.ShardFailure@3f89408f, org.opensearch.client.opensearch._types.ShardFailure@2d8fbca0])

io.camunda.operate.store.opensearch.client.OpenSearchFailedShardsException: Shards failed executing request (request=org.opensearch.client.opensearch.core.SearchRequest@540864b0, failed shards=[org.opensearch.client.opensearch._types.ShardFailure@3f7acf64, org.opensearch.client.opensearch._types.ShardFailure@29566ca0, org.opensearch.client.opensearch._types.ShardFailure@9dedfd8, org.opensearch.client.opensearch._types.ShardFailure@1ee407b7, org.opensearch.client.opensearch._types.ShardFailure@770cfae0, org.opensearch.client.opensearch._types.ShardFailure@6d25abcd, org.opensearch.client.opensearch._types.ShardFailure@127a99ae, org.opensearch.client.opensearch._types.ShardFailure@2c1dfde9, org.opensearch.client.opensearch._types.ShardFailure@3cd6c970, org.opensearch.client.opensearch._types.ShardFailure@7ced66e4, org.opensearch.client.opensearch._types.ShardFailure@3a9c273e, org.opensearch.client.opensearch._types.ShardFailure@792d6731, org.opensearch.client.opensearch._types.ShardFailure@73babc2d, org.opensearch.client.opensearch._types.ShardFailure@64f72ef8, org.opensearch.client.opensearch._types.ShardFailure@3f89408f, org.opensearch.client.opensearch._types.ShardFailure@2d8fbca0])
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.checkFailedShards(OpenSearchDocumentOperations.java:96) ~[operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.scrollWith(OpenSearchDocumentOperations.java:136) ~[operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.unsafeScrollWith(OpenSearchDocumentOperations.java:113) ~[operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.lambda$safeScrollWith$2(OpenSearchDocumentOperations.java:169) ~[operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.OpenSearchOperation.safe(OpenSearchOperation.java:48) [operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.safeScrollWith(OpenSearchDocumentOperations.java:167) [operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.safeScrollWith(OpenSearchDocumentOperations.java:159) [operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.scrollWith(OpenSearchDocumentOperations.java:203) [operate-schema-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.post.opensearch.OpensearchIncidentPostImportAction.queryData(OpensearchIncidentPostImportAction.java:560) [operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.post.opensearch.OpensearchIncidentPostImportAction.searchForInstances(OpensearchIncidentPostImportAction.java:195) [operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.post.AbstractIncidentPostImportAction.processPendingIncidents(AbstractIncidentPostImportAction.java:123) [operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.post.AbstractIncidentPostImportAction.performOneRound(AbstractIncidentPostImportAction.java:61) [operate-importer-8.5.0.jar!/:8.5.0]
	at io.camunda.operate.zeebeimport.post.AbstractIncidentPostImportAction.run(AbstractIncidentPostImportAction.java:75) [operate-importer-8.5.0.jar!/:8.5.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-6.1.5.jar!/:6.1.5]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
``` 

### To Reproduce

1. Run Operate for some time.
2. Check amount of open scroll contexts ( `GET /_nodes/stats/indices/search`, field `scroll_current`).

### Actual behavior

Amount of open scroll contexts grow with the time till reaches the configured maximum.

### Expected behavior

* Amount of open scroll contexts should not be too high (depends on system load)
* Scroll contexts are closed correctly with Opensearch
* If clearing fails, the root cause exception is logged (compare https://github.com/camunda/camunda/blob/aca0eacff3e7dc254706d2945a2af6a0f64bc0fd/operate/schema/src/main/java/io/camunda/operate/store/opensearch/client/sync/OpenSearchDocumentOperations.java#L79)

### Environment

- Operate Version: all Operate versions supporting Opensearch

### Additional context

* Forum post https://forum.camunda.io/t/operate-exeeds-search-max-open-scroll-context-on-aws-using-opensearch/53053
* Related Opensearch issue: https://github.com/opensearch-project/opensearch-java/issues/712
* Similar Tasklist issue (resolved): https://github.com/camunda/tasklist/issues/3939
* https://jira.camunda.com/browse/SUPPORT-22693
  * via https://camunda.slack.com/archives/C07BWNTKRNV/p1720622354128929?thread_ts=1720534070.495119&cid=C07BWNTKRNV

---------------------------------------------------------------------------------------------

### Acceptance Criteria

* Fixed on
  * main
  * 8.5
  * 8.4

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by ThorbenLindhauer** [comment]
Not prioritizing for now due to capacity and other commitments. Moving to backlog.

**Comment by ThorbenLindhauer** [comment]
Note, we plan to revert this fix due to https://github.com/camunda/camunda/issues/24262 and then address the problem here via https://github.com/camunda/camunda/issues/24321
