### ISSUE TITLE
ProcessInstanceMigrationClusteredTest.shouldRejectMigrationWhenMessageSubscriptionMigrationIsNotDistributed is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#19861]
**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  io.camunda.zeebe.it.clustering.ProcessInstanceMigrationClusteredTest.shouldRejectMigrationWhenMessageSubscriptionMigrationIsNotDistributed -- Time elapsed: 10.83 s <<< FAILURE!
java.lang.AssertionError: 

Expecting Optional to contain a value but it was empty.
	at io.camunda.zeebe.it.clustering.ProcessInstanceMigrationClusteredTest.shouldRejectMigrationWhenMessageSubscriptionMigrationIsNotDistributed(ProcessInstanceMigrationClusteredTest.java:112)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

[Test results for [IT] Zeebe QA - Integration Tests.zip](https://github.com/user-attachments/files/16026182/Test.results.for.IT.Zeebe.QA.-.Integration.Tests.zip)

**Comment by Zelldon** [comment]
Blocks merging PRs like https://github.com/camunda/camunda/pull/19623
