### ISSUE TITLE
RandomizedRaftTest.livenessTestWithSnapshot is unstable

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#19862]
**Summary**

This tests seems unstable, it is not labeled as flaky by the plugin but I saw different failures in our CI

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  io.atomix.raft.RandomizedRaftTest.livenessTestWithSnapshot -- Time elapsed: 6.309 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at io.atomix.raft.ControllableRaftContexts.assertAllMembersAreReady(ControllableRaftContexts.java:622)
	at io.atomix.raft.RandomizedRaftTest.livenessTest(RandomizedRaftTest.java:232)
	at io.atomix.raft.RandomizedRaftTest.livenessTestWithSnapshot(RandomizedRaftTest.java:165)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createRawFunction$1(CheckedPropertyFactory.java:84)
	at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createRawFunction$2(CheckedPropertyFactory.java:91)
	at net.jqwik.engine.properties.CheckedFunction.execute(CheckedFunction.java:17)
	at net.jqwik.api.lifecycle.AroundTryHook.lambda$static$0(AroundTryHook.java:57)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$2(HookSupport.java:48)
	at net.jqwik.engine.hooks.lifecycle.TryLifecycleMethodsHook.aroundTry(TryLifecycleMethodsHook.java:56)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$3(HookSupport.java:53)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$2(HookSupport.java:48)
	at net.jqwik.engine.hooks.lifecycle.BeforeTryMembersHook.aroundTry(BeforeTryMembersHook.java:69)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$3(HookSupport.java:53)
	at net.jqwik.engine.execution.CheckedPropertyFactory.lambda$createTryExecutor$0(CheckedPropertyFactory.java:60)
	at net.jqwik.engine.execution.lifecycle.AroundTryLifecycle.execute(AroundTryLifecycle.java:23)
	at net.jqwik.engine.properties.GenericProperty.testPredicate(GenericProperty.java:166)
	at net.jqwik.engine.properties.GenericProperty.check(GenericProperty.java:68)
	at net.jqwik.engine.execution.CheckedProperty.check(CheckedProperty.java:67)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeProperty(PropertyMethodExecutor.java:90)
	at net.jqwik.engine.execution.PropertyMethodExecutor.executeMethod(PropertyMethodExecutor.java:69)
	at net.jqwik.engine.execution.PropertyMethodExecutor.lambda$execute$0(PropertyMethodExecutor.java:49)
	at net.jqwik.api.lifecycle.AroundPropertyHook.lambda$static$0(AroundPropertyHook.java:46)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.api.lifecycle.PropertyExecutor.executeAndFinally(PropertyExecutor.java:39)
	at net.jqwik.engine.hooks.lifecycle.PropertyLifecycleMethodsHook.aroundProperty(PropertyLifecycleMethodsHook.java:56)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.statistics.StatisticsHook.aroundProperty(StatisticsHook.java:37)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$0(HookSupport.java:26)
	at net.jqwik.engine.hooks.lifecycle.AutoCloseableHook.aroundProperty(AutoCloseableHook.java:13)
	at net.jqwik.engine.execution.lifecycle.HookSupport.lambda$wrap$1(HookSupport.java:31)
	at net.jqwik.engine.execution.PropertyMethodExecutor.execute(PropertyMethodExecutor.java:47)
	at net.jqwik.engine.execution.PropertyTaskCreator.executeTestMethod(PropertyTaskCreator.java:166)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$1(PropertyTaskCreator.java:51)
	at net.jqwik.engine.execution.lifecycle.CurrentDomainContext.runWithContext(CurrentDomainContext.java:28)
	at net.jqwik.engine.execution.PropertyTaskCreator.lambda$createTask$2(PropertyTaskCreator.java:50)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.lambda$execute$0(ExecutionTask.java:31)
	at net.jqwik.engine.execution.lifecycle.CurrentTestDescriptor.runWithDescriptor(CurrentTestDescriptor.java:17)
	at net.jqwik.engine.execution.pipeline.ExecutionTask$1.execute(ExecutionTask.java:31)
	at net.jqwik.engine.execution.pipeline.ExecutionPipeline.runToTermination(ExecutionPipeline.java:82)
	at net.jqwik.engine.execution.JqwikExecutor.execute(JqwikExecutor.java:46)
	at net.jqwik.engine.JqwikTestEngine.executeTests(JqwikTestEngine.java:70)
	at net.jqwik.engine.JqwikTestEngine.execute(JqwikTestEngine.java:53)
</pre>
</details>

[Test results for Property Tests.zip](https://github.com/user-attachments/files/16026232/Test.results.for.Property.Tests.zip)

**Comment by EuroLew** [comment]
When aborting snapshots the `previousReceivedSnapshotChunkId` was not set to null, this could cause cases where certain install requests would be skipped assuming they had already been processed when they hadn't as it was a new snapshot from a new broker.

Say for example received chunk-0, previously received is now chunk 0. receive chunk-1 something goes wrong and we `abortSnapshot` previously received is now still chunk-0 so when a different broker sends the snapshot with chunk-0 it skips over it with an `OK` and this fails the snapshot.

https://github.com/camunda/camunda/pull/19959

**Comment by mustafadagher** [comment]
Re-opening, happened again [here](https://github.com/camunda/camunda/actions/runs/9793186595/job/27040608351)

 [Logs](https://drive.google.com/file/d/1LzZ6ZPDYShhPmwtpERWKHtmvSOD7X2oW/view?usp=sharing)

**Comment by deepthidevaki** [comment]
@EuroLew Do you want to look into this? Or should I?

**Comment by EuroLew** [comment]
> 

I've looked into it and not even sure what's going wrong if you could take it that would be great.

**Comment by deepthidevaki** [comment]
Leader 2 sends snapshot `1-5` to follower 0. Snapshot has more than one chunk. Follower 0 starts new snapshot.
```
11:05:07.680 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=9, leader=2, index=1, term=5, version=1, chunkId=chunk-0, nextChunkId=chunk-1, data=HeapByteBuffer{position=0, remaining=72, limit=72, capacity=72, mark=java.nio.HeapByteBuffer[pos=0 lim=72 cap=72], hash=-675584945}, initial=true, complete=false}
11:05:07.680 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received snapshot 1 chunk from 2
11:05:07.680 [raft-server-1] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Started receiving new snapshot InMemorySnapshot{index=1, term=5, id='1-5', checksum=0} from 2
11:05:07.680 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Sending InstallResponse{status=OK, error=null, preferredChunkSize=0}
```
Leader resends the snapshot because the previous request timedout. 
```
11:05:07.682 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=9, leader=2, index=1, term=5, version=1, chunkId=chunk-0, nextChunkId=chunk-1, data=HeapByteBuffer{position=0, remaining=72, limit=72, capacity=72, mark=java.nio.HeapByteBuffer[pos=0 lim=72 cap=72], hash=-675584945}, initial=true, complete=false}
11:05:07.682 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received snapshot 1 chunk from 2
11:05:07.682 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Sending InstallResponse{status=OK, error=null, preferredChunkSize=0}
11:05:07.682 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=9, leader=2, index=1, term=5, version=1, chunkId=chunk-0, nextChunkId=chunk-1, data=HeapByteBuffer{position=0, remaining=72, limit=72, capacity=72, mark=java.nio.HeapByteBuffer[pos=0 lim=72 cap=72], hash=-675584945}, initial=true, complete=false}
11:05:07.682 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received snapshot 1 chunk from 2
11:05:07.682 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Sending InstallResponse{status=OK, error=null, preferredChunkSize=0}
```

After some time Leader 2 sends a new snapshot with only one chunk. Follower accepts the requests, but assumes this is a duplicate request because the chunk-id matches. So it does not process the request and do not commit the snapshot. 
```
11:05:07.786 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received InstallRequest{currentTerm=18, leader=2, index=1, term=5, version=1, chunkId=chunk-0, nextChunkId=null, data=HeapByteBuffer{position=0, remaining=72, limit=72, capacity=72, mark=java.nio.HeapByteBuffer[pos=0 lim=72 cap=72], hash=1579207241}, initial=true, complete=true}
11:05:07.786 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received snapshot 1 chunk from 2
11:05:07.786 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Sending InstallResponse{status=OK, error=null, preferredChunkSize=0}
```

Leader assumes the follower has committed the snapshot, and then sends the next AppendRequest. The follower rejects it.
```
11:05:07.787 [raft-server-1] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2-partition-1} - Received InstallResponse{status=OK, error=null, preferredChunkSize=0} from 0
11:05:07.787 [raft-server-1] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2-partition-1} - Reset next index for RaftMemberContext{member=0, term=18, configIndex=0, snapshotIndex=1, nextSnapshotIndex=0, nextSnapshotChunk=null, matchIndex=0, heartbeatTime=1720091107784, appending=0, appendSucceeded=false, appendTime=1720091107784, configuring=false, installing=false, failures=0} to 2
11:05:07.787 [raft-server-1] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{2-partition-1} - Sending VersionedAppendRequest{version=2, term=18, leader=2, prevLogIndex=1, prevLogTerm=5, entries=2, commitIndex=3} to 0


11:05:07.787 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received InternalAppendRequest[term=18, leader=2, prevLogIndex=1, prevLogTerm=5, commitIndex=3, entries=[ReplicatableJournalRecord{term=9, index=2, checksum=3593661314, serializedJournalRecord=[16, 0, 2, 0, 7, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, 17, 0, 0, 0, 9, 0, 1, 0, 8, 0, 3, 0, 9, 0, 0, 0, 0, 0, 0, 0, 2]}, ReplicatableJournalRecord{term=18, index=3, checksum=4253087553, serializedJournalRecord=[16, 0, 2, 0, 7, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, 17, 0, 0, 0, 9, 0, 1, 0, 8, 0, 3, 0, 18, 0, 0, 0, 0, 0, 0, 0, 2]}]]
11:05:07.787 [raft-server-1] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Rejected InternalAppendRequest[term=18, leader=2, prevLogIndex=1, prevLogTerm=5, commitIndex=3, entries=[ReplicatableJournalRecord{term=9, index=2, checksum=3593661314, serializedJournalRecord=[16, 0, 2, 0, 7, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, 17, 0, 0, 0, 9, 0, 1, 0, 8, 0, 3, 0, 9, 0, 0, 0, 0, 0, 0, 0, 2]}, ReplicatableJournalRecord{term=18, index=3, checksum=4253087553, serializedJournalRecord=[16, 0, 2, 0, 7, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, 17, 0, 0, 0, 9, 0, 1, 0, 8, 0, 3, 0, 18, 0, 0, 0, 0, 0, 0, 0, 2]}]]: Previous index (1) is greater than the local log's last index (0)
11:05:07.787 [raft-server-1] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Sending AppendResponse{status=OK, term=18, succeeded=false, lastLogIndex=0, lastSnapshotIndex=0, configurationIndex=0}
```

Leader will then send the snapshot again, and it repeats. The follower can never complete the snapshot replication and receive events.

There are two problems here
1. The follower assumes it is a duplicate request when seeing the same chunk id. This is incorrect because two different snapshots can have the same chunk id.
2. The snapshotId was same for different snapshot. This is most likely a test setup issue. In production, we ensure that each snapshot gets unique id.
