### ISSUE TITLE
Operate backup/restore test fails

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#19881]
### Description

The backup/restore nightly test for Operate started failing on June 28:

https://github.com/camunda/camunda/actions/runs/9707694834

The test runs by downloading the latest Operate snapshot image and starting in a test container, then seeding data and running backup/restore. 

There is currently a known issue with Operate and Tasklist causing startup failures due to changes with identity that are currently being researched. 

[ERROR] io.camunda.operate.qa.backup.BackupRestoreTest.testBackupRestore -- Time elapsed: 162.1 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image camunda/operate:SNAPSHOT
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at io.camunda.operate.qa.util.TestContainerUtil.startOperateContainer(TestContainerUtil.java:382)
	at io.camunda.operate.qa.backup.BackupRestoreTest.startOperate(BackupRestoreTest.java:165)
	at io.camunda.operate.qa.backup.BackupRestoreTest.startAllApps(BackupRestoreTest.java:160)
	at io.camunda.operate.qa.backup.BackupRestoreTest.testBackupRestore(BackupRestoreTest.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

Once this is fixed, and a working snapshot is built, this will be re-run to determine if there are other issues remaining.

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
This has resolved, recent runs on main are successful.
