### ISSUE TITLE
Flaky shouldRecoverAfterOutOfDiskSpaceAfterExporting: io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#20003]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure? No

**Failures**

```
Condition with alias 'until the disk is not full anymore' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest 
Expecting code not to raise a throwable but caught
  "io.camunda.zeebe.client.api.command.ClientStatusException: Cannot accept requests for partition 1. Broker is out of disk space
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT.publishMessage(DiskSpaceRecoveryIT.java:85)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
	at org.assertj.core.api.NotThrownAssert.isThrownBy(NotThrownAssert.java:43)
	at io.camunda.zeebe.it.health.DiskSpaceRecoveryIT$WithStandardContainerTest.lambda$shouldRecoverAfterOutOfDiskSpaceAfterExporting$1(DiskSpaceRecoveryIT.java:137)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 11 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Cannot accept requests for partition 1. Broker is out of disk space
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
```

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**
[Test results for [IT] QA Integration Tests (2).zip](https://github.com/user-attachments/files/16085174/Test.results.for.IT.QA.Integration.Tests.2.zip)

https://github.com/camunda/camunda/actions/runs/9777819367/job/26993299289?pr=19791
Branch - `release-8.5.4`

**Comment by deepthidevaki** [comment]
Should be fixed by https://github.com/camunda-community-hub/zeebe-test-container/pull/722

**Comment by npepinpe** [comment]
Fixed and merged :)
