### ISSUE TITLE
Big decision evaluation failures can't be indexed

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#20255]
### Describe the bug

* Fix on all maintained versions (also applies to 8.8 with new exporter)

When decision evaluation failure is very big, importer is blocked and following error is logged:
```
INDEX failed for type [operate-decision-instance-8.3.0_] and id [2251800354130069-1]: ElasticsearchException[Elasticsearch exception [type=document_parsing_exception, reason=[1:171] failed to parse field [evaluationFailure] of type [keyword] in document with id '2251800354130069-1'. Preview of field's value: <..>
: java.lang.NumberFormatException: Character , is neither a decimal digit number, decimal point, nor "e" notation exponential mark.']
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:519) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:430) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.action.bulk.BulkItemResponse.fromXContent(BulkItemResponse.java:128) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.action.bulk.BulkResponse.fromXContent(BulkResponse.java:184) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$8(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2188) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:620) ~[elasticsearch-rest-high-level-client-7.17.16.jar!/:7.17.16]
	at io.camunda.operate.util.ElasticsearchUtil.processLimitedBulkRequest(ElasticsearchUtil.java:336) ~[operate-els-schema-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.util.ElasticsearchUtil.processBulkRequest(ElasticsearchUtil.java:291) ~[operate-els-schema-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.util.ElasticsearchUtil.processBulkRequest(ElasticsearchUtil.java:284) ~[operate-els-schema-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.store.elasticsearch.ElasticsearchBatchRequest.execute(ElasticsearchBatchRequest.java:169) ~[operate-els-schema-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.lambda$performImport$1(AbstractImportBatchProcessor.java:38) ~[operate-importer-common-8.3.8.jar!/:8.3.8]
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.11.6.jar!/:1.11.6]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withTimer(AbstractImportBatchProcessor.java:59) ~[operate-importer-common-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.withImportIndexQueryTimer(AbstractImportBatchProcessor.java:52) ~[operate-importer-common-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.AbstractImportBatchProcessor.performImport(AbstractImportBatchProcessor.java:37) ~[operate-importer-common-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.ImportJob.processOneIndexBatch(ImportJob.java:143) ~[operate-importer-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:84) ~[operate-importer-8.3.8.jar!/:8.3.8]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.lambda$executeJob$5(ElasticsearchRecordsReader.java:465) ~[operate-importer-8.3.8.jar!/:8.3.8]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=illegal_argument_exception, reason=Document contains at least one immense term in field="evaluationFailure" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[69, 120, 112, 101, 99, 116, 101, 100, 32, 116, 111, 32, 101, 118, 97, 108, 117, 97, 116, 101, 32, 100, 101, 99, 105, 115, 105, 111, 110, 32]...']
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:519) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:430) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:460) ~[elasticsearch-7.17.16.jar!/:7.17.16]
	... 25 more
```

### To Reproduce

* Deploy the DMN model with huge and complex evaluation expression which will fail (check incident channel for example)
* deploy the BPMN model referencing this DMN
* start process instance

### Current behavior

Decision instance can not be imported, import is blocked.

### Expected behavior

Decision import is imported and shown in UI.

### Environment

- Operate Version: detected on 8.3.8

### Additional context

* Incident: https://camunda.slack.com/archives/C07CDLFF3GD
* Depends on #20248 . Related Zeebe incident: https://camunda.slack.com/archives/C07C68Y6HNY
* One of the options is to disable indexing for this field, we already [disabled indexing for input and output values](https://github.com/camunda/operate/issues/3485)
* Another option: we can add `"ignore_above": 8191` to the field declaration, so that only exceeding values are not indexed (E[lasticsearch reference](https://www.elastic.co/docs/reference/elasticsearch/mapping-reference/ignore-above)).
* **Schema update** Since we don't allow migrating of indices any more, there are two ways to fix the issue:
  * create the new field with the new name, mark old one as deprecated and use only new field in code
  * extend our schema update possibilities, which now allow only [to add new fields](https://github.com/camunda/camunda/blob/bb01bb317d8b3d12b1d5a6e98400a84660fd8d68/operate/schema/src/main/java/io/camunda/operate/schema/IndexSchemaValidator.java#L278), but we could also consider comparing field properties, finding differences and applying schema update
  

[Link to relevant Slack discussion](https://camunda.slack.com/archives/C08GPP57D8R/p1746792175049419)

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [x] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [x] The issue has been labeled with an appropriate `Bug-area` label
- [x] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

### PRs:

main: https://github.com/camunda/camunda/pull/31870
8.7: https://github.com/camunda/camunda/pull/32433
8.6: https://github.com/camunda/camunda/pull/32469
8.5: https://github.com/camunda/camunda/pull/32468
8.4: https://github.com/camunda/operate/pull/6878

**Comment by ThorbenLindhauer** [comment]
Moving into backlog as we currently do not have capacity to work on this.

**Comment by kristinkomschow** [comment]
My plan is to fix this in Operate the same way it was done for zeebe by applying `"ignore_above": 1024` to the field, as I don't see any reason to not align this.

@camunda/data-layer are there any (new) guidelines for changes in the ES schemas? Operate currently only allows for adding new fields, so I'm wondering if you have any input on whether we should rather deprecate the old field and create a new one with the new settings, or if we should support schema updates.

**Comment by kristinkomschow** [comment]
BPMN and DMN to reproduce the error:
[large-dmn-expression-process.bpmn.txt](https://github.com/user-attachments/files/20065164/large-dmn-expression-process.bpmn.txt)
[large-expression-with-error.dmn.txt](https://github.com/user-attachments/files/20065163/large-expression-with-error.dmn.txt)

**Comment by kristinkomschow** [comment]
Impact of deprecating and creating a new field:

Importer:
Set new entity field during import instead of `evaluationFailure` in  [DecisionEvaluationZeebeRecordProcessor] (https://github.com/camunda/camunda/blob/main/operate/importer-8_7/src/main/java/io/camunda/operate/zeebeimport/v8_7/processors/processors/DecisionEvaluationZeebeRecordProcessor.java#L114)

Exporter:
Set new entity field during export instead of `evaluationFailure` in  [DecisionEvaluationZeebeRecordProcessor] (https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/DecisionEvaluationHandler.java#L114)

V1 API:
The field is used by [DecisionInstanceDaos for filtering](https://github.com/camunda/camunda/blob/main/operate/webapp/src/main/java/io/camunda/operate/webapp/api/v1/entities/DecisionInstance.java#L24) -> the filter query needs to be adjusted to accept both the deprecated and new field name and to filter across both fields to provide backwards compatibility. Since this is the public API we also need to check if we have to update documentation.

Internal API:
[DecisionInstanceDto sets the error field](https://github.com/camunda/camunda/blob/main/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/dmn/DecisionInstanceDto.java#L190) from the entity's evaluation failure field -> Should be changed to using the new field if it's not empty (and fall back to the deprecated one if it is)

V2 API:
- New field has to be added to [DecisionInstanceEntityTransformer](https://github.com/camunda/camunda/blob/main/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/entity/DecisionInstanceEntityTransformer.java#L26-L44)
- Adjust filter query to accept both fields (similar to V1 API) in [DecisionInstanceFilterTransformer](https://github.com/camunda/camunda/blob/main/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/filter/DecisionInstanceFilterTransformer.java#L56)
- Add new case for the field to [DecisionInstanceFieldSortingTransformer](https://github.com/camunda/camunda/blob/main/search/search-client-query-transformer/src/main/java/io/camunda/search/clients/transformers/sort/DecisionInstanceFieldSortingTransformer.java#L27-L42)
@camunda/c8-api-team I haven't worked with the new API yet. Is there anything I'm missing?
Do you have thoughts on adjusting the filter to search across both fields (the deprecated and new one) for backwards compatibility regardless of which of the two fields is set, or is that bad practice?
