### ISSUE TITLE
StackOverflowError during process instance modification

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20307]
**Describe the bug**

Due to a recursive call in this processor there's a chance we run into a `StackOverflowError`. It happens when there's a terminate instruction for an element with a lot of nested child elements (think a chain of call activities).
As impact, one partition dies when this happens.

A workaround for now would be to increase the stack size and rebooting the brokers, but it's not ideal.

**To Reproduce**

1. Create a process with a call activity that calls itself and let it run for a while. I used beneath process. This doesn't get caught by the `StraightThroughProcessingLoopValidator` (yet) and let it create 10k instances.
2. In the root process, try to move the token from the call activity to the user task
3. Watch the SO cause the partition to crash and burn :fire:

<img width="551" alt="image" src="https://github.com/user-attachments/assets/05fbcd58-358c-4370-9fdf-aa3816c3b812">

**Expected behavior**

All the element instances should get terminated without problem. We should try to replace the recursion with a regular iteration.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2024-07-10 10:02:41.402 [Broker-2] [zb-actors-0] [StreamProcessor-2] ERROR
      io.camunda.zeebe.util.actor - Shutting down because we can't recover from JVM errors. Consider restarting this broker if it is a temporary issue.
java.lang.StackOverflowError: null
	at io.camunda.zeebe.msgpack.spec.MsgPackWriter.writeString(MsgPackWriter.java:143) ~[zeebe-msgpack-core-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.spec.MsgPackWriter.writeString(MsgPackWriter.java:139) ~[zeebe-msgpack-core-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.StringValue.write(StringValue.java:86) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.EnumValue.write(EnumValue.java:54) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.write(BaseProperty.java:91) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:166) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.write(ObjectValue.java:92) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.msgpack.UnpackedObject.write(UnpackedObject.java:63) ~[zeebe-msgpack-value-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.copyElementInstance(DbElementInstanceState.java:404) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.getInstance(DbElementInstanceState.java:296) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.lambda$getChildren$2(DbElementInstanceState.java:310) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$10(TransactionalColumnFamily.java:202) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.visit(TransactionalColumnFamily.java:475) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$forEachInPrefix$20(TransactionalColumnFamily.java:407) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ColumnFamilyContext.withPrefixKey(ColumnFamilyContext.java:112) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:391) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.forEachInPrefix(TransactionalColumnFamily.java:361) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$whileEqualPrefix$11(TransactionalColumnFamily.java:199) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:344) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.whileEqualPrefix(TransactionalColumnFamily.java:197) ~[zeebe-db-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.getChildren(DbElementInstanceState.java:306) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:701) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:703) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:703) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
	at io.camunda.zeebe.engine.processing.processinstance.ProcessInstanceModificationModifyProcessor.terminateElement(ProcessInstanceModificationModifyProcessor.java:708) ~[zeebe-workflow-engine-8.5.0.jar:8.5.0]
...
```

</p>
</details>

**Environment:**
- Zeebe Version: All that support PI modification

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Changed the severity to high because the impact is significant and the workaround is not straightforward.
- We should aim to avoid recursive call in general. We should fix this by removing the recursive call.
