### ISSUE TITLE
Flaky `SnapshotChecksumTest.shouldFlushOnPersist`

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20344]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work? No
- Do we suspect that it is a real failure? 🤷 

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

```
Error:  io.camunda.zeebe.snapshots.impl.SnapshotChecksumTest.shouldFlushOnPersist -- Time elapsed: 0.363 s <<< ERROR!
java.lang.IllegalArgumentException: Expected line to match format of 'PID fsync(FD<PATH>) = RESULT', but '7076  fsync(135</tmp/junit14308501529630370864/checksum> <unfinished ...>' does not match
	at io.camunda.zeebe.test.util.STracer$FSyncTrace.of(STracer.java:148)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.Spliterators$1Adapter.forEachRemaining(Spliterators.java:706)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.assertj.core.util.Lists.newArrayList(Lists.java:78)
	at org.assertj.core.api.ListAssert$ListFromStream.initList(ListAssert.java:246)
	at org.assertj.core.api.ListAssert$ListFromStream.size(ListAssert.java:254)
	at org.assertj.core.util.IterableUtil.sizeOf(IterableUtil.java:50)
	at org.assertj.core.internal.Iterables.assertHasSize(Iterables.java:214)
	at org.assertj.core.api.AbstractIterableAssert.hasSize(AbstractIterableAssert.java:163)
	at io.camunda.zeebe.snapshots.impl.SnapshotChecksumTest.lambda$shouldFlushOnPersist$0(SnapshotChecksumTest.java:158)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.awaitility.core.SameThreadExecutorService.execute(SameThreadExecutorService.java:79)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:101)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.zeebe.snapshots.impl.SnapshotChecksumTest.shouldFlushOnPersist(SnapshotChecksumTest.java:154)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[zeebe.zip](https://github.com/user-attachments/files/16282717/zeebe.zip)

**Comment by lenaschoenburg** [comment]
Happened again: https://github.com/camunda/camunda/actions/runs/10068712561/job/27834542370

**Comment by EuroLew** [comment]
Reading the error it shows that the fsync call is "unfinished" 

`Run 1: SnapshotChecksumTest.shouldFlushOnPersist:154->lambda$shouldFlushOnPersist$0:158 ? IllegalArgument Expected line to match format of 'PID fsync(FD<PATH>) = RESULT', but '21558 fsync(133</tmp/junit2976503666581059383/checksum> <unfinished ...>' does not match`
 
The documentation for strace [here](https://man7.org/linux/man-pages/man1/strace.1.html) it mentions that unfinished just means its trying to maintain ordering it and the initial call did not finish before another call is made. This means that the <unfinished...> call is a valid `strace` trace.

To fix this flake the regex will be changed to also accept the unfinished trace and the test will be changed to instead of asserting system call success just that the system call was made (to account for the unfinished call which has the call result on a different line)
