### ISSUE TITLE
BeanCreationNotAllowedException: Error creating bean with name 'startupTimeMetrics'

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20343]
**Describe the bug**

Error occurred in the Gateway in a Prod cluster. It happened right after a Gateway shutdown, which is likely the cause.

**Expected behavior**

The Gateway should shutdown gracefully without throwing errors.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'startupTimeMetrics': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-6.0.18.jar:6.0.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.18.jar:6.0.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.0.18.jar:6.0.18]
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:264) ~[spring-context-6.0.18.jar:6.0.18]
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:221) ~[spring-context-6.0.18.jar:6.0.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:140) ~[spring-context-6.0.18.jar:6.0.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445) ~[spring-context-6.0.18.jar:6.0.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-6.0.18.jar:6.0.18]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76) ~[spring-boot-3.1.6.jar:3.1.6]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-3.1.6.jar:3.1.6]
	at io.camunda.zeebe.gateway.StandaloneGateway.main(StandaloneGateway.java:86) [camunda-zeebe-8.3.13.jar:8.3.13] 
```

</p>
</details>

**Environment:**
- OS: Cloud
- Zeebe Version: 8.3.13

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- There is no impact as we were shutting down anyway
- It's just noise on the logs
- Marking it as later and putting it in our backlog.

**Comment by npepinpe** [comment]
Same as ZPA :)

**Comment by npepinpe** [comment]
Did this happen only on 8.3? It seems like this was fixed in newer Spring versions, which 8.3 would not have: https://github.com/spring-projects/spring-boot/issues/38240

8.3 is on Spring Boot 3.1.x, and this fix is in 3.2.0+. I think considering how low it is, we can just close this. Please challenge me if you disagree.
