### ISSUE TITLE
`ConcurrentModificationException` during model transformation

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20361]
**Describe the bug**

Received a `ZeebeTooManySegments` alert. After checking the logs I found this exception at the root of the problem. It seems the actor never really recovered when this occurred. After a manual restart of the broker it all started working fine again.

**To Reproduce**

I don't know

**Expected behavior**

Transformation should never result in a `ConcurrentModificationException`

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=157797162, key=2251799892524398, timestamp=1720778525607, sourceEventPosition=157797158] RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE, intent=ELEMENT_ACTIVATING}'
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:170) ~[zeebe-stream-platform-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:205) [zeebe-scheduler-8.2.27.jar:8.2.27]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?]
	at org.camunda.bpm.model.xml.impl.ModelBuilderImpl.build(ModelBuilderImpl.java:75) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.ModelInstanceImpl.registerGenericType(ModelInstanceImpl.java:111) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElement(ModelUtil.java:91) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElement(ModelUtil.java:52) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at org.camunda.bpm.model.xml.impl.util.ModelUtil.getModelElementCollection(ModelUtil.java:179) ~[camunda-xml-model-7.18.0.jar:7.18.0]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.getChildElements(ModelWalker.java:92) ~[zeebe-bpmn-model-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:74) ~[zeebe-bpmn-model-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:115) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:172) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceStateForProcessByKey(DbProcessState.java:351) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByKey(DbProcessState.java:246) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:285) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.createEventScope(ProcessInstanceElementActivatingApplier.java:261) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:51) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState(ProcessInstanceElementActivatingApplier.java:32) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:344) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:110) ~[zeebe-workflow-engine-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:237) ~[zeebe-stream-platform-8.2.27.jar:8.2.27]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:210) ~[zeebe-stream-platform-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:164) ~[zeebe-stream-platform-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.2.27.jar:8.2.27]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.2.27.jar:8.2.27]
	... 5 more

```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.2.27

**Comment by remcowesterhoud** [comment]
Marking the likelihood as low. We transform a lot of processes all the time and we've never seen this happen before.

Marking the severity as mid. One partition became unhealthy so users would notice something was wrong. However, processing on ohter partitions was fine.

**Comment by lenaschoenburg** [comment]
This [occurred again](https://camunda.slack.com/archives/C07DGCVTTNF) for the same customer but a different cluster. I think this increases the likelihood that this is deterministic and reproducible.

**Comment by lenaschoenburg** [comment]
Based on the increased likelihood and the nature of this issue (how can there be concurrent modification if processing is single-threaded?) I'd propose to at least investigate the root cause immediately.

**Comment by megglos** [comment]
While overall likelihood may not be high, practically we experienced this now at least 3 times in two weeks, pushing it to top of upcoming to prevent potential more interruption.

**Comment by mustafadagher** [comment]
I took some time to investigate the root-cause of this. But I have some findings to share below:
- in https://github.com/camunda/camunda/blob/7017ea2ef98ccf41aec976de4d970e7878c09f8f/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbProcessState.java#L296 we read the `modelInstance` from the `resource` DirectBuffer
- The previous expression down the stack trace creates a new `modelInstance` here https://github.com/camunda/camunda/blob/7017ea2ef98ccf41aec976de4d970e7878c09f8f/zeebe/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/impl/BpmnParser.java#L73
- You can notice from above that both the `BpmnModel` and the `BpmnModelBuilder` are singletons shared across threads and instances
- I'll skip through a little bit, and come to where the error is thrown. Every time we call `registerGenericType()` https://github.com/camunda/camunda-bpm-platform/blob/f37877b822dabcbf3cee5806bd5833d18cdcb543/model-api/xml-model/src/main/java/org/camunda/bpm/model/xml/impl/ModelInstanceImpl.java#L107-L114 we do two things:
  1. `modelBuilder.defineGenericType()` which adds a new `typeBuilder` to the `typeBuilders` List
  2. `modelBuilder.build()` that iterates over these `typeBuilder`
- Now since we know that the `modelBuilder` is a singleton shared with different model instances, it (theoretically) happen that two model instances are doing the same thing above in the same time. so whilst the first is building it's model by iterating over the typeBuilders the other could be defining a GenericType, adding a new `typeBuilder` to the list.

I'm not sure if this could happen as I thought it out above in practice. But if so, to prevent it, we could either introduce read-write locks on the methods above, or replace the `ArrayList` with concurrent/blocking collection implementation

**Comment by megglos** [comment]
> You can notice from above that both the BpmnModel and the BpmnModelBuilder are singletons shared across threads and instances
> ...
> I'm not sure if this could happen as I thought it out above in practice. But if so, to prevent it, we could either introduce read-write locks on the methods above, or replace the ArrayList with concurrent/blocking collection implementation

Nice digging!

So we can conclude the used `BpmnModelBuilder` is not thread-safe but a singleton object of it is shared across all partitions of a broker.  In this case the concurrentModification happened during replay, but generally it can happen as soon as there is more than one partition active on a broker, across Leaders and Followers.

**Comment by remcowesterhoud** [comment]
This happened once more on a cluster that previously also encountered it.

**Comment by berkaycanbc** [comment]
Happened again on a trial cluster. ([link](https://camunda.slack.com/archives/C04D5HLFP24/p1733687232036479))

**Comment by megglos** [comment]
occurred on some clusters again, worth reassessing

**Comment by korthout** [comment]
We discussed this again, and need more info to prioritize it further. For now, it stays in backlog as upcoming.

**Comment by lenaschoenburg** [comment]
It occurred again: https://console.cloud.google.com/errors/detail/COmb47DJ5JilsQE;service=zeebe;time=P7D;locations=global?inv=1&invt=Abshsw&project=camunda-saas-prod-sin

> We discussed this again, and need more info to prioritize it further. For now, it stays in backlog as upcoming.

What more info do you need? 

Like @megglos said:
> So we either invest into a thread-safe impl of these like you suggested or we don't share a singleton across partitions, as for each partition we can assume there is no concurrent access to the model.

Using one instance per partition sounds like a relatively straight-forward fix to me?

**Comment by konstantinos-mylosis** [comment]
Based on [#inc-unhealthy-streamprocessor-blocks-zeebe-log-compaction-for-camunda-8-pro](https://camunda.slack.com/archives/C0C0DEBA37A) and the discussion, updated the urgency to `next`
