### ISSUE TITLE
`ActorLifecyclePhasesAndTimersTest` is flaky

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#20412]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Wanted but not invoked:
runnable.run();
-> at io.camunda.zeebe.scheduler.lifecycle.ActorLifecyclePhasesAndTimersTest.shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase(ActorLifecyclePhasesAndTimersTest.java:73)
Actually, there were zero interactions with this mock.

	at io.camunda.zeebe.scheduler.lifecycle.ActorLifecyclePhasesAndTimersTest.shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase(ActorLifecyclePhasesAndTimersTest.java:73)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

It's possible that the changes made in https://github.com/camunda/camunda/pull/20296 have made `workUntilDone` less reliable, thus causing the new flaky test.

**Comment by lenaschoenburg** [comment]
Actually a duplicate of #19874
