### ISSUE TITLE
Flaky io.camunda.process.test.api.ProcessInstanceAssertTest$IsTerminated shouldFailIfActive

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20486]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

```
org.mockito.exceptions.verification.TooFewActualInvocations: 

camundaDataSource.getProcessInstance(1L);
Wanted *at least* 2 times:
-> at io.camunda.process.test.impl.assertions.CamundaDataSource.getProcessInstance(CamundaDataSource.java:33)
But was 1 time:
-> at io.camunda.process.test.impl.assertions.ProcessInstanceAssertj.lambda$hasProcessInstanceInState$1(ProcessInstanceAssertj.java:100)

	at io.camunda.process.test.impl.assertions.CamundaDataSource.getProcessInstance(CamundaDataSource.java:33)
	at io.camunda.process.test.api.ProcessInstanceAssertTest$IsTerminated.shouldFailIfActive(ProcessInstanceAssertTest.java:379)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

https://github.com/camunda/camunda/actions/runs/10073845074
[Test results for unit tests.zip](https://github.com/user-attachments/files/16361327/Test.results.for.unit.tests.zip)

**Comment by mustafadagher** [comment]
We can also just increase the assertion timeout for now, and see if this happens again.
