### ISSUE TITLE
Failed to build variable mapping expression: failed to parse expression in 8.6.0-alpha3

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#20554]
**Describe the bug**
An error occurs while deploying a new BPMN resource. This is not handled gracefully but ends up as an `IllegalStateException` during processing.

**To Reproduce**

Not clear.

**Expected behavior**

Graceful error handling at least. Possibly fix the expression parsing if this is a bug.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to build variable mapping expression: failed to parse expression '<REDACTED>': Expected (start-of-input | ifOp | forOp | quantifiedOp | disjunction):1:1, found "'<REDACTED>"
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.VariableMappingTransformer.parseExpression(VariableMappingTransformer.java:199) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.VariableMappingTransformer.transformOutputMappings(VariableMappingTransformer.java:94) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.lambda$transformIoMappings$4(FlowNodeTransformer.java:87) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transformIoMappings(FlowNodeTransformer.java:85) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:45) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:24) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$3(BpmnResourceTransformer.java:77) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:70) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:130) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:106) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:151) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:105) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:374) ~[zeebe-stream-platform-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:242) ~[zeebe-stream-platform-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-alpha3.jar:8.6.0-alpha3]

```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6.0-alpha3

Error group: https://console.cloud.google.com/errors/detail/CPu8oYycy-7NWQ;locations=global?project=camunda-saas-prod-lhr
Possibly related to https://github.com/camunda/camunda/issues/15902

**Comment by megglos** [comment]
ZPA-Triage:
- impact => deploy is rejected, the error message should also make the issue clear enough => we log this as an error but should handle it gracefully => low
- it's mostly log noise, because the deployment is already rejected correctly 
- we assume low likelihood until we learn differently
