### ISSUE TITLE
StateMigrationTest.shouldMakeJobActivatableAfterMigrationAndBackoff is flaky

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#20721]
**Summary**

- How often does the test fail? - Once
- Does it block your work? - No
- Do we suspect that it is a real failure? - Not sure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: Condition with alias 'Initial job is activated' didn't complete within 10 seconds because lambda expression in io.camunda.zeebe.it.clustering.StateMigrationTest expected the predicate to return <true> but was null.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:712)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:729)
	at io.camunda.zeebe.it.clustering.StateMigrationTest.shouldMakeJobActivatableAfterMigrationAndBackoff(StateMigrationTest.java:54)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 6 more
</pre>
</details>

**Logs**
Build: https://github.com/camunda/camunda/actions/runs/10179980451/job/28156899826
Logs: [logs.zip](https://github.com/user-attachments/files/16467507/logs.zip)

**Comment by remcowesterhoud** [comment]
I had a look at it and don't see anything special. From the logging I can determine that the failure occurred during the test setup. It begins by creating a single job (this deploys a process with a service task and creates an instance). After the job is created we use Awaitility to activate the job. This await times out.

With the logging available to me I can't determine a cause for now. As I can see in the CI dashboard that this test hasn't failed a single time since it's reported, I'll close this as won't fix.

If this occurs again please reopen. If this happens please download the artifacts from the CI run and add them to this issue. Hopefully those logs provide more insights.
