### ISSUE TITLE
NPE in `BpmnStateBehavior.getParentElementInstanceContext` "parentElementInstance" is null

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#20762]
**Describe the bug**

A NullPointerException occurred during processing resulting in a banned process instance.

> Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=ACTIVATE_ELEMENT, authorization=UNKNOWN}, value={"bpmnElementType":"PROCESS","elementId":"\*\*\*","bpmnProcessId":"\*\*\*","version":<REDACTED>,"processDefinitionKey":2251800319895575,"processInstanceKey":2251800437052917,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":2251800437052573,"parentElementInstanceKey":2251800437052860,"tenantId":"\*\*\*"}}' without errors, but exception occurred with message 'Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "parentElementInstance" is null'.

**To Reproduce**

Not yet clear.

**Expected behavior**

We need to understand what happened here before we can describe the expected behavior, but generally we consider banned instances due to an exception a critical bug.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "parentElementInstance" is null
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.getParentElementInstanceContext(BpmnStateBehavior.java:110) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:469) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementActivating(BpmnStateTransitionBehavior.java:447) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:160) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:369) ~[zeebe-stream-platform-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:240) ~[zeebe-stream-platform-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.3.jar:8.5.3]
```

</p>
</details>

**Environment:**
- Zeebe Version: `8.5.3`
- [logs](https://cloudlogging.app.goo.gl/EG8pyjMHbnE8oXqbA) 
- [logs2](https://cloudlogging.app.goo.gl/JLcN6Kdhs84fxoZG8)
- [drive with persisted logs](https://drive.google.com/drive/folders/1JcFCwWnLaYhMG1QIme3LRyfpG9e-PzpD)

**Comment by korthout** [comment]
I've not been able to reproduce the error locally, but I understand the problem as follows:
- [Terminate End Event](https://docs.camunda.io/docs/next/components/modeler/bpmn/terminate-events) can terminate an active Call Activity for which the child process instance still needs to active through an unprocessed `ACTIVATE_ELEMENT` command
- When the child process instance's `ACTIVATE_ELEMENT` command is being processed, the Call Activity instance has already been `TERMINATED` resulting in the NPE
- The transition guard generally protect against the processing of commands for which the context has changed, e.g. we reject `ACTIVATE_ELEMENT` commands for which the flow scope is no longer active or has been interrupted, see below
- The transition guard does not protect against the processing of `ACTIVATE_ELEMENT` commands for child process instance where the Call Activity is no longer active or has been interrupted, see below

https://github.com/camunda/camunda/blob/5cb54707a2943e1214ecf7f03ea2845a1198ea4b/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/ProcessInstanceStateTransitionGuard.java#L56-L57

https://github.com/camunda/camunda/blob/5cb54707a2943e1214ecf7f03ea2845a1198ea4b/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/ProcessInstanceStateTransitionGuard.java#L168-L181

@saig0 Do you agree that the state transition guard should protect against activating a child process instance for which the call activity is no longer active or has been interrupted?

**Comment by korthout** [comment]
The same case occurred again and I was able to use the data to confirm my hypothesis.

>The call activity is activated and terminated by the Terminate End Event before its child process instance is activated. When the child instance ACTIVATE_ELEMENT command is processed, the call activity is already gone from the state and the NPE occurs resulting in banning the not existing child instance

**Comment by korthout** [comment]
In all cases that I can come up with for this bug, the child process instance should actually not be created (the call activity is interrupted / terminated prior to the child's activation). That means that banning the child instance is actually not loss of data. We can lower the severity to high.

**Comment by rodrigo-lourenco-lopes** [comment]
We seen this issue again in [8.8.9](https://console.cloud.google.com/errors/detail/CIjLitbt2-jfigE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911) 🤔 
In this cluster though, checking the metrics, I dont see any banned PIs. The only problem with the cluster taking a quick look is high backpressure due to high ammount of records not exported in two partitions.

This problem might another know issue potenttially, as I see backlog in the inter partition command queue, also being discussed in incident: [#inc-support-30949-deployments-not-distributed-in-partitions](https://camunda.slack.com/archives/C0A8Q71UZLJ)

<img width="1178" height="320" alt="Image" src="https://github.com/user-attachments/assets/05e4d4da-b206-4659-8241-751ea97dfbd6" />
