### ISSUE TITLE
"java.lang.IllegalStateException: logStream-raft-partition-partition-1 is closed" during transition from FOLLOWER to INACTIVE

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#20903]
**Describe the bug**

Seeing multiple errors similar to the one below (the cluster recovered eventually).

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>
```
exception: "java.lang.IllegalStateException: logStream-raft-partition-partition-1 is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.ensureOpen(LogStreamImpl.java:118) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.onCommit(LogStreamImpl.java:112) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorage.onCommit(AtomixLogStorage.java:68) ~[zeebe-broker-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$notifyCommitListeners$32(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.atomix.raft.impl.RaftContext.notifyCommitListeners(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.setCommitIndex(RaftContext.java:539) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:754) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:582) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:49) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:186) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$21(RaftContext.java:355) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$28(RaftContext.java:378) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$30(RaftContext.java:375) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```
</p>
</details>

Logs: 
https://drive.google.com/file/d/1VNhyuHQQ6ygBVEJo3XMM1Wx_8RRZPtcv/view?usp=drive_link 

**Environment:**
- Zeebe Version: 8.6.0-SNAPSHOT

**Comment by npepinpe** [comment]
@lenaschoenburg - I assume this is related to the new changes we introduced with the sync log stream. This seems to be mostly noise from what I can see, as we're transitioning from FOLLOWER to INACTIVE. However, I wonder if this could block the transition? Should we be able to selectively ignore this? 🤔

**Comment by lenaschoenburg** [comment]
Yeah this is just noise during shutdown but one that we _should_ have seen before, just with a different error message. I've added the `ensureOpen` check on `LogStreamImpl#onCommit` because this used to do an `actor#call` which would fail if the actor is closed.

I think we might as well just ignore this case and just ignore the `LogStreamImpl#onCommit` if the logstream is already closed?

**Comment by npepinpe** [comment]
So...a good first issue? ;)

**Comment by lenaschoenburg** [comment]
Sure, why not :shrug:

**Comment by koevskinikola** [comment]
There were some more occurrences of this issue on:

* Camunda SaaS (prod)
* Zeebe version `8.6.0-alpha4`
* [GCP logs](https://drive.google.com/file/d/13FDoHr8o6SEsBTg9Il6U3q1BNeDD0eUO/view?usp=sharing)
* [GCP logs link](https://console.cloud.google.com/errors/detail/CPjWi4Cyt7-WzAE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911)

**Comment by Zelldon** [comment]
occurrence on INT with alpha4-rc2 https://console.cloud.google.com/errors/detail/CPjWi4Cyt7-WzAE;service=zeebe;time=P7D;locations=global?project=camunda-saas-int

**Comment by Zelldon** [comment]
Happened on DEV alpha4 https://console.cloud.google.com/errors/detail/CPjWi4Cyt7-WzAE;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev

**Comment by npepinpe** [comment]
ZDP Triage: good first issue, may be tackled by a new comer. For now, backlog.

**Comment by Zelldon** [comment]
Again on prod:

```
 An uncaught exception occurred, transition to inactive role

java.lang.IllegalStateException: logStream-raft-partition-partition-2 is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.ensureOpen(LogStreamImpl.java:118) ~[zeebe-logstreams-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.onCommit(LogStreamImpl.java:112) ~[zeebe-logstreams-8.6.0-alpha4.jar:8.6.0-alpha4]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorage.onCommit(AtomixLogStorage.java:68) ~[zeebe-broker-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$notifyCommitListeners$32(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) ~[?:?]
	at io.atomix.raft.impl.RaftContext.notifyCommitListeners(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.impl.RaftContext.setCommitIndex(RaftContext.java:539) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:754) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:582) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:49) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:186) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$21(RaftContext.java:355) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$28(RaftContext.java:378) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$30(RaftContext.java:375) ~[zeebe-atomix-cluster-8.6.0-alpha4.jar:8.6.0-alpha4]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.6.0-alpha4.jar:8.6.0-alpha4]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]

```

**Comment by lenaschoenburg** [comment]
I've traced https://github.com/camunda/camunda/issues/21469 back to this bug. I think the impact analysis was wrong, as we saw from this test it can not only cause noise during shutdown but also break a partition during regular role transitions. We should fix it rather soon.
