### ISSUE TITLE
`TopologyFaultToleranceTest.shouldDetectTopologyChanges` is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#21469]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Caused by: java.lang.AssertionError: Expected partition <2> to have <3> replicas, but it has <2>: brokers <[BrokerInfoImpl{nodeId=2, host='10.124.11.3', port=1907, version=8.6.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=2, role=FOLLOWER, health=HEALTHY}, PartitionInfoImpl{partitionId=3, role=LEADER, health=HEALTHY}]}, BrokerInfoImpl{nodeId=0, host='10.124.11.3', port=1899, version=8.6.0-SNAPSHOT, partitions=[PartitionInfoImpl{partitionId=1, role=LEADER, health=HEALTHY}, PartitionInfoImpl{partitionId=2, role=LEADER, health=HEALTHY}, PartitionInfoImpl{partitionId=3, role=FOLLOWER, health=HEALTHY}]}]>
</pre>
</details>

[Test results for [IT] Zeebe QA - Integration Tests (1).zip](https://github.com/user-attachments/files/16707184/Test.results.for.IT.Zeebe.QA.-.Integration.Tests.1.zip)

This might be related to https://github.com/camunda/camunda/issues/10234

**Comment by lenaschoenburg** [comment]
From the provided test logs:
```
z18:25:05.586 [Broker-1] [raft-server-2] [raft-server-1-2] ERROR io.atomix.raft.impl.RaftContext - RaftServer{raft-partition-partition-2} - An uncaught exception occurred, transition to inactive role
java.lang.IllegalStateException: logStream-raft-partition-partition-2 is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.ensureOpen(LogStreamImpl.java:121) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.onCommit(LogStreamImpl.java:115) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425) ~[?:?]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorage.onCommit(AtomixLogStorage.java:68) ~[zeebe-broker-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$notifyCommitListeners$32(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:?]
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425) ~[?:?]
	at io.atomix.raft.impl.RaftContext.notifyCommitListeners(RaftContext.java:506) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.setCommitIndex(RaftContext.java:539) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.appendEntries(PassiveRole.java:754) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.PassiveRole.handleAppend(PassiveRole.java:582) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.ActiveRole.onAppend(ActiveRole.java:49) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.FollowerRole.onAppend(FollowerRole.java:186) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$21(RaftContext.java:355) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$28(RaftContext.java:378) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.lambda$handleRequestOnContext$30(RaftContext.java:375) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

So in this run, one of the brokers encountered https://github.com/camunda/camunda/issues/20903 and stayed in inactive mode. We should fix that bug first, there's no sense in trying to make this test more robust.
