### ISSUE TITLE
No enum constant io.camunda.zeebe.model.bpmn.instance.zeebe.ZeebeExecutionListenerEventType.assignment

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21575]
**Describe the bug**

[Error reported on production](https://console.cloud.google.com/errors/detail/CPqu9YSR6JKACA;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911) with `8.6.0-alpha4`

> Unexpected error while processing resource 'tmp.bpmn'

**To Reproduce**

Likely a process model with execution listeners.

**Expected behavior**

No error on deployment.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <pre>
java.lang.IllegalArgumentException: No enum constant io.camunda.zeebe.model.bpmn.instance.zeebe.ZeebeExecutionListenerEventType.assignment

at org.camunda.bpm.model.xml.impl.type.attribute.EnumAttribute.convertXmlValueToModelValue ( org/camunda.bpm.model.xml.impl.type.attribute/EnumAttribute.java:38 )
at org.camunda.bpm.model.xml.impl.type.attribute.EnumAttribute.convertXmlValueToModelValue ( org/camunda.bpm.model.xml.impl.type.attribute/EnumAttribute.java:27 )
at org.camunda.bpm.model.xml.impl.type.attribute.AttributeImpl.getValue ( org/camunda.bpm.model.xml.impl.type.attribute/AttributeImpl.java:112 )
at io.camunda.zeebe.model.bpmn.impl.instance.zeebe.ZeebeExecutionListenerImpl.getEventType ( io/camunda.zeebe.model.bpmn.impl.instance.zeebe/ZeebeExecutionListenerImpl.java:41 )
at io.camunda.zeebe.model.bpmn.validation.zeebe.ExecutionListenersValidator.lambda$validate$0 ( io/camunda.zeebe.model.bpmn.validation.zeebe/ExecutionListenersValidator.java:88 )
at io.camunda.zeebe.model.bpmn.validation.zeebe.ExecutionListenersValidator.validate ( io/camunda.zeebe.model.bpmn.validation.zeebe/ExecutionListenersValidator.java:92 )
at io.camunda.zeebe.model.bpmn.validation.zeebe.ExecutionListenersValidator.validate ( io/camunda.zeebe.model.bpmn.validation.zeebe/ExecutionListenersValidator.java:32 )
at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0 ( io/camunda.zeebe.model.bpmn.validation/ValidationVisitor.java:51 )
at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.visit ( io/camunda.zeebe.model.bpmn.validation/ValidationVisitor.java:51 )
at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit ( io/camunda.zeebe.model.bpmn.traversal/TypeHierarchyVisitor.java:39 )
at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk ( io/camunda.zeebe.model.bpmn.traversal/ModelWalker.java:73 )
at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate ( io/camunda.zeebe.engine.processing.deployment.transform/BpmnValidator.java:43 )
at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3 ( io/camunda.zeebe.engine.processing.deployment.transform/BpmnResourceTransformer.java:76 )
at io.camunda.zeebe.util.Either$Right.flatMap ( io/camunda.zeebe.util/Either.java:417 )
at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata ( io/camunda.zeebe.engine.processing.deployment.transform/BpmnResourceTransformer.java:74 )
at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource ( io/camunda.zeebe.engine.processing.deployment.transform/DeploymentTransformer.java:158 )
at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform ( io/camunda.zeebe.engine.processing.deployment.transform/DeploymentTransformer.java:114 )
at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment ( io/camunda.zeebe.engine.processing.deployment/DeploymentCreateProcessor.java:156 )
at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand ( io/camunda.zeebe.engine.processing.deployment/DeploymentCreateProcessor.java:107 )
at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord ( io/camunda.zeebe.engine.processing.streamprocessor/DistributedTypedRecordProcessor.java:33 )
at io.camunda.zeebe.engine.Engine.process ( io/camunda.zeebe.engine/Engine.java:127 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:374 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3 ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:284 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run ( io/camunda.zeebe.db.impl.rocksdb.transaction/ZeebeTransaction.java:109 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:284 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:242 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:83 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )

</pre>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.6.0-alpha4 
- Configuration:

**Comment by ce-dmelnych** [comment]
Thank you, @Zelldon , for reporting this issue!

After a quick investigation, it seems that the BPMN model was manually created or modified. 
Instead of valid Execution Listener configurations like:

```xml
<zeebe:executionListener eventType="start" type="start_el"/>
```
or
```xml
<zeebe:executionListener eventType="end" type="end_el"/>
```

the model was configured with:
```xml
<zeebe:executionListener eventType="assignment" type="unsupported_el"/>
```

The Modeler enforces fixed values for the `eventType` property to prevent this kind of issue.
<img width="281" alt="image" src="https://github.com/user-attachments/assets/9ac094c3-feed-4afa-810a-0430d897066c">

We'll discuss how it can be improved, possibly by providing a more descriptive error message that includes the correct values for enum properties used in BPMN configuration.

**Comment by megglos** [comment]
For me to understand the impact, there was a faulty model deployed, which I assume was rejected because of the error?
However we have "noise" in the log which is distracting, it should rather be a WARN statement at most? Can you confirm @Zelldon , or does that need more investigation to be sure?

Given this is a manually manipulated bpmn, as the modeler is not allowing such values, I would also assess likelihood as low, wdyt @ce-dmelnych ?

**Comment by ce-dmelnych** [comment]
> Given this is a manually manipulated bpmn, as the modeler is not allowing such values, I would also assess likelihood as low, wdyt @ce-dmelnych ?

I agree 👍

**Comment by Zelldon** [comment]
Can it be that this might also happen for C7 BPMN models ?

**Comment by Zelldon** [comment]
> For me to understand the impact, there was a faulty model deployed, which I assume was rejected because of the error?

Yes it should be rejected.

> However we have "noise" in the log which is distracting, it should rather be a WARN statement at most? Can you confirm @Zelldon , or does that need more investigation to be sure?

Jaein. Tbh with this error we already found several bugs in our deployment/transformation logic, which we wouldn't if it was just a warning. But right now it is often hard to reproduce, see also https://github.com/camunda/camunda/issues/21576

**Comment by ce-dmelnych** [comment]
> Can it be that this might also happen for C7 BPMN models ?

In C7 modeler we also have a fixed values for `eventType`:
<img width="734" alt="image" src="https://github.com/user-attachments/assets/5077c368-dc4e-4212-bdab-f36353118051">

So, if the model was manually modified, similar issue could occur in C7 as well.

**Comment by Zelldon** [comment]
@ce-dmelnych my question was more, can it happen that if I take a C7 model and deploy it to Zeebe, that Zeebe fails with the error we see here? Looks like the start and end are in c7 in small capitals and for C8 starting with big letters?

**Comment by ce-dmelnych** [comment]
> @ce-dmelnych my question was more, can it happen that if I take a C7 model and deploy it to Zeebe, that Zeebe fails with the error we see here?

Not really. There are some other differences in configuration between C7 and C8. For example, in C7, we use `event="start"` while in C8, it's `eventType="start"`.
So the deployment would likely fail even before encountering the `No enum constant ..` error.

> Looks like the start and end are in C7 in small capitals and for C8 starting with big letters?

I believe this is just a difference in the labels used in the Modeler; the dropdown values are still the same `start/end`.

---
In this particular case, it seems that someone tried to use the `assignment` [task listener](https://docs.camunda.org/manual/7.21/user-guide/process-engine/delegation-code/#task-listener-event-lifecycle) event type from C7 for execution listeners in C8, which is not supported.

**Comment by berkaycanbc** [comment]
Same error reported for our chaos tests but this time for Task Listeners. I did not create a new issue since the issue is the same but for different type.

[Error link](https://console.cloud.google.com/errors/detail/CIWEi5Hh2p6ZRQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos)
Version: `8.7.0-SNAPSHOT`

> Unexpected error while processing resource 'src/main/resources/processes/process_with_user_task_listeners.bpmn'

<details><summary>Full Stacktrace</summary>
 <pre>
java.lang.IllegalArgumentException: No enum constant io.camunda.zeebe.model.bpmn.instance.zeebe.ZeebeTaskListenerEventType.start
	at java.base/java.lang.Enum.valueOf(Unknown Source) ~[?:?]
	at org.camunda.bpm.model.xml.impl.type.attribute.EnumAttribute.convertXmlValueToModelValue(EnumAttribute.java:38) ~[camunda-xml-model-7.22.0.jar:7.22.0]
	at org.camunda.bpm.model.xml.impl.type.attribute.EnumAttribute.convertXmlValueToModelValue(EnumAttribute.java:27) ~[camunda-xml-model-7.22.0.jar:7.22.0]
	at org.camunda.bpm.model.xml.impl.type.attribute.AttributeImpl.getValue(AttributeImpl.java:112) ~[camunda-xml-model-7.22.0.jar:7.22.0]
	at io.camunda.zeebe.model.bpmn.impl.instance.zeebe.ZeebeTaskListenerImpl.getEventType(ZeebeTaskListenerImpl.java:41) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.function.Function.lambda$andThen$1(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.validation.zeebe.ZeebeElementValidator.lambda$validate$0(ZeebeElementValidator.java:48) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.validation.zeebe.ZeebeElementValidator.validate(ZeebeElementValidator.java:46) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.lambda$visit$0(ValidationVisitor.java:51) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.validation.ValidationVisitor.visit(ValidationVisitor.java:51) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:43) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3(BpmnResourceTransformer.java:81) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata(BpmnResourceTransformer.java:79) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:161) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:117) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:184) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:135) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:131) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:375) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:244) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]

</pre>
</details>

FYI @megglos @ce-dmelnych

**Comment by ce-dmelnych** [comment]
> Same error reported for our chaos tests but this time for Task Listeners. I did not create a new issue since the issue is the same but for different type.

Thank you for reporting this, @berkaycanbc!
I just realized it was me who triggered this error. This happened after I manually modified the XML during testing of initial `complete` task listener support.
