### ISSUE TITLE
Improve logging for missing certificate in store.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#21972]
**Describe the bug**

This issues originates from a [support incident](https://jira.camunda.com/browse/SUPPORT-23288?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D) where the customer moved to an external Keycloak and was unable to see webapps coming online. Through a bit of investigation they found that they needed to add a certificate to the Keystore for the domain used by Keycloak in zeebe-gateway.
The logging provided did not help much. The only thing in any of the logs was the following in zeebe-gateway debug logging:

```
io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor - Denying call gateway_protocol.Gateway/Topology as the token could not be fully verified. Error message: JWKS error…
```

Additionally the response in operate has a missing cause following the message "Failed to parse bearer token, see cause for details":

```
2024-08-23 14:42:27.472 DEBUG 7 --- [-worker-ELG-1-2] i.g.n.NettyClientHandler                 : [id: 0x5e5fd91d, L:/10.165.31.118:36376 - R:tmv-camunda-opensearch-zeebe-gateway/10.165.221.35:26500] INBOUND HEADERS: streamId=3151 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-status: 16, grpc-message: Failed to parse bearer token, see cause for details, x-envoy-upstream-service-time: 6, date: Fri, 23 Aug 2024 14:42:27 GMT, server: envoy] padding=0 endStream=true
```

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

[zeebe-conf.txt](https://github.com/user-attachments/files/16886927/zeebe-conf.txt)
[zeebe-gateway-conf.txt](https://github.com/user-attachments/files/16886928/zeebe-gateway-conf.txt)
[tasklist-conf.txt](https://github.com/user-attachments/files/16886929/tasklist-conf.txt)
[operate-conf.txt](https://github.com/user-attachments/files/16886931/operate-conf.txt)

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by korthout** [comment]
ZPA triage:
- There are more detailed logs missing
- The reported error seems truncated `...` perhaps more details were already available, but that's not clear currently
- In any case, we don't consider this a bug, but a missing feature (adding more detailed logs is an enhancement)

**Comment by korthout** [comment]
Marking as low impact (relieving an uncommon pain)

**Comment by megglos** [comment]
on https://jira.camunda.com/browse/SUPPORT-23477?focusedCommentId=368795&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-368795 we had log output on certificate issues when loading the jwks. 

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@252db4f
java.lang.IllegalStateException: io.camunda.identity.sdk.impl.rest.exception.RestException: request failed
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: io.camunda.identity.sdk.impl.rest.exception.RestException: request failed
	at io.camunda.identity.sdk.impl.rest.RestClient.send(RestClient.java:129)
	at io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:105)
	at io.camunda.identity.sdk.impl.generic.GenericAuthentication.wellKnownConfiguration(GenericAuthentication.java:177)
	at io.camunda.identity.sdk.impl.generic.GenericAuthentication.jwkProvider(GenericAuthentication.java:163)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verify(AbstractAuthentication.java:252)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyAndDecode(AbstractAuthentication.java:247)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:212)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:164)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33)
	at jdk.proxy2/jdk.proxy2.$Proxy108.verifyToken(Unknown Source)
	at io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor.interceptCall(IdentityInterceptor.java:79)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
	... 9 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at io.camunda.identity.sdk.impl.rest.RestClient.send(RestClient.java:118)
```

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | TASK_TOIL_NON_FEATURE |
| **Impact** | ℹ️ Low |
| **When** | ℹ️ Later |
| **Confidence** | 0.93 |

---

### 📝 Rationale

This is a logging/diagnostic quality-of-life improvement, not incorrect product behavior; existing triage notes explicitly classify it as a missing feature and low impact. A keystore workaround exists, and the pain is uncommon.  

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
