### ISSUE TITLE
Actor Scheduler fails to start on Gateway start

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#22149]
**Describe the bug**
On gateway start the Actor scheduler fails to start.
Similar to [this bug](https://github.com/camunda/camunda/issues/17614)

<details><summary>Exception</summary>
 <p>

```
java.util.concurrent.ExecutionException: Startup failed in the following steps: [JobStreamService]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:147) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:114) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:203) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.Broker.internalStart(Broker.java:103) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.util.LogUtil.doWithMDC(LogUtil.java:23) ~[zeebe-util-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.Broker.start(Broker.java:86) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:100) ~[camunda-zeebe-8.5.5.jar:8.5.5]
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.10.jar:6.1.10]
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.10.jar:6.1.10]
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.10.jar:6.1.10]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) ~[spring-boot-3.2.5.jar:3.2.5]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:?]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) [?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:?]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) [spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341) [spring-boot-3.2.5.jar:3.2.5]
	at io.camunda.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:82) [camunda-zeebe-8.5.5.jar:8.5.5]
Caused by: io.camunda.zeebe.scheduler.startup.StartupProcessException: Startup failed in the following steps: [JobStreamService]. See suppressed exceptions for details.
	at io.camunda.zeebe.scheduler.startup.StartupProcess.aggregateExceptionsSynchronized(StartupProcess.java:283) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:184) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:168) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	Suppressed: io.camunda.zeebe.scheduler.startup.StartupProcessStepException: Bootstrap step JobStreamService failed
		at io.camunda.zeebe.scheduler.startup.StartupProcess.completeStartupFutureExceptionallySynchronized(StartupProcess.java:186) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:168) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	Caused by: java.lang.IllegalStateException: Actor scheduler is not running
		at io.camunda.zeebe.scheduler.ActorScheduler.checkRunningState(ActorScheduler.java:70) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorScheduler.submitActor(ActorScheduler.java:58) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.ActorScheduler.submitActor(ActorScheduler.java:36) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.JobStreamServiceStep.startupInternal(JobStreamServiceStep.java:50) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.lambda$startup$0(AbstractBrokerStartupStep.java:25) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.lambda$createFutureAndRun$2(AbstractBrokerStartupStep.java:58) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.forwardExceptions(AbstractBrokerStartupStep.java:71) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.createFutureAndRun(AbstractBrokerStartupStep.java:58) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.startup(AbstractBrokerStartupStep.java:22) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.AbstractBrokerStartupStep.startup(AbstractBrokerStartupStep.java:17) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.callDelegateAndUpdateTimer(BrokerStepMetricDecorator.java:62) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:44) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.broker.bootstrap.BrokerStepMetricDecorator.startup(BrokerStepMetricDecorator.java:25) ~[zeebe-broker-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.proceedWithStartupSynchronized(StartupProcess.java:162) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3(StartupProcess.java:170) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
		... 6 more 
```
</p>
</details>

**Log/Stacktrace**

[Full logs](https://drive.google.com/file/d/1TH8KxxWhvS0g72aiyuu7hereAY456KAl/view?usp=sharing)

**Environment:**
- OS: 
- Zeebe Version:  8.5.5
- Configuration:

**Comment by npepinpe** [comment]
We can see that the node is shutting down when this is happening. I'd classify the severity as low then, as it's mostly just noise. And the cluster later recovered anyway. It seems to be mostly just a race condition between the startup and the shutdown, specifically the broker start up (which we do wait for) and the Spring shutdown hook (which is called immediately and closes the beans). The main cause is the streamlining refactoring, which introduced the `Broker` bean, but does not specify any dependencies between it and the actor scheduler, so they are closed asynchronously.
