### ISSUE TITLE
Release benchmarks are broken for versions before 8.5.x

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#22407]
**Description**

After last weeks release, release benchmarks are broken for versions 8.4.x, 8.3.x and 8.2.x. 

Preliminary Investigation:
Brokers are running, but gateway pods are not getting ready because the readiness check fails due to connection refused.
```
Warning  Unhealthy  2m25s (x52265 over 12d)  kubelet  Readiness probe failed: Get "http://10.0.18.8:9600/actuator/health/readiness": dial tcp 10.0.18.8:9600: connect: connection refused
```

Starters and workers cannot connect to the gateway due to connection refused errors.
```
 io.camunda.zeebe.App - Topology request failed
io.camunda.zeebe.client.api.command.ClientStatusException: io exception
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116) ~[zeebe-client-java-8.4.11.jar:8.4.11]
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54) ~[zeebe-client-java-8.4.11.jar:8.4.11]
	at io.camunda.zeebe.App.printTopology(App.java:90) [classes/:?]
	at io.camunda.zeebe.Starter.run(Starter.java:60) [classes/:?]
	at io.camunda.zeebe.App.createApp(App.java:59) [classes/:?]
	at io.camunda.zeebe.Starter.main(Starter.java:230) [classes/:?]
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52) ~[zeebe-client-java-8.4.11.jar:8.4.11]
	... 4 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.65.1.jar:1.65.1]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.65.1.jar:1.65.1]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.65.1.jar:1.65.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.65.1.jar:1.65.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.65.1.jar:1.65.1]
	at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57) ~[micrometer-core-1.12.6.jar:1.12.6]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564) ~[grpc-core-1.65.1.jar:1.65.1]
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72) ~[grpc-core-1.65.1.jar:1.65.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729) ~[grpc-core-1.65.1.jar:1.65.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710) ~[grpc-core-1.65.1.jar:1.65.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.65.1.jar:1.65.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.65.1.jar:1.65.1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: release-8-4-x-zeebe-gateway/10.4.6.109:26500
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by npepinpe** [comment]
If you don't get around to it, let us know here, and I will assign someone to it next week.

**Comment by korthout** [comment]
I did not get around to this @npepinpe

**Comment by lenaschoenburg** [comment]
I'll pick it up as medic

**Comment by megglos** [comment]
Moving to inbox, needs reassignment.

**Comment by npepinpe** [comment]
as I missed planning, I will assign someone directly :)

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes since you're between topics, could you take a look at this?

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes - did you forget to update with your findings here?

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes - did you forget to update with your findings here?

Yes sorry, I only gave the update on the team meeting. 

A quick summary from my timed boxed investigation: 
I could not find any more good leads from the logs besides observing the same problem with gateway not being able to discover the brokers. 
I tried to restart the broker pods and the gateway pods, but the problem persisted. 
I checked the deployments configurations comparing to the releases that are not affected and this is also not the problem.

My next step would be trying to do similar benchmarks and replicate the issue.

**Comment by lenaschoenburg** [comment]
This is fixed, the release benchmarks for 8.3, 8.4 and 8.5 are working now.
