### ISSUE TITLE
NPE when deploying new version of process due to invalid execution listener configuration

### ISSUE THREAD

**Issue by ce-dmelnych** [camunda/camunda#22520]
**Issue description**

fter upgrading from version `8.4.9` to `8.5.6`, the customer encountered a `NullPointerException` when deploying a new version (29) of an existing process. This issue arises during the invocation of `StartEventSubscriptionManager.closeExistingStartEventSubscriptions`, which iterates through the definitions of previous process versions in reverse order (e.g., 28, 27, ..., 18). An NPE is thrown when processing version 18 due to invalid execution listener (EL) configuration.

The snippet below illustrates the invalid EL configuration from process version 18:
```xml
<bpmn:receiveTask id="Activity_1bqm35l" name="File.Split.Done" messageRef="Message_3st9end">
  <bpmn:extensionElements>
    <zeebe:executionListeners>
      <zeebe:executionListener eventType="start" />
    </zeebe:executionListeners>
  </bpmn:extensionElements>
</bpmn:receiveTask>
```

It was configured without the required `type` property.

Typically, during the deployment of this process, Zeebe should reject it with the following error:
```
Element: ... > extensionElements > executionListeners > executionListener
- ERROR: Attribute 'type' must be present and not empty
```

However, since this process was successfully deployed using version `8.4.9` (or earlier), before the initial execution listener support and validation were introduced, the validation for EL configuration was not invoked and now it leads to an NPE when transforming the process with version 18 in an environment running `8.5.0` or higher.

**To reproduce**
1. Deploy a process with an invalid EL configuration (e.g., missing `eventType` or `type` property) using Zeebe v8.4.9.
   - The process should deploy successfully.
2. Upgrade to Zeebe v8.5.0 or higher.
3. Try to deploy the new process version with valid EL configuration (or even without EL setup).
4. Observe the NPE during the new process version deployment.

**Expected behavior**
- Allow the deployment of the new process version without EL configuration violations by filtering out incorrectly configured execution listeners for previous process versions during the transformation.
- Provide a clear and descriptive error message indicating the specific reason for the failure when EL configured in a wrong way for the previous process versions.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
13:45:58.743 [Broker-0] [zb-actors-0] [StreamProcessor-1] ERROR io.camunda.zeebe.broker.process - Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE, authorization=JWT.eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJ6ZWViZS1nYXRld2F5IiwiYXVkIjoiemVlYmUtYnJva2VyIiwic3ViIjoiemVlYmUtY2xpZW50IiwiYXV0aG9yaXplZF90ZW5hbnRzIjpbIjxkZWZhdWx0PiJdfQ.}, value={"resources":[],"processesMetadata":[{"bpmnProcessId":"sco.asb-send-receive","version":29,"processDefinitionKey":2251800871597729,"resourceName":"sco.asb-send-receive-v28.bpmn","checksum":"Q0PgqYN7iC3MIfqUkmnN0A==","isDuplicate":false,"tenantId":"<default>"}],"decisionRequirementsMetadata":[],"decisionsMetadata":[],"formMetadata":[],"tenantId":"<default>"}}' without errors, but exception occurred with message 'expression'.
java.lang.NullPointerException: expression
	at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[classes/:?]
	at io.camunda.zeebe.el.impl.FeelExpressionLanguage.parseExpression(FeelExpressionLanguage.java:59) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.addListenerToFlowNode(ExecutionListenerTransformer.java:35) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.lambda$transform$0(ExecutionListenerTransformer.java:25) ~[classes/:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.transform(ExecutionListenerTransformer.java:24) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.lambda$transformExecutionListeners$5(FlowNodeTransformer.java:99) ~[classes/:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transformExecutionListeners(FlowNodeTransformer.java:97) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:46) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:24) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[classes/:?]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[classes/:?]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[classes/:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:243) ~[classes/:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceState(DbProcessState.java:412) ~[classes/:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByProcessIdAndVersion(DbProcessState.java:312) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.findLastStartProcess(StartEventSubscriptionManager.java:130) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.closeMessageExistingStartEventSubscriptions(StartEventSubscriptionManager.java:89) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.closeExistingStartEventSubscriptions(StartEventSubscriptionManager.java:74) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.StartEventSubscriptionManager.tryReOpenStartEventSubscription(StartEventSubscriptionManager.java:59) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:109) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[classes/:?]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:369) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:282) ~[classes/:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:282) ~[classes/:?]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:240) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute$$$capture(ActorJob.java:47) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
```

</p>
</details>

Process versions where the issue was encountered:

**Environment:**
- OS: 
- Zeebe Version: 8.5.6
- Configuration:

**Comment by tmetzke** [comment]
I guess this is related to [this issue](https://github.com/camunda/camunda/issues/11253). If we stop looping through the whole history of a process definition upon deployment of a new version, this might not happen anymore.

**Comment by korthout** [comment]
ZPA triage:
- root cause is not specific to execution listeners, users can deploy processes with not yet supported zeebe extension elements -> we could reject deployments with unsupported extension elements, let's extract this to a different issue @ce-dmelnych 
- solution: we can filter transformers for not yet supported extension elements
- additional potential solution is fixing #11253
- impact: user was blocked from deploying new versions of this process 
- workaround: delete the older (broken) version
- severity: mid
- likelihood: low (low through Modeler, low through bpmn-model api as it requires version)
- prio: later

**Comment by korthout** [comment]
WIP: https://github.com/camunda/camunda/compare/stable/8.6...korthout-dead-partition-after-execution-listener-update
