### ISSUE TITLE
Error when performing an upgrade from Optimize 3.13/8.5 to 8.6

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23168]
Engineering DRI: @grlimacan

### Describe the bug

When performing an upgrade from Optimize  3.13/8.5 to 8.6, the following error is thrown:
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ExistsRequest.id'
2024-10-08 17:35:15     at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:89)
2024-10-08 17:35:15     at org.opensearch.client.opensearch.core.ExistsRequest.<init>(ExistsRequest.java:99)
2024-10-08 17:35:15     at org.opensearch.client.opensearch.core.ExistsRequest.<init>(ExistsRequest.java:60)
2024-10-08 17:35:15     at org.opensearch.client.opensearch.core.ExistsRequest$Builder.build(ExistsRequest.java:471)
2024-10-08 17:35:15     at io.camunda.optimize.service.db.os.OptimizeOpenSearchClient.exists(OptimizeOpenSearchClient.java:377)
2024-10-08 17:35:15     at io.camunda.optimize.service.db.DatabaseClient.countWithoutPrefixWithExistsCheck(DatabaseClient.java:95)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.plan.factories.UpgradePlanFactory.isC7LicenseDataPresent(UpgradePlanFactory.java:25)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.plan.factories.UpgradePlanFactory.validateOptimizeModeAndFailIfC7DataPresent(UpgradePlanFactory.java:37)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.plan.factories.Upgrade313To86PlanFactory.createUpgradePlan(Upgrade313To86PlanFactory.java:33)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.plan.UpgradePlanRegistry.lambda$new$0(UpgradePlanRegistry.java:46)
2024-10-08 17:35:15     at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.plan.UpgradePlanRegistry.<init>(UpgradePlanRegistry.java:39)
2024-10-08 17:35:15     at io.camunda.optimize.upgrade.main.UpgradeMain.main(UpgradeMain.java:62)
```

This error seems to have been introduced between the building of the RC1 and RC2 release candidates. Since the feature was validate with RC1, the error went unnoticed into the release

### Expected behaviour

The upgrade works as expected

### To Reproduce

Start an Optimize Upgrade with 8.6

### Environment observed:

- Optimize mode(s): C8SM
- Optimize version(s): 8.6.0
- Database(s) (Elasticsearch/OpenSearch): OpenSearch

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23169
- [ ] https://github.com/camunda/camunda/pull/23194
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [x] All Review stages are successfully completed
- [x] All associated PRs are merged to the main branch(es) and stable branches
- [x] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
This has been fixe and tested agains 8.6.1-rc1

The upgrade works as expected

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/4db5c497-3216-42c6-8e54-3684303b50fc">

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/eb1d5796-48bd-467a-ad8a-a8aee4483c95">

**Comment by RobertDorlan** [comment]
FYI @grlimacan 


Tested agains 3.13.0 to 8.6.1

![image](https://github.com/user-attachments/assets/b71b792c-4071-4f80-888d-baeb7083b854)

![image](https://github.com/user-attachments/assets/af1b56fb-89b4-4009-b245-540f63b7baa4)
