### ISSUE TITLE
NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "flowScope" is null

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#23440]
An NPE occurs while cancelling a process instance:

```
Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=PROCESS_INSTANCE, intent=CANCEL, authorization=<REDACTED>}, value={"bpmnElementType":"UNSPECIFIED","elementId":"","bpmnProcessId":"","version":-1,"processDefinitionKey":-1,"processInstanceKey":-1,"flowScopeKey":-1,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}}' without errors, but exception occurred with message 'Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "flowScope" is null'.
```

Stack trace:
```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getKey()" because "flowScope" is null
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateBehavior.getFlowScopeContext(BpmnStateBehavior.java:103) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:464) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:423) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.lambda$onChildTerminated$7(SubProcessProcessor.java:160) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onChildTerminated(SubProcessProcessor.java:143) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.container.SubProcessProcessor.onChildTerminated(SubProcessProcessor.java:25) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.lambda$onElementTerminated$5(BpmnStateTransitionBehavior.java:428) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.invokeElementContainerIfPresent(BpmnStateTransitionBehavior.java:478) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnStateTransitionBehavior.onElementTerminated(BpmnStateTransitionBehavior.java:423) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$onTerminate$8(JobWorkerTaskProcessor.java:119) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.onTerminate(JobWorkerTaskProcessor.java:106) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.onTerminate(JobWorkerTaskSupportingProcessor.java:60) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.onTerminate(JobWorkerTaskSupportingProcessor.java:18) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:174) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:369) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:240) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.8.jar:8.5.8]
```

Error group: https://console.cloud.google.com/errors/detail/CMy5vNinz4ahFA;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911
Zeebe version: 8.5.8

**Comment by megglos** [comment]
Instance will be banned, the user wanted to stop it anyway.
Impact: instance appears as running but isn't anymore, can also not be cleaned up

**Comment by korthout** [comment]
I'll raise this at the upcoming mob programming session, as it lends itself well to investigation:
- we have the data folder available for analysis
- we can figure out what the process looks like where this happened
- we can try to figure out why the flow scope is null

**Comment by korthout** [comment]
@remcowesterhoud @ce-dmelnych @mustafadagher and I investigated this issue today in our mob programming session. Sadly, we we're unable to root cause the issue.

The main finding:
- the stacktrace shows that either of these is true:
  - the flow scope instance containing the sub process instance is null.
  - the sub process instance has `-1` as its `flowScopeKey` even though it must be contained by a flow element.

However, we encountered the following problems that halted our investigation:

- the data folder does not contain any banned instances

```
zdb state list -cf BANNED_INSTANCE -p ./raft-partition/partitions/1/snapshots/456388427-534-484405792-0
{"data":[]}%
```

Nor after replay:
```
zdb state list -cf BANNED_INSTANCE -p ./raft-partition/partitions/1/runtime
{"data":[]}%
```

- the reported error no longer refers to logs as the issue is > 30 days old
- the logs were not added to the issue
- the stacktrace and error message don't show any keys to use for our investigation
- there are 35 processes deployed, making it hard to just select one 🤷 

```
zdb process list -p ./raft-partition/partitions/1/runtime | jq '.data | length'
35
```

---

As we see no other way to continue this investigation, we close this issue. Please re-open it if you encounter this.

**Comment by nicpuppa** [comment]
This error happened again, I'll try to grab the data folder. Here the [link](https://cloudlogging.app.goo.gl/q5ecEUNWHKhGQPVL7) to the logs

**Comment by berkaycanbc** [comment]
I dig into the issue once again with the fresh data folder shared. I've found exactly the same patterns as @korthout mentioned above https://github.com/camunda/camunda/issues/23440#issuecomment-2476430025.

However, I can share some notes:

- The instance is not in banned instance state because we do not ban instance on cancellation. Even if the exception is thrown while processing `TERMINATE_ELEMENT` for a service task, we still do the `shouldBanInstanceOnError` check on the source command. E.g. if a `TERMINATE_ELEMENT` command appended as a follow-up on `CANCEL` command fails, instance is not banned because we do not ban instances on errors while processing `CANCEL` command ([ref](https://github.com/camunda/camunda/blob/f28651eddb7a797073849d99e50a62687cdee262/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/intent/ProcessInstanceIntent.java#L22)).

Therefore, not having the instance in the banned state makes sense.

- In the latest data folder, there was only one `CANCEL` command in the log. When I inspect the related process, I did not see anything weird. Plus, I run a cancelation test on the process and it succeeds.

- For future reporters of the issue, **please also attach downloaded logs and exported records**. Since no error event is appended to the log stream, we do not have parameters to for rejection. Exported records should contain rejection.

**Comment by lev-safro** [comment]
Triaged with @ArezooAzar.

@berkaycanbc @mustafadagher @korthout how should we proceed here? There were a couple investigations already done, what's the conclusion?

Could you please reach out to @ArezooAzar regarding any verification of this issue.

**Comment by rodrigo-lourenco-lopes** [comment]
Happened [here](https://console.cloud.google.com/errors/detail/CLqT9JHbo_PEmAE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911) again in zeebe:8.8.9

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | ⚠️ Mid |
| **Confidence** | 0.85 |

---

### 📝 Rationale

The issue describes a NullPointerException occurring during process instance cancellation in Zeebe, which results in the instance appearing as running but being unmanageable. This is incorrect behavior in a released version, fitting the definition of a BUG. The impact is noticeable (processes cannot be cleaned up, but there is no evidence of data loss or security risk), so severity is MID. The issue has recurred across multiple versions and has been reported by several users, but is not described as affecting all users or every cancellation, so likelihood is MID. The issue is within Core Features team boundaries.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by rodrigo-lourenco-lopes** [comment]
We had another another [case with this error](https://console.cloud.google.com/logs/query;cursorTimestamp=2026-02-24T07:44:14.339900047Z;duration=PT3H;query=resource.labels.namespace_name%3D%22c6601073-972b-4c3b-beb3-13eb525ad984-zeebe%22%0Aseverity%3D%22ERROR%22%0Atimestamp%3D%222026-02-24T07:44:14.339900047Z%22%0AinsertId%3D%22uf1sgo17eh03off3%22?project=camunda-cloud-240911), we opened an incident since this cluster also had problems exporting. The data folder is pined in the incident channel [#inc-unable-to-find-pi-key](https://camunda.slack.com/archives/C0AGBJL7XAT)
