### ISSUE TITLE
Missing version property when creating a resource causes an exception

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#23536]
**Describe the bug**

See following [GCP logs](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CI7Z3fDnpK-ZOw%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%225ebc0c99-1333-48ab-93f9-2656a92d6378-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22europe-west2%22%0Aresource.labels.project_id%3D%22camunda-saas-prod-lhr%22%0Aresource.labels.cluster_name%3D%22worker-6%22;cursorTimestamp=2024-10-15T10:04:01.763635609Z;startTime=2024-10-15T09:34:31.763Z;endTime=2024-10-15T10:34:31.763Z?project=camunda-saas-prod-lhr). An exception is thrown while deploying a resource if version is missing.

Logs downloaded

**To Reproduce**

The process causing the issue is not available since the error is thrown while deploying the process definition.

**Expected behavior**

Validation is performed on the command preemptively such that no exception is thrown.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.msgpack.MsgpackPropertyException: Property 'version' is invalid: Expected a value or default value to be specified, but has nothing
	at io.camunda.zeebe.msgpack.property.BaseProperty.resolveValue(BaseProperty.java:65) ~[zeebe-msgpack-value-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.msgpack.property.BaseProperty.getEncodedLength(BaseProperty.java:71) ~[zeebe-msgpack-value-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength(ObjectValue.java:203) ~[zeebe-msgpack-value-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength(ObjectValue.java:141) ~[zeebe-msgpack-value-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getEncodedLength(UnifiedRecordValue.java:36) ~[zeebe-protocol-impl-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.protocol.impl.record.value.deployment.ProcessMetadata.getEncodedLength(ProcessMetadata.java:162) ~[zeebe-protocol-impl-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.msgpack.UnpackedObject.getLength(UnpackedObject.java:57) ~[zeebe-msgpack-value-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getLength(UnifiedRecordValue.java:30) ~[zeebe-protocol-impl-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.protocol.impl.record.value.deployment.ProcessMetadata.getLength(ProcessMetadata.java:156) ~[zeebe-protocol-impl-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.util.buffer.BufferUtil.createCopy(BufferUtil.java:74) ~[zeebe-util-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.protocol.impl.record.value.deployment.DeploymentRecord.getProcessesMetadata(DeploymentRecord.java:104) ~[zeebe-protocol-impl-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.checkForDuplicateBpmnId(BpmnResourceTransformer.java:171) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$createMetadata$3(BpmnResourceTransformer.java:88) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.createMetadata(BpmnResourceTransformer.java:79) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:161) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:117) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.transformAndDistributeDeployment(DeploymentCreateProcessor.java:164) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processNewCommand(DeploymentCreateProcessor.java:115) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.DistributedTypedRecordProcessor.processRecord(DistributedTypedRecordProcessor.java:33) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:131) ~[zeebe-workflow-engine-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:375) ~[zeebe-stream-platform-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:244) ~[zeebe-stream-platform-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) [zeebe-scheduler-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0.jar:8.6.0]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0.jar:8.6.0]
```

</p>
</details>

**Environment:**
- OS:  Camunda SaaS prod
- Zeebe Version:  `8.6.0`
- Configuration:

**Comment by nicpuppa** [comment]
Happened again in 8.6.8, [link to the error group](https://console.cloud.google.com/errors/detail/CI7Z3fDnpK-ZOw;service=zeebe;time=P7D;locations=global?inv=1&invt=AbqKTQ&project=camunda-saas-dev)
