### ISSUE TITLE
Flaky AuthorizationAddPermissionAuthorizationIT.shouldBeAuthorizedToAddPermissionsWithUser

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#23554]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? often
- Does it block your work? no
- Do we suspect that it is a real failure? yes

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.client.api.command.ProblemException: 
Failed with code 404: 'Not Found'. Details: 'class ProblemDetail {
    type: about:blank
    title: NOT_FOUND
    status: 404
    detail: Command 'ADD_PERMISSION' rejected with code 'NOT_FOUND': Expected to find owner with key: '2251799813685250', but none was found
    instance: /v2/authorizations/2251799813685250
}'
	at io.camunda.zeebe.client.impl.http.ApiCallback.handleErrorResponse(ApiCallback.java:111)
	at io.camunda.zeebe.client.impl.http.ApiCallback.completed(ApiCallback.java:59)
	at io.camunda.zeebe.client.impl.http.ApiCallback.completed(ApiCallback.java:30)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:72)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$2$1.completed(InternalAbstractHttpAsyncClient.java:304)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer$1.completed(AbstractAsyncResponseConsumer.java:101)
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:84)
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:81)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:251)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:270)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:334)
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64)
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

The authorization add permissions command is sent to a random partition. The user create command is sent to partition 1. If the add permissions command goes to a different partition than the user create, it could be that the user doesn't exist yet due to eventual consistency. We must ensure we always send the add permissions to partition 1 as well.

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by remcowesterhoud** [comment]
Appears the fix didn't help and it's still flaky.
