### ISSUE TITLE
Flaky `io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest shouldQueryFlowNodeInstanceByIncident`

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#23978]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Often
- Does it block your work? No
- Do we suspect that it is a real failure? No clue

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.opentest4j.AssertionFailedError: 

expected: 1
 but was: 20
	at io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest.shouldQueryFlowNodeInstanceByIncident(ProcessInstanceAndFlowNodeInstanceQueryTest.java:676)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

Couldn't get any because the artifacts aren't stored. See https://camunda.slack.com/archives/C071KP5BTHB/p1729758811450069

Example CI run: https://github.com/camunda/camunda/actions/runs/11495201327

**Comment by mustafadagher** [comment]
This now fails as we have anticipated in the mob-programming session when opted for the change in https://github.com/camunda/camunda/pull/24010 
```
  <no name>: io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest
No value present
java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.orElseThrow(Optional.java:377)
at io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest.beforeAll(ProcessInstanceAndFlowNodeInstanceQueryTest.java:94)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by tmetzke** [comment]
> This now fails as we have anticipated in the mob-programming session when opted for the change in #24010
> 
> ```
>   <no name>: io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest
> No value present
> java.util.NoSuchElementException: No value present
> at java.base/java.util.Optional.orElseThrow(Optional.java:377)
> at io.camunda.it.client.ProcessInstanceAndFlowNodeInstanceQueryTest.beforeAll(ProcessInstanceAndFlowNodeInstanceQueryTest.java:94)
> at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
> at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
> ```
> 
> That might alarm for an underlying bug where we have `FlowNodeInstance` with an incident key but with `hasIncident` set to false.

@ralfpuchert, any ideas on why that might be the case would be great as we need to find out if this is a bug in exporting, searching, or test setup/timing

**Comment by tmetzke** [comment]
Could be handled and checked on together with https://camunda.slack.com/archives/C06UKS51QV9/p1729850461025129 directly, moving away from "hasIncident" to encoding this in the flow node instance state. But it might also have drawbacks that we need to consider.
