### ISSUE TITLE
io.camunda.zeebe.engine.processing.authorization.RoleTest causing JVM crashes

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#24024]
**Describe the bug**

I'm opening a bug issue instead of a flaky test, because the consequence is not just that the test is flaky, but that it's crashing the JVM. I would recommend we consider this a bug to start with, and downgrade it to flaky test if we identify it's _only_ occurring in tests.

Happened in this run: https://github.com/camunda/camunda/actions/runs/11502526769/job/32017737075

**To Reproduce**

Unclear yet, but I suppose re-running the test would work.

**Expected behavior**

JVM does not crash :)

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/_work/camunda/camunda/zeebe/engine' && '/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.5-11.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20241024153602999_1725.jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-10-24T15-31-42_949-jvmRun3' 'surefire-20241024153602999_1723tmp' 'surefire_214-20241024153602999_1724tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.authorization.RoleTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/_work/camunda/camunda/zeebe/engine' && '/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.5-11.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20241024153602999_1725.jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-10-24T15-31-42_949-jvmRun3' 'surefire-20241024153602999_1723tmp' 'surefire_214-20241024153602999_1724tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.authorization.RoleTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:358)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:296)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1336)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1134)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:968)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Error:  	at java.base/java.lang.Thread.run(Thread.java:1583)
Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/_work/camunda/camunda/zeebe/engine' && '/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.5-11.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20241024153602999_1725.jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-10-24T15-31-42_949-jvmRun3' 'surefire-20241024153602999_1723tmp' 'surefire_214-20241024153602999_1724tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.authorization.RoleTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:643)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.lambda$null$3(ForkStarter.java:350)
Error:  	... 4 more
```

</p>
</details>

**Comment by nicpuppa** [comment]
After investigating the failure I'll downgrade the issue as flaky test instead of a bug, a fix is coming
