### ISSUE TITLE
Exported record with duplicate sequence number

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#24192]
**Describe the bug**

In Zeebe we increase the `sequenceNumber` of a record only on successful or async flush:

https://github.com/camunda/camunda/blob/c0a936b2fac2037a1cf9470a590dfba5202c5593/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L119-L130

If the `flush()` fails and the exporter retries to export the record, we are fine as the record gets the same sequence value. 
If the `flush()` fails and the exporter gets closed it will try to flush again, which may succeed:

https://github.com/camunda/camunda/blob/c0a936b2fac2037a1cf9470a590dfba5202c5593/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L89-L105

In this scenario Zeebe updates the last position while not increments the sequence counter.

When Zeebe tries to export the next batch of records, the first record with the same `ValueType` of the next batch gets the same sequence number of the one that fails in the previous batch.

There are 2 possible fix for this:

1. Always update the sequence before trying to flush -> ensuring that the sequence is always updated even if there is an error, this can lead to skipping some sequence number on exported records. This shouldn't be a problem as Operate and Tasklist should import new records with the sequence number bigger than the last known sequence.
2. Update the sequence number on actor `close()` if the flush succeed

Related support cases (internal [#1](https://jira.camunda.com/browse/SUPPORT-24263) [#2](https://jira.camunda.com/browse/SUPPORT-24199))

**To Reproduce**

An error should happen while exporting the record and the actor should be close

**Expected behavior**

The sequence number should not be duplicated

**Log/Stacktrace**

This is the error happened on ES, but it's not fully related to the bug.

<details><summary>Full Stacktrace</summary>
 <p>

```
Error on exporting record with key 4503600741741953
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk
	at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:166) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:111) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:202) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:120) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:202) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:201) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:179) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:570) ~[zeebe-broker-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.5.jar:8.5.5]
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-96 [ACTIVE]
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:915) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-8.9.2.jar:8.9.2]
	at io.camunda.zeebe.exporter.ElasticsearchClient.sendRequest(ElasticsearchClient.java:250) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:164) ~[zeebe-elasticsearch-exporter-8.5.5.jar:8.5.5]
	... 16 more
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-96 [ACTIVE]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:98) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:506) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

```

</p>
</details>

**Comment by lenaschoenburg** [comment]
The first proposed solution, incrementing sequence numbers on failed flush, is not safe as far as I can tell:

Positions and sequence numbers need to stay in sync. When one resets to a lower value, the other needs to reset too.
This is not guaranteed if a leader can increment the sequence number freely without followers observing this. Consider this scenario:

Starting point:
Leader A exported p(osition)100, s(equence)100.
Follower B knows about p100, s100.

Leader fails to flush a couple times but eventually succeeds. Unfortunately, the follower did not receive updates:
Leader A exported p101, s150.
Follower B knows about p100, s100.

After a leader change to B, it starts exporting from p100,s100. Then:
Leader B exports p101, s101.
Leader B exports p102, s102.
...

Here we would export new positions (102 and following) with sequence numbers that are lower than the sequence number of p101. This break the contract and would cause importers to miss records.

**Comment by remcowesterhoud** [comment]
>Update the sequence number on actor close() if the flush succeed

I don' think this is required. If the `close()` method is called it means we are doing an asynchronous flush. The sequence is already updated at that point:

```java
    } else {
      // If the exporter doesn't flush synchronously then it can update the record counters
      // immediately. If the asynchronous flush fails then it will retry only the flush operation
      // with the records in the pending bulk request.
      recordCounters.updateRecordCounters(record, recordSequence);
    }
```

That leaves it with 2 scenarios:
1. The flush succeeds. We update our last exported position, which will also make the controller aware of the latest sequence numbers. All should be fine.
2. The flush fails. You should be able to see this in the logging via a warning: `log.warn("Failed to flush records before closing exporter.", e);`. If this happens the last exporteed position is not updated. The controller is not aware of the latest sequence. That is fine, because the flush failed and this record is not actually exported. The sequence number should be reused.

**Comment by nicpuppa** [comment]
@remcowesterhoud from the log we can see:

```
Unexpected exception occurred on periodically flushing bulk, will retry later.
.....
Error on exporting record with key 4503600741741953
```

**Comment by lenaschoenburg** [comment]
> If the close() method is called it means we are doing an asynchronous flush. The sequence is already updated at that point

@remcowesterhoud That's not correct, the sequence number is not incremented in case a previous call to `export` tried to flush immediately but `flush` throws an exception, thus preventing the sequence number increment.
