### ISSUE TITLE
Operate loses connection to AWS Opensearch

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24262]
### Describe the bug

When running Operate with AWS Opensearch, it starts well but after a while starts logging exceptions in logs and Operate UI stops responding. (Exception in comment)
```
2024-10-31 13:05:23.419 ERROR 7 --- [ecords_reader_2] i.c.o.s.o.c.s.ZeebeRichOpenSearchClient  : Failed to search index: [zeebe-record-decision]! Reason: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.

java.lang.RuntimeException: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
        at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:204) ~[opensearch-java-2.5.0.jar!/:?]
        at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1302) ~[opensearch-java-2.5.0.jar!/:?]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.unsafeSearch(OpenSearchDocumentOperations.java:239) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.lambda$search$6(OpenSearchDocumentOperations.java:254) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.OpenSearchOperation.safe(OpenSearchOperation.java:48) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:253) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:245) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.read(OpensearchRecordsReader.java:407) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.lambda$readNextBatchBySequence$0(OpensearchRecordsReader.java:270) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.12.7.jar!/:1.12.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.withTimerSearchHits(OpensearchRecordsReader.java:500) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readNextBatchBySequence(OpensearchRecordsReader.java:270) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readNextBatchBySequence(OpensearchRecordsReader.java:393) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readAndScheduleNextBatch(OpensearchRecordsReader.java:180) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readAndScheduleNextBatch(OpensearchRecordsReader.java:159) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.run(OpensearchRecordsReader.java:155) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.10.jar!/:6.1.10]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
        at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:69) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:307) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:188) ~[netty-nio-client-2.25.70.jar!/:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        ... 1 more
Caused by: java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
        at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.timeoutAcquire(HealthCheckedChannelPool.java:77) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.lambda$acquire$0(HealthCheckedChannelPool.java:67) ~[netty-nio-client-2.25.70.jar!/:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        ... 1 more

```

### To Reproduce

1. Create AWS Opensearch instance
2. Run Operate with test data
3. Let it run for some time (couple of hours may be enough)
4. Try to click through Operate UI and observe the logs

### Current behavior

After some time UI hangs (infinitely loading) and logs show a lot of exceptions.

### Expected behavior

Operate runs well and not degrading with the time.

### Environment

AWS Opensearch
- Operate Version: 8.5.7, 8.6.3

### Additional context

Incident channel: https://camunda.slack.com/archives/C07QBPDB2SE

**Comment by sdorokhova** [comment]
```
2024-10-31 13:05:23.419 ERROR 7 --- [ecords_reader_2] i.c.o.s.o.c.s.ZeebeRichOpenSearchClient  : Failed to search index: [zeebe-record-decision]! Reason: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.

java.lang.RuntimeException: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
        at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:204) ~[opensearch-java-2.5.0.jar!/:?]
        at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1302) ~[opensearch-java-2.5.0.jar!/:?]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.unsafeSearch(OpenSearchDocumentOperations.java:239) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.lambda$search$6(OpenSearchDocumentOperations.java:254) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.OpenSearchOperation.safe(OpenSearchOperation.java:48) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:253) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.store.opensearch.client.sync.OpenSearchDocumentOperations.search(OpenSearchDocumentOperations.java:245) ~[operate-schema-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.read(OpensearchRecordsReader.java:407) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.lambda$readNextBatchBySequence$0(OpensearchRecordsReader.java:270) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.12.7.jar!/:1.12.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.withTimerSearchHits(OpensearchRecordsReader.java:500) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readNextBatchBySequence(OpensearchRecordsReader.java:270) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readNextBatchBySequence(OpensearchRecordsReader.java:393) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readAndScheduleNextBatch(OpensearchRecordsReader.java:180) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.readAndScheduleNextBatch(OpensearchRecordsReader.java:159) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at io.camunda.operate.zeebeimport.opensearch.OpensearchRecordsReader.run(OpensearchRecordsReader.java:155) ~[operate-importer-8.5.7.jar!/:8.5.7]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.10.jar!/:6.1.10]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
        at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:69) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:307) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:188) ~[netty-nio-client-2.25.70.jar!/:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        ... 1 more
Caused by: java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
        at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.timeoutAcquire(HealthCheckedChannelPool.java:77) ~[netty-nio-client-2.25.70.jar!/:?]
        at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.lambda$acquire$0(HealthCheckedChannelPool.java:67) ~[netty-nio-client-2.25.70.jar!/:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar!/:4.1.111.Final]
        ... 1 more

```

**Comment by houssain-barouni** [comment]
Hi @ThorbenLindhauer ,
Tasklist archiver implementation is basically the same as Operate. Do you think we need to revert the netty client in Tasklist as well ?

**Comment by ThorbenLindhauer** [comment]
@houssain-barouni yes, I think so. I will get in touch with Marcos.

**Comment by ThorbenLindhauer** [comment]
We will make the change here for Tasklist as well. We need to revert this PR: https://github.com/camunda/tasklist/pull/4008

@houssain-barouni I will co-assign you to the PR review.

**Comment by ThorbenLindhauer** [comment]
Code is in review. I'll leave the ticket in progress until the CI is finished and successful.

**Comment by ThorbenLindhauer** [comment]
Today, I ran the Operate ITs against AWS Opensearch. See the log file attached. I had to cancel the run towards the end as the runtime was exceeding three hours.

Here is my assessment of the test failures int he log:

* DecisionIT
  * Succeeds when run in isolation
* ModifyProcessInstanceOperationZeebeIT.shouldMoveTokenWithAncestor
  * Note: This failed with a request signing error similar to https://github.com/camunda/camunda/issues/24321; however the rootcause seems not to be a missing Content-Length header
  * Succeeds when run in isolation
* BackupControllerIT
  * Test is specific to Elasticsearch (mocks responses of the ES client and verifies ES client interactions)
* io.camunda.operate.webapp.security.es.AuthenticationWithPersistentSessionsIT
  * Test is specific to Elasticsearch (loads only the ES-specific application context classes)
* io.camunda.operate.webapp.security.identity.AuthenticationWithPersistentSessionsIT
  * Test is specific to Elasticsearch (loads only the ES-specific application context classes)
* io.camunda.operate.webapp.security.sso.AuthenticationWithPersistentSessionsIT
  * Test is specific to Elasticsearch (loads only the ES-specific application context classes)
* DMNFlowNodeMetadataZeebeImportIT
  * flow node metadata does not return called decision instance id on Opensearch
  * Raised https://github.com/camunda/camunda/issues/24397

I will proceed with merging the PRs.

[integration-test-run-86.txt](https://github.com/user-attachments/files/17637179/integration-test-run-86.txt)

**Comment by ThorbenLindhauer** [comment]
8.5 and lower PRs are all merged. main and 8.6 are in the merge queue. Will close the ticket once they are successfully merged.

**Comment by ThorbenLindhauer** [comment]
All PRs merged
