### ISSUE TITLE
IncidentQueryTest is flaky

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#24271]
**Summary**

- How often does the test fail? once [here](https://github.com/camunda/camunda/actions/runs/11614274002/attempts/1?pr=24268) so far.
- Does it block your work? 
- Do we suspect that it is a real failure? no

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
❌ shouldFilterByTreePath (Flaky Test): io.camunda.it.client.IncidentQueryTest

org.opentest4j.AssertionFailedError: 

expected: null
 but was: "PI_2251799813685271/FN_taskAIncident/FNI_2251799813685275"
	at io.camunda.it.client.IncidentQueryTest.shouldFilterByTreePath(IncidentQueryTest.java:257)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
<pre>
❌   shouldGetIncidentByKey (Flaky Test): io.camunda.it.client.IncidentQueryTest

org.opentest4j.AssertionFailedError: 
expected: io.camunda.zeebe.client.impl.search.response.IncidentImpl@ca4834ff
but was: io.camunda.zeebe.client.impl.search.response.IncidentImpl@e51e266e
        at io.camunda.it.client.IncidentQueryTest.shouldGetIncidentByKey(IncidentQueryTest.java:86)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre>
</details>

**Hypotheses**

**Logs**

[LOGS](https://drive.google.com/file/d/1vU0Rs3SG2s_iCATwb2LhenwZevDRi6l_/view?usp=drive_link)

**Comment by mustafadagher** [comment]
@ralfpuchert is this something related to your work?

**Comment by nathansandi** [comment]
@mustafadagher  we are not exposing tree path anymore on incident query

https://github.com/camunda/camunda/pull/25791/files#diff-232b091b3ac9194152378fcef1141141fbc28e20a0657c26ae60de3d4e6650ac

As this test is removed as well, I am going to close this issue. 

cc: @tmetzke @ralfpuchert

**Comment by tmetzke** [comment]
This part still prevails, so I'm re-opening this:

```
❌   shouldGetIncidentByKey (Flaky Test): io.camunda.it.client.IncidentQueryTest

org.opentest4j.AssertionFailedError: 
expected: io.camunda.zeebe.client.impl.search.response.IncidentImpl@ca4834ff
but was: io.camunda.zeebe.client.impl.search.response.IncidentImpl@e51e266e
        at io.camunda.it.client.IncidentQueryTest.shouldGetIncidentByKey(IncidentQueryTest.java:86)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by tmetzke** [comment]
The root cause of the flakiness is the incident state, see https://github.com/camunda/camunda/pull/28552#issuecomment-2674265286
