### ISSUE TITLE
ES not coming up after several turn on/off of c8run

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda#24307]
**Describe the issue:**

### Environment (Required on creation)

C8.6.2 Run distro on Mac

### Description (Required on creation; please attach any relevant screenshots, stacktraces, log files, etc. to the ticket)

After running the start.sh and shutdown.sh scripts a few times, it happens that the ES cluster cannot connect to tasklist since it's status is red.

`{
  "cluster_name" : "elasticsearch",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 23,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 0.0
}`

And also the camunda logs shows as if the address is still on use

`Caused by: java.net.BindException: Address already in use
		at java.base/sun.nio.ch.Net.bind0(Native Method) ~[?:?]
		at java.base/sun.nio.ch.Net.bind(Net.java:565) ~[?:?]`

### Steps to reproduce (Required on creation)

1- Go to the C8Run artifact page.
2- Download it/unzip it
3- On the terminal execute the command `./start.sh` and `./shutdown.sh` a few times 

### Observed Behavior (Required on creation)

Notice that the apps are not showing up anymore and the logs start showing the above messages.

### Links

Download link - [here](https://github.com/camunda/camunda/releases/tag/c8run-8.6.0-alpha5)

Was reported - [here](https://camunda.slack.com/archives/C074T8BTTM2/p1725981714995929)

### Breakdown

```[tasklist]
### Pull Requests
```

**Comment by hisImminence** [comment]
As we moved all scritps to go. This issue does not seem to be apparent anymore.
