### ISSUE TITLE
NPE while adding an execution listener to a flow node

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#24348]
**Describe the bug**
A Job/Complete command could not be processed. It looks as if we tried to lookup the BPMN resource, needed to parse it and then failed while adding execution listeners to a flownode.

**To Reproduce**

Not clear.

**Expected behavior**

No error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: expression
	at java.base/java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.EnsureUtil.ensureNotNull(EnsureUtil.java:20) ~[zeebe-util-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.el.impl.FeelExpressionLanguage.parseExpression(FeelExpressionLanguage.java:57) ~[zeebe-expression-language-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.addListenerToFlowNode(ExecutionListenerTransformer.java:33) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.lambda$transform$0(ExecutionListenerTransformer.java:23) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.zeebe.ExecutionListenerTransformer.transform(ExecutionListenerTransformer.java:22) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.lambda$transformExecutionListeners$5(FlowNodeTransformer.java:99) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transformExecutionListeners(FlowNodeTransformer.java:97) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:46) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.FlowNodeTransformer.transform(FlowNodeTransformer.java:24) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:118) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:343) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupPersistenceStateForProcessByKey(DbProcessState.java:569) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getProcessByKeyAndTenant(DbProcessState.java:459) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:496) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.appliers.EventSubProcessInterruptionMarker.markInstanceIfInterrupted(EventSubProcessInterruptionMarker.java:43) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:54) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.appliers.ProcessEventTriggeringApplier.applyState(ProcessEventTriggeringApplier.java:20) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:493) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.common.EventTriggerBehavior.triggeringProcessEvent(EventTriggerBehavior.java:164) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.common.EventHandle.triggeringProcessEvent(EventHandle.java:101) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.common.EventHandle.triggeringProcessEvent(EventHandle.java:152) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.job.JobCompleteProcessor.afterAccept(JobCompleteProcessor.java:82) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.job.JobCompleteProcessor.afterAccept(JobCompleteProcessor.java:27) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:76) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:131) ~[zeebe-workflow-engine-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:375) ~[zeebe-stream-platform-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:285) ~[zeebe-stream-platform-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:244) ~[zeebe-stream-platform-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) [zeebe-scheduler-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.4.jar:8.6.4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.4.jar:8.6.4] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6.4

**Comment by megglos** [comment]
[Listener Type was not specified](https://github.com/camunda/camunda/blob/8.6.4/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/zeebe/ExecutionListenerTransformer.java#L33), this might happen more frequently, especially as it's a new feature.

We need to validate that the type expression is not null.

**Comment by eppdot** [comment]
@mustafadagher any update on this? we should also add labels for affected versions etc. as r/n this does not show in the 8.8 view on the quality board

**Comment by mustafadagher** [comment]
@eppdot I believe this might have been solved already in #27905 (PR:  https://github.com/camunda/camunda/pull/27904)

@lenaschoenburg / @megglos could you confirm that the fix in the PR above was what's needed to overcome this bug?

**Comment by lenaschoenburg** [comment]
Sounds like it but I think you'd know better than I, at this point.
