### ISSUE TITLE
ProcessDefinitionQueryTest is flaky

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#24551]
**Summary**

- How often does the test fail? Once so far
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 198.6 s <<< FAILURE! -- in io.camunda.it.client.ProcessDefinitionQueryTest
Error:  io.camunda.it.client.ProcessDefinitionQueryTest -- Time elapsed: 198.6 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'should deploy processes and import in Operate' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.it.client.ProcessDefinitionQueryTest 
expected: 28
 but was: 7.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.it.client.ProcessDefinitionQueryTest.waitForProcessesToBeDeployed(ProcessDefinitionQueryTest.java:441)
	at io.camunda.it.client.ProcessDefinitionQueryTest.beforeAll(ProcessDefinitionQueryTest.java:71)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: org.opentest4j.AssertionFailedError: 
expected: 28
 but was: 7
	at io.camunda.it.client.ProcessDefinitionQueryTest.lambda$waitForProcessesToBeDeployed$27(ProcessDefinitionQueryTest.java:444)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:[248](https://github.com/camunda/camunda/actions/runs/11740605152/job/32711343039?pr=24320#step:9:249))
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

<details><summary>Failure</summary>
<pre>
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ProcessDefinitionQueryTest.shouldValidateGetProcessForm:426 
expected: 2L
 but was: 1L
Error:  Errors: 
Error:  io.camunda.it.client.ProcessDefinitionQueryTest.null
Error:    Run 1: ProcessDefinitionQueryTest.beforeAll:71->waitForProcessesToBeDeployed:441 ? ConditionTimeout Condition with alias 'should deploy processes and import in Operate' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.it.client.ProcessDefinitionQueryTest 
expected: 14
 but was: 7.
Error:    Run 2: ProcessDefinitionQueryTest.beforeAll:71->waitForProcessesToBeDeployed:441 ? ConditionTimeout Condition with alias 'should deploy processes and import in Operate' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.it.client.ProcessDefinitionQueryTest 
expected: 21
 but was: 7.
Error:    Run 3: ProcessDefinitionQueryTest.beforeAll:71->waitForProcessesToBeDeployed:441 ? ConditionTimeout Condition with alias 'should deploy processes and import in Operate' didn't complete within 3 minutes because assertion condition defined as a Lambda expression in io.camunda.it.client.ProcessDefinitionQueryTest 
expected: 28
 but was: 7.
</pre>
</details>

**Logs**

Link to build: [here](https://github.com/camunda/camunda/actions/runs/11740605152/job/32711343039?pr=24320)

**Comment by cmur2** [comment]
More flakes recently:

* https://github.com/camunda/camunda/actions/runs/13408280550/job/37452401510#step:8:393
* https://github.com/camunda/camunda/actions/runs/13408665366/job/37453610781#step:8:935
* https://github.com/camunda/camunda/actions/runs/13400687759/job/37430628104#step:8:393

This is currently in the Top 3 build failure causes on the merge queue.
