### ISSUE TITLE
NPE during replay when completing process instance

### ISSUE THREAD

**Issue by filipecampos** [camunda/camunda#24819]
**Describe the bug**

In some [benchmarks](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=medic-y-2024-cw-47-a620223a-benchmark-mixed&var-pod=All&var-partition=All&from=now-3h&to=now) an issue was detected: a [NPE in replay](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2024-cw-47-a620223a-benchmark-mixed%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2024-cw-47-a620223a-benchmark-mixed%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22;pinnedLogId=2024-11-18T01:45:03.872919491Z%2Ficsd39nozsvsv02h;cursorTimestamp=2024-11-18T01:45:03.872919491Z;duration=PT12H?inv=1&invt=Abhzsg&project=zeebe-io).

The NPE was trigger after a leader change, and occurred when replaying a `ProcessInstance/ElementCompleting` event
The impact is that the stream processing is completely blocked and the partition is dead. A restart does not recover this. Additionally, it seems likely that this can also cause irreparable data inconsistency because it appears like we re-apply events that have already been applied before. 

More information in this [Slack conversation](https://camunda.slack.com/archives/C05DH1F5TAR/p1731928114390969).

**To Reproduce**
This issue appeared after https://github.com/camunda/camunda/issues/18379 and is probably caused by it.

We can see the NPE during replay and right after a transition to leader.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

[StreamProcessor1](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-11-18T10:54:05.628760272Z;endTime=2024-11-18T14:51:51.229Z;pinnedLogId=2024-11-18T01:45:03.970181388Z%2Fqhvx351bzij6jhyr;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2024-cw-47-a620223a-benchmark-mixed%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2024-cw-47-a620223a-benchmark-mixed%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%0Aseverity%3DERROR%0Aresource.labels.pod_name%3D%22medic-y-2024-cw-47-a620223a-benchmark-mixed-zeebe-0%22%0Atimestamp%3D%222024-11-18T10:54:05.628760272Z%22%0AinsertId%3D%22rxqs83mai1eb1a0v%22;startTime=2024-11-12T14:14:47.324Z?project=zeebe-io)

```
java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=90886472, key=2251799843003542, timestamp=1731927149690, sourceEventPosition=90886471] RecordMetadata{recordType=EVENT, valueType=PROCESS_INSTANCE, intent=ELEMENT_COMPLETING, authorization=UNKNOWN}'
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:170) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
Caused by: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.setState(io.camunda.zeebe.protocol.record.intent.ProcessInstanceIntent)" because "instance" is null
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementCompletingApplier.lambda$applyState$0(ProcessInstanceElementCompletingApplier.java:30) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.instance.DbElementInstanceState.updateInstance(DbElementInstanceState.java:226) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementCompletingApplier.applyState(ProcessInstanceElementCompletingApplier.java:28) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementCompletingApplier.applyState(ProcessInstanceElementCompletingApplier.java:16) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:582) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:102) ~[zeebe-workflow-engine-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:237) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:210) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:109) ~[zeebe-db-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:164) ~[zeebe-stream-platform-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	... 5 more
```
</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.7-SNAPSHOT 
- Configuration:

**Comment by npepinpe** [comment]
When giving a critical severity assessment, please explain a little why that is e.g. impact, no workaround, etc.

**Comment by filipecampos** [comment]
From our analysis, we decided to try to replace `batchSourceEventPosition` with `lastReadRecordPosition` as the `ReplayStateMachine` seems to be counting on monotonically increasing position numbers on the records to be replayed. With the change to `sourceRecordPosition` this is no longer the only valid scenario as we saw a command with position 85 produce a whole batch of records with positions between 87 and 118 and the command with position 86 produced records with position greater than 118. We end up with these latest records having `sourceRecordPosition` 86 and in the previous batch we have records with lower positions but higher values on `sourceRecordPosition`.

**Comment by npepinpe** [comment]
It sounds like we know the issue, but it still doesn't tell me what is the impact on the node/cluster.

- What is the impact (from a user pov) on the cluster?
- Does it/can it recover from this failure?
- How likely is it to happen?

You also mostly describe what we're doing to fix it. Since I wasn't super involved and lack a bit of context, can you also explain conceptually for me what went wrong and how this resolves it?

**Comment by lenaschoenburg** [comment]
>  What is the impact (from a user pov) on the cluster?
    Does it/can it recover from this failure?
    How likely is it to happen?

I covered most of this in the description already: 
> The impact is that the stream processing is completely blocked and the partition is dead. A restart does not recover this. Additionally, it seems likely that this can also cause irreparable data inconsistency because it appears like we re-apply events that have already been applied before.

Likelihood is difficult to tell but probably high given that it showed up immediately in benchmarks.

**Comment by npepinpe** [comment]
Sorry, I didn't know the description had been updated since :sweat_smile:

**Comment by lenaschoenburg** [comment]
Unfortunately, I think we will have to roll back #24136 because the changes appear to be incompatible with how we replay state at the moment and changing this would be a significant refactor, if it is even possible. Here is why:

As @filipecampos already explained, with the changes from #24136 we are now in a situation where the `sourceRecordPosition` of events can skip ahead of the actual processed position. Imagine this log:

```
C position 1 source -1
C position 2 source -1
E position 3 source 1
C position 4 source 1
E position 5 source 4
```

Let's say we have `lastProcessedPosition` 4 and start replaying. We need to skip all events that were already applied when processing command 4. So we skip over event 5 and are now done with replay. But where should we continue processing now? Currently we continue processing at position 4 which means we skip over command 2 which is not valid.

Before our changes the situation would have looked different:

```
C position 1 source -1
C position 2 source -1
E position 3 source 1
C position 4 source 1
E position 5 source 1
```

Here we would have resumed processing after command 1 which is correct.

We could attempt some sort of backtracking (`sourceRecordPosition` 4 is a command that was already processed and was itself caused by command 1 so we need to actually start processing after command 1, not after command 4). But this seems like a risky refactor.

Overall, I think I greatly misunderstood the complexity of setting `sourceRecordPosition` to commands produced during batch processing. I think our current replay and processing state machines are not capable of handling this well.
In the future we could consider refactoring these completely and making the internal bookkeeping of what's processed and what's applied easier to follow and less brittle.

@filipecampos Since the changes are not critical, I'm not sure how to resolve this current bug and I lost confidence that we would not introduce other, less easy to detect, bugs, please revert #24136 :disappointed:
