### ISSUE TITLE
Flaky test CredentialsProviderSelfManagedTest shouldHaveZeebeAuth 

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#24824]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once [here](https://github.com/camunda/camunda/actions/runs/11897299647?pr=24823)
- Does it block your work? no
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
  shouldHaveZeebeAuth: io.camunda.zeebe.spring.client.config.CredentialsProviderSelfManagedTest

expected: {"Authorization"="***;}
 but was: {"Authorization"="***;}
org.opentest4j.AssertionFailedError: 
expected: {"Authorization"=";}
but was: {"Authorization"=";}
at io.camunda.zeebe.spring.client.config.CredentialsProviderSelfManagedTest.shouldHaveZeebeAuth(CredentialsProviderSelfManagedTest.java:108)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by korthout** [comment]
@mustafadagher Please consider this when reporting flaky tests: https://github.com/camunda/camunda/issues/24725#issuecomment-2485148695

**Comment by mustafadagher** [comment]
@korthout Logs can be found [here](https://drive.google.com/drive/folders/1NqO8wnDrFMTsM57wS_IAP8tJ00aTHzUJ)

**Comment by cmur2** [comment]
I also see spurious CI failures in the merge queue to `main` because of the flaky test in this ticket (happens in `java-unit-tests` job), recent examples from yesterday+today:

* https://github.com/camunda/camunda/actions/runs/11910585616/job/33190322451
* https://github.com/camunda/camunda/actions/runs/11910585616/job/33190322451
* https://github.com/camunda/camunda/actions/runs/11904705470/job/33173973699
* https://github.com/camunda/camunda/actions/runs/11895631844/job/33145702007

In all samples I checked from the last days this is the single most prominent failure reason in CI:

![image](https://github.com/user-attachments/assets/179ae53d-4779-426b-b7f5-5dd3af80d86e)

Please prioritize mitigate the CI impact of this (e.g. workaround by skipping the test) before it becomes a problem.

**Comment by mustafadagher** [comment]
@nicpuppa is that something you can take a look at? Thanks!

**Comment by nicpuppa** [comment]
I looked at it on monday, and I wasn't able to reproduce the error locally. Not sure if it make sense to disable the test and look at it with more time @mustafadagher.
I don't have time today, and probably the rest of the week

**Comment by nicpuppa** [comment]
I disabled the test, unassign myself as I don't have time to investigate the test this week

**Comment by cmur2** [comment]
For reference: https://github.com/camunda/camunda/commit/0b2c0794110c4ec79cfde05f2201f8900fa0d9d9 re-enabled the CredentialsProviderSelfManaged test

**Comment by ChrisKujawa** [comment]
Flake https://github.com/camunda/camunda/actions/runs/13942923675/job/39023512422?pr=29582#step:7:6765

**Comment by cmur2** [comment]
Thanks to everyone participating in tracking down and fixing this long-standing issue! 🙇🏼
