### ISSUE TITLE
Exporter does not recover from not finding snapshot position

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#25072]
**Describe the bug**

Upon transition the cluster is not able to recover snapshot position:

```
java.lang.IllegalStateException: Expected to find event with the snapshot position -1 in log stream, but nothing was found. Failed to recover 'Exporter-3'.
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.startActiveExportingFrom(ExporterDirector.java:567) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$17(ExporterDirector.java:551) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.AllCompletedFutureConsumer.accept(AllCompletedFutureConsumer.java:33) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.AllCompletedFutureConsumer.accept(AllCompletedFutureConsumer.java:13) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
```
This leads to a loop of shuting down the exporter, then the partition and repeatedly failing to set the partition as inactive.
```
Error during transition preparation: Expected to find event with the snapshot position -1 in log stream, but nothing was found. Failed to recover 'Exporter-3'.
```

From the logs it seems that issue was resolved form restarting the brokers.

[LOGS](https://drive.google.com/file/d/1jZo_esgAWm62gXYC8WABTpjD9nFPy39I/view?usp=drive_link)

**To Reproduce**

Unknown how to reproduce.

**Expected behavior**

**Log/Stacktrace**

**Environment:**
- OS: 
- Zeebe Version: 8.7.0-SNAPSHOT
- Configuration:

**Comment by rodrigo-lourenco-lopes** [comment]
Also seen in a different [cluster](https://console.cloud.google.com/errors/detail/COPBhdf8_ri--gE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbiLPw&project=camunda-saas-int-chaos) in Saas int Chaos.

**Comment by npepinpe** [comment]
-1 means there is no snapshot actually (or used to anyway). I lack context to judge if this was some test, or unexpected. Based on the stage it was deployed, I assume unexpected.

Did we keep the snapshot/logs? I guess this is too old now and we lost everything. I will put it in the backlog until it comes back, as we can't do much without the state. Next time, try and grab the partition data.
