### ISSUE TITLE
Spring Client stream warning

### ISSUE THREAD

**Issue by goenkale** [camunda/camunda#25535]
**Description**

Getting this warning over and over after running a Spring boot application for a while (40s or so): 

**2024-12-03T11:14:00.731+01:00  WARN 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] io.camunda.client.job.worker             : Failed to stream jobs of type 'trackOrderStatus' to worker 'orderHandler#handleOrderStatusJob' io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 504**

I tested the same application with Java client and I can't reproduce it (even forcing a job _.streamEnabled(true)_).

It seems that the Spring Client has the job stream enabled by default. 

The "warning" stopped after manually adding it to the .yaml file:

```
camunda:
  client:
    mode: saas
    auth:
      client-id: ***
      client-secret: ***
    cluster-id: ***
    region: ***
    zeebe:
      defaults:
        stream-enabled: false
```

The code is available here:
* Java: https://github.com/camunda-academy/c8-develop-workers-java-lab
* Spring: https://github.com/camunda-academy/c8-develop-workers-spring-lab

```
2024-12-03T11:13:21.082+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.camunda.academy.handler.OrderHandler   : Getting order (9b6cf8d) for job: 6755399515704647
2024-12-03T11:13:21.082+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.camunda.academy.handler.OrderHandler   : Order status tracked successfully for job: 6755399515704647   
2024-12-03T11:13:21.094+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.academy.handler.PackItemsHandler     : Handling job: 6755399515704699 for packing items
2024-12-03T11:13:21.098+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.services.TrackingOrderService      : Packing items for job: 6755399515704699
2024-12-03T11:13:21.098+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.academy.handler.PackItemsHandler     : Items packed successfully for job: 6755399515704699
2024-12-03T11:13:21.297+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.handler.ProcessPaymentHandler      : Handling job: 6755399515704697 for process payment 
2024-12-03T11:13:21.297+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.services.TrackingOrderService      : Processing payment for job: 6755399515704697
2024-12-03T11:13:21.297+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.handler.ProcessPaymentHandler      : Process payment successfully for job: 6755399515704697        
2024-12-03T11:13:21.509+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.academy.handler.PackItemsHandler     : Handling job: 6755399515704733 for packing items
2024-12-03T11:13:21.511+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.services.TrackingOrderService      : Packing items for job: 6755399515704733
2024-12-03T11:13:21.511+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.academy.handler.PackItemsHandler     : Items packed successfully for job: 6755399515704733
2024-12-03T11:13:21.713+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.handler.ProcessPaymentHandler      : Handling job: 6755399515704731 for process payment 
2024-12-03T11:13:21.713+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.services.TrackingOrderService      : Processing payment for job: 6755399515704731
2024-12-03T11:13:21.720+01:00  INFO 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] c.c.a.handler.ProcessPaymentHandler      : Process payment successfully for job: 6755399515704731        
2024-12-03T11:14:00.731+01:00  WARN 26060 --- [c8-develop-workers-spring-lab] [pool-1-thread-1] io.camunda.client.job.worker             : Failed to stream jobs of type 'trackOrderStatus' to worker 'orderHandler#handleOrderStatusJob'

io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 504
invalid content-type: text/html
headers: Metadata(:status=504,date=Tue, 03 Dec 2024 10:14:00 GMT,content-type=text/html,strict-transport-security=max-age=63072000; includeSubDomains,content-length=160)
DATA-----------------------------
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

        at io.grpc.Status.asRuntimeException(Status.java:532) ~[grpc-api-1.68.1.jar:1.68.1]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.68.1.jar:1.68.1]
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.68.1.jar:1.68.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.68.1.jar:1.68.1]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]`
```
**Related**
[SUPPORT-25369](https://jira.camunda.com/browse/SUPPORT-25369)
[SUPPORT-26528](https://jira.camunda.com/browse/SUPPORT-26528)

**Comment by npepinpe** [comment]
ZDP triage: nothing for us, possibly something for the ZPA team.

**Comment by falko** [comment]
According to discussions in [SUPPORT-22331](https://jira.camunda.com/browse/SUPPORT-22331?focusedCommentId=353992&atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258Y29tbWVudA%3D%3D#comment-353992) and [SUPPORT-22069](https://jira.camunda.com/browse/SUPPORT-22069?focusedCommentId=351867&atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258Y29tbWVudA%3D%3D#comment-351867), this warning could indicate that an intermediary ingress controller or proxy server is terminating idle streaming connections thinking they stale. The log message quoted above also shows `nginx` to be involved. In this case, impact of the issue is just noisy logging, and there are no issues with the underlying cluster.

Workaround include:
- Increasing connection timeouts in the ingress controller or proxy server
- Decrease property camunda.client.zeebe.default.stream-timeout

Nevertheless, it would be helpful if the raw gRPC error message would be wrapped in a Zeebe Client exception with a little more explanation of what is going on and what is the impact. I have seen several prospects get concerned and starting to debug their client.

Also related:
[SUPPORT-23866](https://jira.camunda.com/browse/SUPPORT-23866)

**Comment by megglos** [comment]
When applying
> Decrease property camunda.client.zeebe.default.stream-timeout

to be lower than the nginx timeout, users also get noise in the logs as reported by https://github.com/camunda/camunda/issues/31577
e.g.
```
WARN  io.camunda.zeebe.client.job.worker - Failed to stream jobs of type 'type' to worker 'type#handleTask'
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: CallOptions deadline exceeded after 3299.999946600s.
```
