### ISSUE TITLE
Cannot archive if a shard is unhealthy

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#25539]
**Describe the bug**

Archiving does not work with the new exporter is any of the shards are currently unhealthy. We had a case where this happened because ES went out of disk space, and when it restarted, it failed to start and would shut down because it cannot load it's persistent cache (due to out of disk space).

```
[2024-12-03T12:16:35,514][INFO ][o.e.n.Node               ] [elastic-0] starting ...
[2024-12-03T12:16:35,531][ERROR][o.e.b.Elasticsearch      ] [elastic-0] fatal exception while booting Elasticsearch java.io.UncheckedIOException: Failed to load persistent cache
	at org.elasticsearch.searchablesnapshots@8.15.3/org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache.repopulateCache(PersistentCache.java:272)
	at org.elasticsearch.searchablesnapshots@8.15.3/org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.doStart(CacheService.java:196)
	at org.elasticsearch.server@8.15.3/org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.server@8.15.3/org.elasticsearch.node.Node.start(Node.java:285)
	at org.elasticsearch.server@8.15.3/org.elasticsearch.bootstrap.Elasticsearch.start(Elasticsearch.java:457)
	at org.elasticsearch.server@8.15.3/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:257)
	at org.elasticsearch.server@8.15.3/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:76)
Caused by: java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:400)
	at java.base/java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.store.OutputStreamIndexOutput.getChecksum(OutputStreamIndexOutput.java:104)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.codecs.CodecUtil.writeCRC(CodecUtil.java:644)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.codecs.CodecUtil.writeFooter(CodecUtil.java:412)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.SegmentInfos.write(SegmentInfos.java:691)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.SegmentInfos.write(SegmentInfos.java:569)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.SegmentInfos.prepareCommit(SegmentInfos.java:912)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5647)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3790)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:4131)
	at org.apache.lucene.core@9.11.1/org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:4093)
	at org.elasticsearch.searchablesnapshots@8.15.3/org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache$CacheIndexWriter.commit(PersistentCache.java:525)
	at org.elasticsearch.searchablesnapshots@8.15.3/org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache.repopulateCache(PersistentCache.java:261)
	... 7 more

ERROR: Elasticsearch did not exit normally - check the logs at /opt/bitnami/elasticsearch/logs/elastic.log
[2024-12-03T12:16:35,538][INFO ][o.e.n.Node               ] [elastic-0] stopping ...
[2024-12-03T12:16:35,547][INFO ][o.e.n.Node               ] [elastic-0] stopped
[2024-12-03T12:16:35,547][INFO ][o.e.n.Node               ] [elastic-0] closing ...
[2024-12-03T12:16:35,557][INFO ][o.e.n.Node               ] [elastic-0] closed
```

This means the shard is never assigned until there is more disk space, and archiving does not work, leading to more disk usage for other nodes as well.

**To Reproduce**

1. Create a cluster with the new Camunda Exporter.
1. Generate load quickly (<1h) until one node is out of disk space.
1. Restart the node.

Check that at least one shard for process instance related indices is unhealthy. This will prevent reindexing, which archiving relies on.

**Expected behavior**

1. We have a better error message describing what is happening. Right now, the error simply says we're missing some shards, and nothing else. Looking at ES is what led to diagnose this.
1. Log errors less often. We logged this error hundreds of thousands of time now in a short time, we can probably do better.

And if anyone has any other workaround, I'm all ears.

**Comment by sdorokhova** [comment]
I failed to reproduce the disk overflow case locally, but if I manually make dated index as read-only, I observe such log coming from archiver:
```


18:59:39.106 [] [exporter-camunda-p1-tasks-1] [] ERROR io.camunda.zeebe.broker.exporter.camunda - Error occurred while performing a background task; operation will be retried
java.util.concurrent.CompletionException: co.elastic.clients.transport.TransportException: node: http://localhost:9200/, status: 403, [es/reindex] Failed to decode error response, check exception cause for additional details
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: co.elastic.clients.transport.TransportException: node: http://localhost:9200/, status: 403, [es/reindex] Failed to decode error response, check exception cause for additional details
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:357) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.lambda$performRequestAsync$0(ElasticsearchTransportBase.java:211) ~[elasticsearch-java-8.13.4.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient$1.onSuccess(RestClientHttpClient.java:115) ~[elasticsearch-java-8.13.4.jar:?]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:680) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:403) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:397) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar:4.4.16]
	... 1 more
Caused by: co.elastic.clients.json.UnexpectedJsonEventException: Unexpected JSON event 'VALUE_NUMBER' instead of 'KEY_NAME'
	at co.elastic.clients.json.JsonpUtils.expectEvent(JsonpUtils.java:106) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.endpoints.EndpointBase$1.deserialize(EndpointBase.java:150) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.endpoints.EndpointBase$1.deserialize(EndpointBase.java:144) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:77) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:343) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.lambda$performRequestAsync$0(ElasticsearchTransportBase.java:211) ~[elasticsearch-java-8.13.4.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient$1.onSuccess(RestClientHttpClient.java:115) ~[elasticsearch-java-8.13.4.jar:?]
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:680) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:403) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:397) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) ~[httpcore-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar:4.4.16]
	... 1 more
```

This looks like parsing error indices Elasticsearch client, I posted it on Elastic forum to clarify this.
But another problems with this failure that are also mentioned in the issue description are:
1. It's not clear from the log which exactly background task has failed.
2. The error is logged many times polluting the logs.

**Comment by npepinpe** [comment]
https://github.com/camunda/camunda/issues/28158

Rodrigo was assigned to it, but he's on FTO for 2 weeks, so it might make sense to re-assign.

**Comment by sdorokhova** [comment]
@npepinpe thanks for the info! I actually created [the PR](https://github.com/camunda/camunda/pull/28682) to log which task failed and also log reoccurring exceptions not so frequently. PR is still in draft, I do some more testing there.

I can then take over the other task also.
