### ISSUE TITLE
Background tasks logs intermediate connection issues as errors

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda#25631]
**Description**

We can see in SaaS that a lot of intermediate connections issues are logged as errors, causing to flood the error reporting.

Expectation would be here to log this as warning, as the request/connection is retried (based on the log statement at least).

[Error](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CL7rsaOb9OHu0QE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%22db344356-bad0-4b67-9334-92eed8f183d1-zeebe%22;pinnedLogId=2024-12-04T16:11:15.169595315Z%2Fk7doa0vxof15qhog;cursorTimestamp=2024-12-04T16:11:15.169595315Z;startTime=2024-12-04T15:42:19.537Z;endTime=2024-12-04T16:42:19.537Z?inv=1&invt=AbjSiQ&project=camunda-saas-int):

```
java.util.concurrent.CompletionException: java.net.ConnectException: Timeout connecting to [elasticsearch-es-http/10.44.45.56:9200]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Timeout connecting to [elasticsearch-es-http/10.44.45.56:9200]
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:169) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:630) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:896) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:198) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:213) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:158) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.5.jar:4.1.5]
	... 1 more
```

Error group: 

- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSiQ&project=camunda-saas-int
- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSiQ&project=camunda-saas-int-chaos

**Comment by korthout** [comment]
Some more errors:
- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSyQ&project=camunda-saas-int-chaos
- https://console.cloud.google.com/errors/detail/CLfwnJ7N8_yEpgE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSyg&project=zeebe-io
- https://console.cloud.google.com/errors/detail/CM2wspjy-tLbdg;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSyg&project=zeebe-io
- https://console.cloud.google.com/errors/detail/CPLP-r7xjfu74QE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSyg&project=zeebe-io
- https://console.cloud.google.com/errors/detail/CIvg3eLarPXlew;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjSyg&project=zeebe-io

**Comment by ana-vinogradova-camunda** [comment]
Some more:

- https://console.cloud.google.com/errors/detail/CL7rsaOb9OHu0QE;service=zeebe;time=P7D;locations=global?inv=1&invt=Abj60g&project=camunda-saas-dev

**Comment by koevskinikola** [comment]
Got another one [here (SaaS dev)](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.cluster_name%3D%22worker-2%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%2205e7dcc7-28a0-43d2-bc12-b22e1e947447-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-north1%22;pinnedLogId=2024-12-16T13:50:52.197517324Z%2Fb8y0oqhmu8u7vr86;cursorTimestamp=2024-12-16T13:51:01.273939561Z;startTime=2024-12-16T13:21:22.197Z;endTime=2024-12-16T14:21:22.197Z?inv=1&invt=AbkWuw&project=camunda-saas-dev).
