### ISSUE TITLE
RuntimeException: Expected to activate jobs of type '..', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#25806]
**Describe the bug**

[This error](https://console.cloud.google.com/errors/detail/CIWyxZzWobCCPw;service=zeebe;time=P1D;locations=global?inv=1&invt=AbjvWw&project=camunda-cloud-240911) was reported multiple times on SaaS: `Expected to handle REST API request, but an unexpected error occurred`

**To Reproduce**

**Expected behavior**

* On backpressure (RESOURCE_EXHAUSTED) the REST API should return a 503 status code instead of 500 or 429
  * the gateway needs to handle this case gracefully and log it as an error
* REST API Docs need to be updated to make transparent that a 503 with the cause RESOURCE_EXHAUSTED can occur and what it means (backoff and eventually retry)

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Expected to activate jobs of type '[redacted]', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.

at io.camunda.zeebe.gateway.impl.job.LongPollingActivateJobsHandler.lambda$handleNoReceivedJobsFromAllPartitions$9 ( io/camunda.zeebe.gateway.impl.job/LongPollingActivateJobsHandler.java:225 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:83 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
Recent samples Learn more 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6.5
- [Logs](https://cloudlogging.app.goo.gl/3gzgtvPDZ7yLBc8w6)

SUPPORT CASE: [SUPPORT-24274](https://jira.camunda.com/browse/SUPPORT-24274)

**Comment by korthout** [comment]
I choose not to store an export of the logs, as I don't think they add anything useful (they are all unrelated).

**Comment by berkaycanbc** [comment]
Related support [channel](https://camunda.slack.com/archives/C0931DWV42D)

**Comment by berkaycanbc** [comment]
@npepinpe bringing the issue to your radar as one of the customers facing with it. I still think it is low severity as no significant impact on components but might worth re-assessing the priority.

**Comment by megglos** [comment]
For a user this error actually results in HTTP 500s, is it intended to use 500 here indeed? It's actually nothing unexpected and not really an error but expected behavior on overload, so would rather a 503 fit? see
```
[08:34:39.811] ERROR (14000): Response code 500 (Internal Server Error) (request to https://host/zeebe/v2/jobs/activation). {"type":"about:blank","title":"java.lang.RuntimeException","status":500,"detail":"Unexpected error occurred during the request processing: Expected to activate jobs of type 'type', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/zeebe/v2/jobs/activation"}
    err: {
      "type": "HTTPError",
      "message": "Response code 500 (Internal Server Error) (request to https://host/zeebe/v2/jobs/activation). {\"type\":\"about:blank\",\"title\":\"java.lang.RuntimeException\",\"status\":500,\"detail\":\"Unexpected error occurred during the request processing: Expected to activate jobs of type 'type', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.\",\"instance\":\"/zeebe/v2/jobs/activation\"}",
      "stack":
          HTTPError: Response code 500 (Internal Server Error) (request to https://host/zeebe/v2/jobs/activation). {"type":"about:blank","title":"java.lang.RuntimeException","status":500,"detail":"Unexpected error occurred during the request processing: Expected to activate jobs of type 'type', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/zeebe/v2/jobs/activation"}
              at <anonymous> (C:\Users\user\git_local\connector-runtime\node_modules\.pnpm\@camunda8+sdk@8.7.17\node_modules\@camunda8\sdk\src\lib\GotHooks.ts:57:12)
              at Request._error (C:\Users\user\git_local\connector-runtime\node_modules\.pnpm\got@11.8.6\node_modules\got\dist\source\core\index.js:1198:31)
              at C:\Users\user\git_local\connector-runtime\node_modules\.pnpm\got@11.8.6\node_modules\got\dist\source\core\index.js:1284:23
              at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      "name": "HTTPError",
      "code": "ERR_NON_2XX_3XX_RESPONSE",
      "timings": {
        "start": 1750314878053,
        "socket": 1750314878053,
        "lookup": 1750314878053,
        "connect": 1750314878053,
        "secureConnect": 1750314878053,
        "upload": 1750314878054,
        "response": 1750314879809,
        "end": 1750314879810,
        "phases": {
          "wait": 0,
          "dns": 0,
          "tcp": 0,
          "tls": 0,
          "request": 1,
          "firstByte": 1755,
          "download": 1,
          "total": 1757
        }
      },
      "statusCode": 500,
      "source": [
        "Error",
        "    at Array.<anonymous> (C:\\Users\\user\\git_local\\connector-runtime\\node_modules\\.pnpm\\got@11.8.6\\node_modules\\got\\dist\\source\\create.js:67:24)",
        "    at iterateHandlers (C:\\Users\\user\\git_local\\connector-runtime\\node_modules\\.pnpm\\got@11.8.6\\node_modules\\got\\dist\\source\\create.js:89:50)",
        "    at got (C:\\Users\\user\\git_local\\connector-runtime\\node_modules\\.pnpm\\got@11.8.6\\node_modules\\got\\dist\\source\\create.js:117:20)",
        "    at <anonymous> (C:\\Users\\user\\git_local\\connector-runtime\\node_modules\\.pnpm\\@camunda8+sdk@8.7.17\\node_modules\\@camunda8\\sdk\\src\\c8\\lib\\CamundaRestClient.ts:1547:18)"
      ]
    }
```

**Comment by npepinpe** [comment]
No, in fact it doesn't sound like a 5xx at all is expected.

**Comment by megglos** [comment]
@npepinpe what's best fitting from your perspective? Rather a 429 - Too Many requests? On the other hand backpressure can be caused by internal processing load not directly related to the amount of requests by the client. Still the behavior we expect is similar, retry eventually while backing off.

Looking at the API docs, [we have 500 documented though](https://docs.camunda.io/docs/apis-tools/camunda-api-rest/specifications/activate-jobs/) for all cases when a request couldn't be processed.

**Comment by npepinpe** [comment]
Honestly, 500s should be exceptional. I would expect in most cases we can map them to a proper meaningful error. Technically even in your case, it's somewhat related to clients, even if it may not be related to client who just sent the request - but load primarily comes from clients interacting with the cluster, no? I know there are some edge cases (e.g. 1,000,000 timers triggering all at once)...

Anyway, it's semantics. I would still not expect 500s, so 503 would be OK as it indicates the request may be retried - 500 is unclear.

**Comment by npepinpe** [comment]
Is this reported on the client or server? If on the client, @megglos can you prio this? And if on the server, that would be a core features issue, no?

**Comment by megglos** [comment]
@npepinpe the log I shared is from the nodeJs SDK, Josh created https://github.com/camunda/camunda-8-js-sdk/issues/509 to limit the noise in such situations by handling the 500.

This issue would be about the server side logs in this situation.

**Comment by jwulf** [comment]
**Update**: 429 is already returned by at least one endpoint on backpressure. For consistency, 429. See https://github.com/camunda/camunda/issues/25806#issuecomment-3077042004

_[Old comment content:]_

A 503 response from the server is preferable in my case. 

With a 503 response, I can do a blanket backoff-retry in the SDK. 

With 500, it is non-trivial for me to discriminate whether or not to retry based on the error message text.

**Comment by jwulf** [comment]
It seems that the v2/signals/broadcast endpoint already returns 429 on backpressure, so we should be consistent with that:

```
HTTPError: Response code 429 (Too Many Requests) (POST ***/v2/signals/broadcast). 
{"type":"about:blank","title":"RESOURCE_EXHAUSTED","status":429,
"detail":"Failed to write client request to partition '2', because the request limit is exhausted.",
"instance":"/b18e8686-c393-4a4f-afe1-13cb4fbedeab/v2/signals/broadcast"}.
```

**Comment by megglos** [comment]
In overall I would conclude comparing [429](https://developer.mozilla.org/de/docs/Web/HTTP/Reference/Status/429) and [503](https://developer.mozilla.org/de/docs/Web/HTTP/Reference/Status/503), that 503 is the better fit. As engine load does not directly correlate with user requests but can be caused by internal load only, thus a single user request may hit backpressure already.

Edit:
Citing the mozilla guide on 503
>Dropping incoming requests creates backpressure that prevents the server's compute resources from being exhausted, avoiding more severe failures. If requests from specific clients are being restricted due to [rate limiting](https://developer.mozilla.org/en-US/docs/Glossary/Rate_limit), the appropriate response is [429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/429).

**Comment by megglos** [comment]
Turns out we have 429 consistently now thanks to [this change](https://github.com/camunda/camunda/pull/35207/files#diff-2ec9442dd0fbae50e4b038bc7aaa5bc50c036f3030368cbe65b398b2c5b13c5eR80) by Tobi from last week :D

**Comment by megglos** [comment]
@tmetzke since you introduced the usage of 429 for RESOURCE_EXHAUSTED, do you have a different perspective on [this](https://github.com/camunda/camunda/issues/25806#issuecomment-3083319486) argumentation towards 503?

**Comment by tmetzke** [comment]
503 looks fine to me, yeah, your perspective makes sense 👍 Good thing it's a lot easier now to change this centrally 😄

**Comment by megglos** [comment]
> 503 looks fine to me, yeah, your perspective makes sense 👍 Good thing it's a lot easier now to change this centrally 😄

yeah it was a very nice surprise to find that you already improved the error mapping!
We were actually confused first how we could observe 500s while there was central mapping logic to 429 already 😆 until we realized this was just commited a week ago.

**Comment by jwulf** [comment]
@npepinpe necro-posting, I know. 

But from a client SDK perspective — if the server won't start because of failed partitions, the service returns 503. 

If the client SDK is coded to back off and retry on 503, it will never throw an error saying "_Hey, this service is down_", prompting a developer to go look at the server logs. 

If we use 429 to signal backpressure, then I can transparently retry in a backpressure scenario, while surfacing an error for "_Hey, the server has actually melted down_".

**Comment by npepinpe** [comment]
I'm fine with either, my original complain was that a 500 is just wrong, it's not an internal server error.

I'll let you and Meggle decide on what's best.

**Comment by megglos** [comment]
Backporting to 8.7 was missed.

On 8.8 we have a conflict now as 503 as it is returned in different cases:
* partitions are unhealthy
* backpressure
* cluster not started yet (needs to be validated) - e.g. gateway running but broker not
* SaaS cluster deleted? (needs to be validated)

Except the last, these are temporary conditions as well though. 

In GRPC we have two different codes:
* RESOURCE_EXHAUSTED for backpressure
* UNAVAILABLE for e.g. broker down

One alternativ e would be to:
* use 504 for Gateway not reaching broker, e.g. broker down
* use 503 for backpressure

**Comment by jwulf** [comment]
Essentially, we really need differential signals for:

1. Backpressure: an expected and frequently encountered (I can reliably trigger it in simple integration tests) characteristic of the system with a well-defined client behaviour - transparently backoff and retry. This doesn't need to be surfaced in many cases, it can just happen automagically allowing the system to respond to the signal in a distributed fashion at run-time.
2. Service outage: an unexpected service interruption. This should be treated differently in terms of logging (user awareness) and benefits from allowing users to define different behaviour. 

We can differentiate based on text, but a more stable signal is using different status codes.

**Comment by jwulf** [comment]
On 8.8.0, the broker returns _both_ 500 and 503 in backpressure. 

```
HttpSdkError: INTERNAL
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { 
  status: 500, 
  operationId: 'activateJobs', 
  title: 'INTERNAL', 
  detail: 'Unexpected error occurred during the request processing: Expected to activate jobs of type \'test-job\', but no jobs available and at least one broker returned \'RESOURCE_EXHAUSTED\'. Please try again later.', 
  instance: '/v2/jobs/activation' 
}
This error originated in "camundacon/backpressure/backpressure.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
HttpSdkError: RESOURCE_EXHAUSTED
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { 
  status: 503, 
  operationId: 'createProcessInstance', 
  title: 'RESOURCE_EXHAUSTED', 
  detail: 'Failed to write client request to partition \'1\', because the request limit is exhausted.', 
  instance: '/v2/process-instances' 
}
This error originated in "camundacon/backpressure/backpressure.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
```

So the `activateJobs` request returns 500, and the `createProcessInstance` returns 503.

We need a stable signal for "_The system is under load and cannot process your request. This is recoverable in most cases if you give me some space — please back off to reduce distributed system load_" (proposed: 429) versus:
-  "_There is a bug in our system implementation and retrying is not going to help, contact support_" (500); and 
- "_The system has gone away, the broker may have crashed. Trigger an alert_." (503)

For CamundaCon, I'm using this retry logic in the SDK: 

```typescript
if (status === 429) return { retryable: true, reason: 'http-429' }; // always retry 429
const title = (err as any).title || (err as any).response?.data?.title;
const detail = (err as any).detail || (err as any).response?.data?.detail;
if (status === 503) {
  if (title === 'RESOURCE_EXHAUSTED') return { retryable: true, reason: 'backpressure-503' };
  return { retryable: false, reason: 'http-503-non-backpressure' };
}
if (status === 500) {
  if (typeof detail === 'string' && /RESOURCE_EXHAUSTED/.test(detail)) {
    return { retryable: true, reason: 'backpressure-500-detail' };
  }
  return { retryable: false, reason: 'http-500' };
}
```

**Comment by jwulf** [comment]
We might be too late to change this, but we should be aware of the design implications. 

Making the back pressure signal split across codes, and sharing those codes with other non-retryable errors means that every client must implement complex arbitrary logic to implement back pressure management. 

When we have a first-class concept, instantiating it with a coherent first-class surface makes it tractable to generated solutions.

**Comment by megglos** [comment]
I looked into this and found that while the [previous change ](https://github.com/camunda/camunda/pull/35586)converted all existing 429s to 503, it did not affect the 500 returned by exclusively the job activation REST endpoint on backpressure.

The cause is, that for Job Activation Long polling there is an additional layer for error response mapping that just throws a RuntimeException in case any broker signaled backpressure. See here https://github.com/camunda/camunda/blob/main/dist/src/main/java/io/camunda/application/commons/job/JobHandlerConfiguration.java#L92 

The whole picture is the following:
* 8.6/8.7 return 429 for all other endpoints on backpressure, for job activation it's a 500
* 8.8 returns 503 for all other endpoints on backpressure, for job activation it's a 500

I would thus propose:
* let's not change the 429 to 503 for 8.6/8.7 => that's changing behavior and while 429 was considered not appropriate let's only do that change with 8.8+ and not backport it
* let's do the following:
  * fix the 500 on job activation to 429 for 8.6/8.7
  * fix the 500 on job activation to a 503 for 8.8+

**Comment by megglos** [comment]
@jwulf with https://github.com/camunda/camunda/pull/39985 the job activation endpoint will return a **503 for 8.8** with the following body:
```
{"type":"about:blank","title":"RESOURCE_EXHAUSTED","status":503,"detail":"Expected to activate jobs of type 'test', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/v2/jobs/activation"}
```
This will be fixed in 8.8.3.

While previously for 8.8 (8.8.0-8.8.2) it was a 500 with the following body:
```
{"type":"about:blank","title":"INTERNAL","status":500,"detail":"Unexpected error occurred during the request processing: Expected to activate jobs of type 'test', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/v2/jobs/activation"}
```

So both have in common that the `detail` contains `Expected to activate jobs of type 'test', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.`

**Comment by megglos** [comment]
In 8.6/8.7 the error returned for job activation should look like this:
```
{"type":"about:blank","title":"java.lang.RuntimeException","status":500,"detail":"Unexpected error occurred during the request processing: Expected to activate jobs of type 'test', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/zeebe/v2/jobs/activation"}
```

and will change with the fix backported in a future patch to
```
{"type":"about:blank","title":"RESOURCE_EXHAUSTED","status":429,"detail":"Expected to activate jobs of type 'test', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later.","instance":"/v2/jobs/activation"}
```

**Comment by megglos** [comment]
@jwulf as aligned:
Summary:
8.8.:
* (8.8.0-8.8.2) we need to handle 500 with the `detail` containing `RESOURCE_EXHAUSTED` as backpressure
* we need to handle 503 with the `title=RESOURCE_EXHAUSTED`  as backpressure

8.6/8.7:
* (8.6.0-8.6.29 & 8.7.0-8.7.16) we need to handle 500 with the `detail` containing `RESOURCE_EXHAUSTED` as backpressure
* we need to handle 429 with the `title=RESOURCE_EXHAUSTED`  as backpressure

**Comment by tmetzke** [comment]
@megglos, just realized that we should also adjust the [OpenAPI description](https://github.com/camunda/camunda/blob/e7c1d5d2b21383bd7a0ac7d08f2126c4e9c10041/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L159) related to this for 500 responses. It can return to a simple `ref` to the internal error component we have.

**Comment by megglos** [comment]
Oh wow we even documented the bug 😆 [it's already referencing the actually expected 503](https://github.com/camunda/camunda/blob/e7c1d5d2b21383bd7a0ac7d08f2126c4e9c10041/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L159) as well though, ~~so I would just go about removing the 500 but only on main as on 8.8 (8.8.0-8.8.2) you will get the 500 ^^~~ now I think I got you, the 500 can stay as it can occur due to other unhandled issues, thus going for:
```
        "500":
          $ref: "#/components/responses/InternalServerError"
```
to remove the relation to backpressure.
