### ISSUE TITLE
ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#25812]
**Describe the bug**

https://console.cloud.google.com/errors/detail/CMjsyJf_4uLtkAE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

https://console.cloud.google.com/errors/detail/COGAtdrpsfPDxgE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvZQ&project=camunda-saas-int-chaos

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Stacktrace</summary>
<p>

<pre>
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists

at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse ( co/elastic.clients.transport/ElasticsearchTransportBase.java:345 )
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest ( co/elastic.clients.transport/ElasticsearchTransportBase.java:147 )
at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create ( co/elastic.clients.elasticsearch.indices/ElasticsearchIndicesClient.java:277 )
at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex ( io/camunda.exporter.schema.elasticsearch/ElasticsearchEngineClient.java:65 )
at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndexTemplates$3 ( io/camunda.exporter.schema/SchemaManager.java:127 )
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept
at java.util.stream.ReferencePipeline$2$1.accept
at java.util.Iterator.forEachRemaining
at java.util.Spliterators$IteratorSpliterator.forEachRemaining
at java.util.stream.AbstractPipeline.copyInto
at java.util.stream.AbstractPipeline.wrapAndCopyInto
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential
at java.util.stream.AbstractPipeline.evaluate
at java.util.stream.ReferencePipeline.forEach
at io.camunda.exporter.schema.SchemaManager.initialiseIndexTemplates ( io/camunda.exporter.schema/SchemaManager.java:118 )
at io.camunda.exporter.schema.SchemaManager.initialiseResources ( io/camunda.exporter.schema/SchemaManager.java:75 )
at io.camunda.exporter.schema.SchemaManager.startup ( io/camunda.exporter.schema/SchemaManager.java:51 )
at io.camunda.exporter.CamundaExporter.open ( io/camunda.exporter/CamundaExporter.java:117 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0 ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:118 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:59 )
at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader ( io/camunda.zeebe.util.jar/ThreadContextUtil.java:35 )
at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter ( io/camunda.zeebe.broker.exporter.stream/ExporterContainer.java:117 )
at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16 ( io/camunda.zeebe.broker.exporter.stream/ExporterDirector.java:532 )
at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run ( io/camunda.zeebe.scheduler.retry/BackOffRetryStrategy.java:51 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:85 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:42 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
</pre>

</p>
</details> 

<details><summary>Stacktrace</summary>
<p>

<pre>
 co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/indices.create] failed: [resource_already_exists_exception] index [operate-sequence-flow-8.3.0_/mi8AWfmuQWqAM1k79lkdPg] already exists
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.create(ElasticsearchIndicesClient.java:277) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.exporter.schema.elasticsearch.ElasticsearchEngineClient.createIndex(ElasticsearchEngineClient.java:65) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.lambda$initialiseIndexTemplates$3(SchemaManager.java:127) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.exporter.schema.SchemaManager.initialiseIndexTemplates(SchemaManager.java:118) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.initialiseResources(SchemaManager.java:75) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.schema.SchemaManager.startup(SchemaManager.java:51) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.exporter.CamundaExporter.open(CamundaExporter.java:117) ~[camunda-exporter-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$openExporter$0(ExporterContainer.java:118) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[zeebe-util-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.openExporter(ExporterContainer.java:117) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.lambda$startActiveExportingMode$16(ExporterDirector.java:532) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT] 
</pre>

</p>
</details> 

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by korthout** [comment]
Also reported here:
- https://console.cloud.google.com/errors/detail/COGAtdrpsfPDxgE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvaQ&project=zeebe-io
- https://console.cloud.google.com/errors/detail/CKnp5Yyey-vSZQ;service=zeebe;time=P7D;locations=global?inv=1&invt=AbjvaQ&project=zeebe-io

**Comment by korthout** [comment]
And reported here:
- https://console.cloud.google.com/errors/detail/CIWywMWwu8H2IQ;service=zeebe;time=P7D;locations=global?project=zeebe-io&inv=1&invt=Abj0rQ
