### ISSUE TITLE
Zeebe Client API failed to complete a user task with task "Zeebe User Task"

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda/camunda#25859]
**Describe the bug**
running via the Zeebe Client API in JAVA, the method `newUserTaskCompleteCommand'failed when the task implementation is "Zeebe User Task".

**To Reproduce**
Then, via the Zeebe Client, I called the method

`
zeebeClient.newUserTaskCompleteCommand(Long.parseLong(taskId)).variables(variablesMap).send().join()
`
It works fine

Then move the type to "Zeebe User Task". Run the same code.
You received an exception (see below the stack trace)

I reproduce the issue with [jonathan.lukas]

**Expected behavior**

There is no exception; the task should be completed.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
`
io.camunda.zeebe.client.api.command.ClientException: io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response
	at io.camunda.zeebe.client.impl.http.HttpZeebeFuture.unwrapExecutionException(HttpZeebeFuture.java:86) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.HttpZeebeFuture.join(HttpZeebeFuture.java:42) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.tasklist.CamundaTaskListClient.completeTask(CamundaTaskListClient.java:121) ~[camunda-tasklist-client-java-8.6.6.jar:8.6.6]
	at org.camunda.automator.bpmnengine.camunda8.TaskListClient.executeUserTask(TaskListClient.java:208) ~[classes/:na]
	at org.camunda.automator.bpmnengine.camunda8.BpmnEngineCamunda8.executeUserTask(BpmnEngineCamunda8.java:325) ~[classes/:na]
	at org.camunda.automator.engine.unit.RunScenarioUnitUserTask.executeUserTask(RunScenarioUnitUserTask.java:78) ~[classes/:na]
	at org.camunda.automator.engine.unit.RunScenarioUnit$ScnThreadExecutionCallable.runExecution(RunScenarioUnit.java:197) ~[classes/:na]
	at org.camunda.automator.engine.unit.RunScenarioUnit$ScnThreadExecutionCallable.call(RunScenarioUnit.java:117) ~[classes/:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response
	at io.camunda.zeebe.client.impl.http.ApiCallback.failed(ApiCallback.java:69) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at org.apache.hc.core5.concurrent.BasicFuture.failed(BasicFuture.java:138) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.concurrent.ComplexFuture.failed(ComplexFuture.java:79) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1.failed(InternalAbstractHttpAsyncClient.java:326) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.async.AsyncRedirectExec$1.failed(AsyncRedirectExec.java:246) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.failed(AsyncHttpRequestRetryExec.java:168) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.failed(AsyncProtocolExec.java:295) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.failed(HttpAsyncMainClientExec.java:131) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.failed(ClientHttp1StreamHandler.java:285) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.terminate(ClientHttp1StreamDuplexer.java:181) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.shutdownSession(AbstractHttp1StreamDuplexer.java:164) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onException(AbstractHttp1StreamDuplexer.java:404) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.exception(AbstractHttp1IOEventHandler.java:90) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.exception(ClientHttp1IOEventHandler.java:41) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.InternalDataChannel.onException(InternalDataChannel.java:180) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:55) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44) ~[httpcore5-5.2.2.jar:5.2.2]
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: must specify a response
	at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[na:na]
	at io.camunda.zeebe.client.impl.http.ApiEntity$Response.<init>(ApiEntity.java:89) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.ApiEntity$Response.<init>(ApiEntity.java:85) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.ApiEntity.of(ApiEntity.java:74) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.TypedApiEntityConsumer$JsonApiEntityConsumer.generateContent(TypedApiEntityConsumer.java:94) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.ApiEntityConsumer.generateContent(ApiEntityConsumer.java:81) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at io.camunda.zeebe.client.impl.http.ApiEntityConsumer.generateContent(ApiEntityConsumer.java:50) ~[zeebe-client-java-8.6.5.jar:8.6.5]
	at org.apache.hc.core5.http.nio.entity.AbstractBinAsyncEntityConsumer.completed(AbstractBinAsyncEntityConsumer.java:82) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.nio.entity.AbstractBinDataConsumer.streamEnd(AbstractBinDataConsumer.java:81) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.streamEnd(AbstractAsyncResponseConsumer.java:142) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.streamEnd(HttpAsyncMainClientExec.java:251) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamHandler.dataEnd(ClientHttp1StreamHandler.java:270) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1StreamDuplexer.dataEnd(ClientHttp1StreamDuplexer.java:366) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1StreamDuplexer.onInput(AbstractHttp1StreamDuplexer.java:335) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.AbstractHttp1IOEventHandler.inputReady(AbstractHttp1IOEventHandler.java:64) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.http.impl.nio.ClientHttp1IOEventHandler.inputReady(ClientHttp1IOEventHandler.java:41) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142) ~[httpcore5-5.2.2.jar:5.2.2]
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51) ~[httpcore5-5.2.2.jar:5.2.2]
	... 5 common frames omitted
````

</p>
</details>

**Environment:**
- OS: Windows+Docker for C8
- Zeebe Version: 8.6.6. spring-boot-starter-camunda-sdk 8.6.5
- Configuration: official docker compose

**Comment by korthout** [comment]
>Then move the type to "Zeebe User Task". Run the same code.

@pierre-yves-monnet What do you mean by moving the type? Moving from what/where? How do you move it exactly?

**Comment by chirag7382** [comment]
Any updates on this ??
I am facing the same issue when I use Implementation Type of my User task in workflow definition (BPMN) as "Zeebe user task"

**Comment by blottobill** [comment]
I am having the exact same issue. To clarify the OP post, I think he just means when the type of task is Zeebe User Task and Not Job Worker. This not a complete example that can reproduce, but here is the code I use that fails with the exact same message:
		zeebeClient.newUserTaskCompleteCommand(Long.parseLong(workItem.getWorkItemId())).send().join();
		log.info("complete task finished");
The value of workItemId in this case is "2251799817848713".
Also, if it helps, this is on a self managed (Docker) version of camunda 8.6.7

**Comment by pierre-yves-monnet** [comment]
Sorry, @korthout, I didn't get a notification of your question.

The Java code does not change.

zeebeClient.newUserTaskCompleteCommand(Long.parseLong(taskId)).variables(variablesMap).send().join()

In the modeler, you set the implementation/Type to "Job Worker" ==> Work as expected.
You now set the implementation/Type in the modeler to "Zeebe user task" and redeploy the process ==> Exception.

**Comment by korthout** [comment]
@pierre-yves-monnet I am unable to reproduce this. Can you provide me a minimal reproducer?

For me it's the other way around, which is expected in my opinion:
- I can complete user tasks that are "Zeebe user task" using `zeebeClient.newUserTaskCompleteCommand`
- I cannot complete user tasks that are "Job Worker" using `zeebeClient.newUserTaskCompleteCommand`

**Comment by steinm91** [comment]
Hi @korthout 

We've ran across the same problem when using Quarkus and the Zeebe Extension from Quarkiverse.
I've created a repo where the error should be reproducable: https://github.com/steinm91/camunda-quarkus

Our camunda cluster is deployed on a server using `kind` (https://docs.camunda.io/docs/self-managed/setup/deploy/local/local-kubernetes-cluster) for try-out purposes.

Whenever I try to complete a Zeebe User Task using the Zeebe client I get an error message:

`io.camunda.zeebe.client.api.command.ClientException: io.camunda.zeebe.client.api.command.ClientException: java.lang.NullPointerException: must specify a response
        at io.camunda.zeebe.client.impl.http.HttpZeebeFuture.unwrapExecutionException(HttpZeebeFuture.java:86)
        at io.camunda.zeebe.client.impl.http.HttpZeebeFuture.join(HttpZeebeFuture.java:42)
        at io.camunda.tasklist.CamundaTaskListClient.lambda$completeTask$6(CamundaTaskListClient.java:177)
        at io.camunda.tasklist.CamundaTaskListClient.executeForImplementation(CamundaTaskListClient.java:190)
        at io.camunda.tasklist.CamundaTaskListClient.completeTask(CamundaTaskListClient.java:161)
        at TaskService.completeTask(TaskService.java:82)
`

Maybe someone can take a look at it sometime, in the meantime we use the Job Worker :)

Thanks for your help!

**Comment by korthout** [comment]
The [Zeebe User Task](https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#camunda-user-tasks) (also known as Camunda User Task)'s lifecycle is managed inside of the workflow engine (Zeebe) instead of inside of Tasklist.

@steinm91 Instead of using `CamundaTaskListClient` can you try using `ZeebeClient. newUserTaskCompleteCommand`?

**Comment by steinm91** [comment]
The Client for the Tasklist API actually uses ZeebeClient.newUserTaskCompleteCommand when it detects that the Task uses the Zeebe implementation. 

I've also implemented the ZeebeClient.newUserTaskCompleteCommand directly in my code. It leads to the same error :/

**Comment by korthout** [comment]
Interesting. Is a REST connection configured? https://docs.camunda.io/docs/8.6/apis-tools/java-client/#bootstrapping

**Comment by korthout** [comment]
@pierre-yves-monnet Could you try this as well: https://github.com/camunda/camunda/issues/25859#issuecomment-2886904483

**Comment by korthout** [comment]
Closing this as a misconfiguration rather than a bug. @pierre-yves-monnet let me know when you have new input.
