### ISSUE TITLE
UnsupportedOperationException: Incorrect usage of actor.call(...) cannot be called from current actor.

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#25897]
**Describe the bug**

Reported on SaaS Int Chaos [here](https://console.cloud.google.com/errors/detail/COKDyumjivrUSQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos): `Actor failed in phase 'CLOSING'. Discard all jobs and stop immediately`.

**To Reproduce**

Happened during transition from `FOLLOWER` to `INACTIVE`.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.UnsupportedOperationException: Incorrect usage of actor.call(...) cannot be called from current actor.
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:211) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:79) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.unregisterHandlers(CommandApiServiceImpl.java:114) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.commandapi.CommandApiServiceImpl.onActorClosing(CommandApiServiceImpl.java:57) ~[zeebe-broker-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:83) ~[zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.7.0-SNAPSHOT
- Logs ([link](https://cloudlogging.app.goo.gl/bfvLJkvaau34oJer7), [Drive](https://drive.google.com/file/d/1Ex9rQMrTzlgZo_mcG0m0XuRLMiU5vyAx/view?usp=drive_link))

**Comment by npepinpe** [comment]
@entangled90 / @filipecampos - I think we mentioned it last time we looked at the bug, and that this was likely incorrect, right? I would propose we fix it then, it's a low hanging fruit.

`onActorClosing` should execute whatever is in `unregisterHandlers` but without going through `actor.call` (since it's already in the actor context). So we extract the internal method body so it can be called both externally and internally.

@filipecampos can you do that? It would likely have to be backported as well. Thanks! 🙏
