### ISSUE TITLE
ResourceDeletionRejectionTest fails with an OOM

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#25979]
**Summary**

- How often does the test fail? - So far I've seen this failure once
- Does it block your work?  - Not sure
- Do we suspect that it is a real failure? - Not sure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.resource.ResourceDeletionRejectionTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:358)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:296)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1336)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1134)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:968)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Error:  	at java.base/java.lang.Thread.run(Thread.java:1583)
Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/home/runner/_work/camunda/camunda/zeebe/engine' && '/home/runner/_work/_tool/Java_Temurin-Hotspot_jdk/21.0.5-11.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-202412[12082](https://github.com/camunda/camunda/actions/runs/12292245755/job/34302759382#step:7:12083)028462_1857.jar' '/home/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-12-12T08-15-41_464-jvmRun7' 'surefire-20241212082028462_1851tmp' 'surefire_219-20241212082028462_1854tmp'
</pre>
</details>

**Hypotheses**

None so far.

**Logs**

Link to build: [here](https://github.com/camunda/camunda/actions/runs/12292245755/job/34302759382)
[hs_err_pid51316.log](https://github.com/user-attachments/files/18109606/hs_err_pid51316.log)

<details><summary>Error</summary>
<pre>
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f43c9b79229, pid=51316, tid=51339
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.5+11 (21.0.5+11) (build 21.0.5+11-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xa5229]  malloc+0x189
</pre>
</details>

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | NEEDS_INFO |
| **Severity** | N/A |
| **Likelihood** | N/A |
| **Confidence** | 0.98 |

---

### 📝 Rationale

The issue reports a one-off JVM crash in a test fork but lacks reproduction steps, confirmed impact, and a concrete product behavior problem; triage therefore requires more information before classification. 

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.
