### ISSUE TITLE
ElasticsearchException: [es/search] failed: [index_not_found_exception] no such index.

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#25987]
**Describe the bug**

[Link to the exception](https://console.cloud.google.com/errors/detail/CODGq6mty7OVyQE;service=zeebe;time=P7D;locations=global?inv=1&invt=Abj6sw&project=camunda-cloud-240911)

[es/search] failed: [index_not_found_exception] no such index [operate-process-8.3.0_alias]

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [index_not_found_exception] no such index [operate-process-8.3.0_alias]
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1923) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.search.es.clients.ElasticsearchSearchClient.search(ElasticsearchSearchClient.java:55) ~[camunda-search-client-elasticsearch-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.lambda$search$0(SearchClientBasedQueryExecutor.java:50) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.executeSearch(SearchClientBasedQueryExecutor.java:73) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.search(SearchClientBasedQueryExecutor.java:49) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClients.searchProcessDefinitions(SearchClients.java:206) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.service.ProcessDefinitionServices.search(ProcessDefinitionServices.java:45) ~[camunda-service-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.search(ProcessDefinitionQueryController.java:62) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.fold(Either.java:445) ~[zeebe-util-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.searchProcessDefinitions(ProcessDefinitionQueryController.java:53) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.30.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.30.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.1.14.jar:6.1.14]
	at io.camunda.zeebe.gateway.RestApiCompositeFilter.doFilter(RestApiCompositeFilter.java:36) ~[camunda-zeebe-8.7.0-alpha2.jar:8.7.0-alpha2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by ChrisKujawa** [comment]
This is somewhat a duplicate of https://github.com/camunda/camunda/issues/24146 and related to #26890 we need to create the schema before allowing requests to the secondary storage.

@houssain-barouni I will assign it to you, as you will work on the schema manager. I will remove it also from the exporter project.

**Comment by berkaycanbc** [comment]
Seen in: [`8.9.2`](https://console.cloud.google.com/errors/detail/CKriidWx35qGCQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev)
Also for `operate-decision` index: [`8.9.2`](https://console.cloud.google.com/errors/detail/CI2WyMKaztjJLA;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev)

**Comment by houssain-barouni** [comment]
> Seen in: [`8.9.2`](https://console.cloud.google.com/errors/detail/CKriidWx35qGCQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev) Also for `operate-decision` index: [`8.9.2`](https://console.cloud.google.com/errors/detail/CI2WyMKaztjJLA;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev)

This seems to be triggered when Prometheus scarps some metrics about processes and decisions, we need to check why the alias was not ready by that time. Also for now it seems to happen in Operate V1 stack

```
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [index_not_found_exception] no such
index [operate-process-8.3.0_alias]

at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse ( co/elastic.clients.transport/ElasticsearchTransportBase.java:357 )
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest ( co/elastic.clients.transport/ElasticsearchTransportBase.java:141 )
at co.elastic.clients.elasticsearch.ElasticsearchClient.search ( co/elastic.clients.elasticsearch/ElasticsearchClient.java:5184 )
at io.camunda.operate.store.elasticsearch.ElasticsearchProcessStore.getDistinctCountFor ( io/camunda.operate.store.elasticsearch/ElasticsearchProcessStore.java:116 )
at io.camunda.operate.management.ModelMetricProvider.getBPMNModelCount ( io/camunda.operate.management/ModelMetricProvider.java:65 )
at io.micrometer.core.instrument.Gauge.lambda$builder$0 ( io/micrometer.core.instrument/Gauge.java:58 )
at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble ( io/micrometer.core.instrument/StrongReferenceGaugeFunction.java:47 )
at io.micrometer.core.instrument.internal.DefaultGauge.value ( io/micrometer.core.instrument.internal/DefaultGauge.java:53 )
at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.lambda$newGauge$12 ( io/micrometer.prometheusmetrics/PrometheusMeterRegistry.java:338 )
```

**Comment by RomanJRW** [comment]
Closing this as done, as we believe it was resolved in the linked tickets described [here](https://github.com/camunda/camunda/issues/25987#issuecomment-2720254115)
