### ISSUE TITLE
Elasticsearch closed the connection while performing search request

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#26050]
**Describe the bug**

Error link [here](https://console.cloud.google.com/errors/detail/CNvhsrmCq9a1-QE;service=zeebe;time=P7D;locations=global?inv=1&invt=Abj_2g&project=camunda-saas-prod)

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
org.apache.http.ConnectionClosedException: Connection is closed
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:924) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:304) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest(RestClientHttpClient.java:91) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:144) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1923) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.search.es.clients.ElasticsearchSearchClient.search(ElasticsearchSearchClient.java:55) ~[camunda-search-client-elasticsearch-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.lambda$search$0(SearchClientBasedQueryExecutor.java:50) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.executeSearch(SearchClientBasedQueryExecutor.java:73) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.search(SearchClientBasedQueryExecutor.java:49) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClients.searchProcessDefinitions(SearchClients.java:206) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.service.ProcessDefinitionServices.search(ProcessDefinitionServices.java:45) ~[camunda-service-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.search(ProcessDefinitionQueryController.java:62) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.fold(Either.java:445) ~[zeebe-util-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.searchProcessDefinitions(ProcessDefinitionQueryController.java:53) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.1.14.jar:6.1.14]
	at io.camunda.zeebe.gateway.RestApiCompositeFilter.doFilter(RestApiCompositeFilter.java:36) ~[camunda-zeebe-8.7.0-alpha2.jar:8.7.0-alpha2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.apache.http.ConnectionClosedException: Connection is closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.16.jar:4.4.16]
	... 1 more 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: zeebe:8.7.0-alpha2
- Configuration:

**Comment by ana-vinogradova-camunda** [comment]
Looks like [this](https://console.cloud.google.com/errors/detail/CP_nhvvHr-H3ag;service=zeebe;time=P7D;locations=global?inv=1&invt=AbkAxg&project=camunda-saas-int-chaos) is related too.

**Comment by ana-vinogradova-camunda** [comment]
Looks like [this](https://console.cloud.google.com/errors/detail/CJicn-DqtYOoWA;service=zeebe;time=P7D;locations=global?inv=1&invt=AbkA2g&project=camunda-saas-dev) is also related.

**Comment by koevskinikola** [comment]
Issue occurred again:
- Camunda SaaS (Prod - LNR)
- Zeebe version: `8.7.0-alpha2`
- GCP downloaded log: [internal link](https://drive.google.com/file/d/1YhwHW8JPch7NJdFjqsN0fKj8US4hSr63/view?usp=sharing)
- GCP logs: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-prod-lhr%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.namespace_name%3D%2258e2f12f-ec0b-47ed-a3d1-520aa11b3996-zeebe%22%0Aresource.labels.location%3D%22europe-west2%22%0Aresource.labels.cluster_name%3D%22worker-6%22;pinnedLogId=2024-12-16T05:17:41.834325843Z%2F8mwicgc17bwunu6i;cursorTimestamp=2024-12-16T05:17:41.850241358Z;startTime=2024-12-16T04:48:11.834Z;endTime=2024-12-16T05:48:11.834Z?inv=1&invt=AbkRAg&project=camunda-saas-prod-lhr)

**Comment by koevskinikola** [comment]
Another occurrence [here](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.namespace_name%3D%221e3e0a04-6556-4451-92e0-3bcba6b0b5dd-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-2%22%0Aresource.labels.location%3D%22europe-north1%22;pinnedLogId=2024-12-16T16:58:01.727252594Z%2Ft2dyhdt2pxej923g;cursorTimestamp=2024-12-16T16:58:01.727252594Z;startTime=2024-12-16T16:28:31.727Z;endTime=2024-12-16T17:28:31.727Z?inv=1&invt=AbkXfA&project=camunda-saas-dev).

**Comment by berkaycanbc** [comment]
Occurred again on SaaS Int [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2025-01-08T05:25:53.838352316Z;endTime=2025-01-08T05:56:23.838Z;query=error_groups.id%3D%22CNvhsrmCq9a1-QE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-gateway-64fdcddd9-h72wv%22%0Aresource.labels.namespace_name%3D%2262baa71f-f78c-437c-8038-dc4b84f82d67-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Atimestamp%3D%222025-01-08T05:25:53.838352316Z%22%0AinsertId%3D%220rbm5ypp1qg5dzgo%22;startTime=2025-01-08T04:56:23.838Z?project=camunda-saas-int).

**Comment by ChrisKujawa** [comment]
@rodrigo-lourenco-lopes could you take a look at this and validate whethet this issue still exist? Likely it is some connectivity issue that is transient and shouldnt be logged as error, please verify.

**Comment by ChrisKujawa** [comment]
Scratch [this](https://github.com/camunda/camunda/issues/26050#issuecomment-2720167415).

This is I think, similar to  the other search connectivity issue. https://github.com/camunda/camunda/issues/28117

@tmetzke I think we need to handle the connectivity issues a bit better in the search/REST API layer

**Comment by tmetzke** [comment]
Thanks, @ChrisKujawa, I agree, we can add this to the #28117 issue basically 👍

**Comment by tmetzke** [comment]
@mihail-ca, this should be solved with #28117 as well

**Comment by tmetzke** [comment]
@mihail-ca, the issue here is that a connectivity issue is logged as ERROR but should only be a WARN at max. Therefore, this should be solved with #28117.
