### ISSUE TITLE
Camunda search client fails due to service not known

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#26121]
**Describe the bug**

The Camunda search client fails due to an `IOException` (Name or service not known).

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.io.IOException: elasticsearch-es-http: Name or service not known
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:939) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:304) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest(RestClientHttpClient.java:91) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:144) ~[elasticsearch-java-8.13.4.jar:?]
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1923) ~[elasticsearch-java-8.13.4.jar:?]
	at io.camunda.search.es.clients.ElasticsearchSearchClient.search(ElasticsearchSearchClient.java:55) ~[camunda-search-client-elasticsearch-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.lambda$search$0(SearchClientBasedQueryExecutor.java:50) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.executeSearch(SearchClientBasedQueryExecutor.java:73) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClientBasedQueryExecutor.search(SearchClientBasedQueryExecutor.java:49) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.search.clients.SearchClients.searchProcessDefinitions(SearchClients.java:206) ~[camunda-search-client-query-transformer-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.service.ProcessDefinitionServices.search(ProcessDefinitionServices.java:45) ~[camunda-service-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.search(ProcessDefinitionQueryController.java:62) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.util.Either$Right.fold(Either.java:445) ~[zeebe-util-8.7.0-alpha2.jar:8.7.0-alpha2]
	at io.camunda.zeebe.gateway.rest.controller.ProcessDefinitionQueryController.searchProcessDefinitions(ProcessDefinitionQueryController.java:53) ~[zeebe-gateway-rest-8.7.0-alpha2.jar:8.7.0-alpha2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.30.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.14.jar:6.1.14]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.30.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.1.14.jar:6.1.14]
	at io.camunda.zeebe.gateway.RestApiCompositeFilter.doFilter(RestApiCompositeFilter.java:36) ~[camunda-zeebe-8.7.0-alpha2.jar:8.7.0-alpha2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.14.jar:6.1.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.14.jar:6.1.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:731) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar:10.1.30]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: elasticsearch-es-http: Name or service not known
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:666) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:637) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:472) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:381) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:130) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:116) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
	... 71 more
```

</p>
</details>

**Environment:**
- OS: Camunda SaaS (Prod - LHR)
- Zeebe Version: 8.7.0-alpha2
- Configuration: 
- GCP downloaded logs: [internal link](https://drive.google.com/file/d/1U5iNV7tNoBBtqn3ocmGFqwjt40gSK_aB/view?usp=sharing)
- GCP log viewer: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west2%22%0Aresource.labels.project_id%3D%22camunda-saas-prod-lhr%22%0Aresource.labels.cluster_name%3D%22worker-6%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22b1d24680-aca8-4ccb-bbf6-402e13b94132-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;pinnedLogId=2024-12-16T07:45:35.149454478Z%2F77vwepnmogurujmw;cursorTimestamp=2024-12-16T07:45:15.889794085Z;startTime=2024-12-16T07:16:05.149Z;endTime=2024-12-16T08:16:05.149Z?inv=1&invt=AbkRAA&project=camunda-saas-prod-lhr)

**Comment by npepinpe** [comment]
Did you notify the API team? This sounds like a possible bug there.

**Comment by berkaycanbc** [comment]
Happened again:

Version: `Zeebe SNAPSHOT`
GCP logs: [link](https://console.cloud.google.com/logs/query;cursorTimestamp=2025-03-03T00:36:46.632784034Z;endTime=2025-03-03T01:07:22.668Z;query=error_groups.id%3D%22CKGqmP6S67bzbw%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.namespace_name%3D%22d8ddbca7-5393-4a5e-b2ca-f638909efc24-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Atimestamp%3D%222025-03-03T00:36:46.632784034Z%22%0AinsertId%3D%22tdi24vdt47wk66ve%22;startTime=2025-03-03T00:07:22.668Z?project=camunda-saas-int-chaos)
GCP logs downloaded: [link](https://drive.google.com/drive/folders/1lf1glFrCNBK_jGlCoBCqOvZfpGaSVsRm)

**Comment by ana-vinogradova-camunda** [comment]
Looks like something similar happened again:

Version: zeebe:8.8.0-alpha3
GCP logs link: [here](https://console.cloud.google.com/errors/detail/CJC5pbWGv_O6hQE;service=zeebe;time=P7D;locations=global?invt=AbuzWg&project=camunda-saas-prod-lhr)
Logs: [here](https://drive.google.com/file/d/1U4oSb731Jk_GjLoxJN2dcmwUM77CfOAp/view?usp=drive_link)

```
java.util.concurrent.CompletionException: java.net.UnknownHostException: elasticsearch-es-http
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: elasticsearch-es-http
	at java.base/java.net.InetAddress$CachedLookup.get(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:666) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:637) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:472) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280) ~[httpcore-nio-4.4.16.jar:4.4.16]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:381) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:130) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:116) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138) ~[httpasyncclient-4.1.5.jar:4.1.5]
	at org.elasticsearch.client.RestClient.lambda$performRequestAsync$0(RestClient.java:397) ~[elasticsearch-rest-client-8.16.4.jar:8.16.4]
	at org.elasticsearch.client.Cancellable$RequestCancellable.runIfNotCancelled(Cancellable.java:90) ~[elasticsearch-rest-client-8.16.4.jar:8.16.4]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:395) ~[elasticsearch-rest-client-8.16.4.jar:8.16.4]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:382) ~[elasticsearch-rest-client-8.16.4.jar:8.16.4]
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequestAsync(RestClientHttpClient.java:113) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequestAsync(ElasticsearchTransportBase.java:184) ~[elasticsearch-java-8.16.4.jar:?]
	at co.elastic.clients.elasticsearch.ElasticsearchAsyncClient.search(ElasticsearchAsyncClient.java:2362) ~[elasticsearch-java-8.16.4.jar:?]
	at io.camunda.exporter.tasks.archiver.ElasticsearchArchiverRepository.getProcessInstancesNextBatch(ElasticsearchArchiverRepository.java:102) ~[camunda-exporter-8.8.0-alpha3.jar:8.8.0-alpha3]
	at io.camunda.exporter.tasks.archiver.ProcessInstancesArchiverJob.archiveNextBatch(ProcessInstancesArchiverJob.java:46) ~[camunda-exporter-8.8.0-alpha3.jar:8.8.0-alpha3]
	at io.camunda.exporter.tasks.archiver.ArchiverJob.execute(ArchiverJob.java:18) ~[camunda-exporter-8.8.0-alpha3.jar:8.8.0-alpha3]
	at io.camunda.exporter.tasks.ReschedulingTask.run(ReschedulingTask.java:47) ~[camunda-exporter-8.8.0-alpha3.jar:8.8.0-alpha3]
	... 6 more 
```

It looks like this happened during the shutdown.

**Comment by koevskinikola** [comment]
Issue occurred again on SaaS Int - chaos on a `8.8.0-snapshot` cluster.

- [GCP logs link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%2263a0c3b9-0bd1-4050-b659-8bdc2fc5bdc8-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22;pinnedLogId=2025-06-13T22:42:39.316725490Z%2Fllmdawb3yao8665m;cursorTimestamp=2025-06-13T22:42:37.201772237Z;startTime=2025-06-13T22:13:09.316Z;endTime=2025-06-13T23:13:09.316Z?inv=1&invt=Ab0Rcg&project=camunda-saas-int-chaos) (internal)\
- [Downloaded GCP logs](https://drive.google.com/file/d/1Q66tVxqn_WeSQ5AQ6RhOJRoJVSUaVRmD/view?usp=sharing) (internal link)

**Comment by rodrigo-lourenco-lopes** [comment]
Also happened [here](https://console.cloud.google.com/errors/detail/CKfg19LfseugLQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int) in `zeebe-8.8.0` in `Camunda Saas Int`

**Comment by berkaycanbc** [comment]
Occurred again on SaaS Prod `zeebe:8.8.0-alpha8`:

GCP error: [LINK](https://console.cloud.google.com/errors/detail/CJC5pbWGv_O6hQE;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911)
GCP logs: [LINK](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CJC5pbWGv_O6hQE%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.namespace_name%3D%2237299ef5-fc7f-4ac7-9b9e-f1bc6d84f7b6-zeebe%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.container_name%3D%22zeebe%22;cursorTimestamp=2025-10-28T17:35:15.598452577Z;startTime=2025-10-28T17:05:45.598Z;endTime=2025-10-28T18:05:45.598Z?project=camunda-cloud-240911)

**Comment by HeleneW-dot** [comment]
Seeing this recur in `camunda-saas-prod-lhr`:
GCP Logs: [link](https://drive.google.com/file/d/19ewhJZbfIw0rPG2MG8V8wHCGyN_zdq4z/view?usp=sharing)
GCP Error: [link](https://console.cloud.google.com/errors/detail/CPnj7Y3Upa24vwE;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod-lhr)
