### ISSUE TITLE
LargeStateControllerPerformanceTest.shouldRecoverStateWithinDeviation is flaky

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#26259]
**Summary**

- How often does the test fail? Once
- Does it block your work? No
- Do we suspect that it is a real failure? Not sure

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 121.2 s <<< FAILURE! -- in io.camunda.zeebe.broker.system.partitions.impl.perf.LargeStateControllerPerformanceTest
Error:  io.camunda.zeebe.broker.system.partitions.impl.perf.LargeStateControllerPerformanceTest.shouldRecoverStateWithinDeviation(JMHTestCase) -- Time elapsed: 120.6 s <<< FAILURE!
java.lang.AssertionError: Expected reference score to be at least "10.000" (with "20.000%" max deviation, i.e. "8.000"), but got "7.941"
	at io.camunda.zeebe.broker.system.partitions.impl.perf.LargeStateControllerPerformanceTest.shouldRecoverStateWithinDeviation(LargeStateControllerPerformanceTest.java:78)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</details>

**Logs**

Link to build: [here](https://github.com/camunda/camunda/actions/runs/12395767338/job/34602281870?pr=26253)

**Comment by lenaschoenburg** [comment]
This is failing more often now, three times on `main` in short succession: 

![Image](https://github.com/user-attachments/assets/f44e140e-869f-4526-a838-f62da9c22cb4)

**Comment by lenaschoenburg** [comment]
Reported as blocking the merge queue: https://camunda.slack.com/archives/CSQ2E3BT4/p1737045081760619

**Comment by lenaschoenburg** [comment]
@npepinpe The test was disabled to unblock the merge queue now: https://github.com/camunda/camunda/pull/27046 
We need to invest time if we want to enable it again.

**Comment by npepinpe** [comment]
I still think it's the way we validate the measurement, it's inherently flaky I think, unless we can run on it on a perfectly controlled environment with no noise (and even then...).

I don't think we have much time to focus on it these days, honestly. I could see it going into our benchmarking/performance stream, but nothing soon...
