### ISSUE TITLE
io.camunda.zeebe.it.clustering.FailOverReplicationTest is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#26393]
**Summary**

- How often does the test fail? 15 times in the last week
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
org.opentest4j.AssertionFailedError: 

expected: FileBasedSnapshotId{index=206, term=3, processedPosition=221, exporterPosition=223, brokerId=Optional[1]}
 but was: FileBasedSnapshotId{index=0, term=0, processedPosition=1, exporterPosition=0, brokerId=Optional[0]}
	at io.camunda.zeebe.it.clustering.FailOverReplicationTest.shouldReceiveSnapshotAfterNetworkPartition(FailOverReplicationTest.java:136)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Logs**

Test job: https://github.com/camunda/camunda/actions/runs/12470311955/attempts/1

**Comment by lenaschoenburg** [comment]
I'm pretty sure this is just a normal flaky test and not something else. I already tried to stabilize it here: https://github.com/camunda/camunda/commit/8cddd330bd99b37ca5f04144e1c1553d29bd0fc6

But that fix wasn't enough, I think we should just change the entire assertion to await that `previousLeader` has the expected snapshot.

**Comment by npepinpe** [comment]
Let's try it. We have a dashboard to observe improvements over time, so we actually get feedback from trying to stabilize now :)
