### ISSUE TITLE
NPE on RaftClusterContext#configure

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#4159]
**Expected behavior**
No exception on configure.

**Actual behavior**

I lately saw multiple times in our qa tests NPE's like 

```
java.lang.NullPointerException: configuration cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-28.1-jre.jar:?]
	at io.atomix.protocols.raft.cluster.impl.RaftClusterContext.configure(RaftClusterContext.java:579) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.protocols.raft.cluster.impl.RaftClusterContext.reset(RaftClusterContext.java:568) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.protocols.raft.roles.AbstractRole.updateTermAndLeader(AbstractRole.java:124) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.protocols.raft.roles.InactiveRole.onConfigure(InactiveRole.java:117) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$8(RaftContext.java:216) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:254) ~[atomix-raft-3.2.0-20191207.093106-100.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-20191207.093016-100.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Steps to reproduce**
Run the qa tests.

**Comment by npepinpe** [comment]
Is this still occurring in recent versions? I would close this otherwise.

**Comment by npepinpe** [comment]
I will close this for now. I haven't seen this in a long time, and we refactored the whole joining process.

**Comment by saig0** [comment]
The failure occurred again twice in the medic benchmark (`medic-cw-49--benchmark-mixed`, `medic-cw-49-79bcae7-benchmark`) for Zeebe version `8.2.0-SNAPSHOT`.

The failure happened during the startup of the broker.

**Comment by Zelldon** [comment]
Happened again on benchmark medic week 52, on normal start up (on first start). This is a bit weird tbh.

https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.pod_name%3D%22medic-cw-52-cce4510-benchmark-zeebe-1%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22medic-cw-52-cce4510-benchmark%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.project_id%3D%22zeebe-io%22;timeRange=2022-12-26T01:12:15.119Z%2F2022-12-26T02:12:15.119Z;pinnedLogId=2022-12-26T01:41:45.119101649Z%2Fmr8fvowtnbdtg8g2;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2022-12-26T01:41:56.911971446Z?project=zeebe-io

**Comment by koevskinikola** [comment]
Happened again on a trial cluster on version `8.2.3`. 

Here are the logs: https://drive.google.com/file/d/1Y1VTz-Q8KLk6Hc19d3x8JBwXNop48awT/view

**Comment by megglos** [comment]
Happened again here https://console.cloud.google.com/logs/query;cursorTimestamp=2023-07-26T15:14:30.371917277Z;query=%22bd612a1f-bfdb-4b82-9479-7ee711f18a4f-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0A--%22ZeebePartition-3%22%0A%22unhealthy%22%0Atimestamp%3D%222023-07-26T15:14:30.371917277Z%22%0AinsertId%3D%22k43kn4jajohp2jys%22;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?project=camunda-saas-int-chaos

**Comment by megglos** [comment]
ZDP-Triage:
- set as upcoming to increase chance we investigate on this
- severity still low given the partition is still fine on other brokers there is no interruption on processing and eventualy restarts will heal it

**Comment by Zelldon** [comment]
Happened again in 8.2.11

https://console.cloud.google.com/errors/detail/CI3p7rmNubS-5wE;service=zeebe;time=P7D?project=camunda-saas-int-chaos


```
java.lang.NullPointerException: configuration cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
	at io.atomix.raft.cluster.impl.RaftClusterContext.configure(RaftClusterContext.java:296) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.raft.cluster.impl.RaftClusterContext.reset(RaftClusterContext.java:285) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.raft.roles.AbstractRole.updateTermAndLeader(AbstractRole.java:125) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.raft.roles.InactiveRole.onConfigure(InactiveRole.java:57) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$6(RaftContext.java:285) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.raft.impl.RaftContext.lambda$runOnContext$21(RaftContext.java:300) ~[zeebe-atomix-cluster-8.2.11.jar:8.2.11]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.2.11.jar:8.2.11]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Zelldon** [comment]
Happened again on 8.2.11-dmn cache SNAPSHOT

https://console.cloud.google.com/errors/detail/CI3p7rmNubS-5wE;service=zeebe;time=P7D?project=camunda-saas-int


```
java.lang.NullPointerException: configuration cannot be null

at com.google.common.base.Preconditions.checkNotNull ( com/google.common.base/Preconditions.java:907 )
at io.atomix.raft.cluster.impl.RaftClusterContext.configure ( io/atomix.raft.cluster.impl/RaftClusterContext.java:296 )
at io.atomix.raft.cluster.impl.RaftClusterContext.reset ( io/atomix.raft.cluster.impl/RaftClusterContext.java:285 )
at io.atomix.raft.roles.AbstractRole.updateTermAndLeader ( io/atomix.raft.roles/AbstractRole.java:125 )
at io.atomix.raft.roles.InactiveRole.onConfigure ( io/atomix.raft.roles/InactiveRole.java:57 )
at io.atomix.raft.impl.RaftContext.lambda$registerHandlers$6 ( io/atomix.raft.impl/RaftContext.java:285 )
at io.atomix.raft.impl.RaftContext.lambda$runOnContext$21 ( io/atomix.raft.impl/RaftContext.java:300 )
at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run ( io/atomix.utils.concurrent/SingleThreadContext.java:178 )
at java.util.concurrent.Executors$RunnableAdapter.call
at java.util.concurrent.FutureTask.run
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run
at java.util.concurrent.ThreadPoolExecutor.runWorker
at java.util.concurrent.ThreadPoolExecutor$Worker.run
at java.lang.Thread.run
```

**Comment by npepinpe** [comment]
We did changes there with dynamic scaling starting with 8.3. As 8.2 is going out of support next month, I will close this.
