### ISSUE TITLE
Raise an incident when an exception occurs during timer rescheduling

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#4208]
**Is your feature request related to a problem? Please describe.**
If an exception occurs during rescheduling of a repeating timer (i.e. cycle), then it is currently not possible to resolve this as an incident.

**Describe the solution you'd like**
Raise an incident that can be resolved, when this situation occurs. See: TriggerTimerProcessor.

**Describe alternatives you've considered**
Currently an incident could be raised, but it cannot be resolved yet. We do not yet support resolving timer records incidents.

**Additional context**
With the addition of FEEL expression support for timers, the chance of this issue occurring increases a lot. Previously it was only possible to get into this situation if somehow there was no timer known while rescheduling. Now, this can occur because the variables used in the cycle expression may change at runtime.

**Comment by korthout** [comment]
I believe this should actually be `severity/high`:
 - the impact is a blacklisted process instance
 - there is no workaround available

**Comment by saig0** [comment]
We found this error with the following stacktrace in the error reporting tool. It was triggered as part of a game day.  

```
java.lang.IllegalStateException: Expected to reschedule repeating timer for element with id 'Event_1u7f6ud', but an error occurred: Text cannot be parsed to a Period
	at io.camunda.zeebe.engine.processing.timer.TriggerTimerProcessor.rescheduleTimer(TriggerTimerProcessor.java:148) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.engine.processing.timer.TriggerTimerProcessor.processRecord(TriggerTimerProcessor.java:118) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.6.jar:8.1.6]
```

**Comment by koevskinikola** [comment]
The error occurred again in an internal cluster of the Operate team. I documented it in a [Google Doc](https://docs.google.com/document/d/1KgT5RW2I4eyvJIyvlPuIhZf8Ya5UQYNZzqq-MUCUbXI/edit#).

**Comment by lev-safro** [comment]
@korthout is this still the case? I'm concerned that with the **high** severity there were no actions taken for the last 6 years.
Is the severity still high? What about the Likelihood?

**Comment by korthout** [comment]
@lev-safro Yes this is still the case. The process instance is banned when this occurs. We might consider a banned process instance at critical severity rather than high as a banned instance could be considered a form of loss of data, but it's a gray area. Personally, I think high is fitting.

Likelihood is hard to determine. As far as I know, no customers have reported this so far, and we've not seen this error on SaaS. The case only occurs when using a timer cycle FEEL expression that is successfully evaluated the first time, but fails on some later evaluation when rescheduling the timer for the cycle.

<details><summary>Showcasing test case</summary>
<p>

Add the following to test case to `io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest`:

```java
@Test
public void shouldRaiseIncidentWhenCycleExpressionFailsToReschedule() {
  // Deploy a process with a task with a timer boundary event with a cycle expression that the
  // first time evaluates to a valid cycle but on rescheduling evaluates to an invalid value

  ENGINE
      .deployment()
      .withXmlResource(
          Bpmn.createExecutableProcess("process_with_faulty_cycle")
              .startEvent()
              .serviceTask("task", b -> b.zeebeJobType("type"))
              .boundaryEvent("timer")
              .cancelActivity(false)
              .timerWithCycleExpression(
                  "if (shouldFail = false) then \"R/PT1S\" else \"invalid-cycle\"")
              .endEvent()
              .moveToActivity("task")
              .endEvent()
              .done())
      .deploy();

  final var processInstanceKey =
      ENGINE
          .processInstance()
          .ofBpmnProcessId("process_with_faulty_cycle")
          .withVariable("shouldFail", false)
          .create();

  // Advance time to trigger the timer the first time
  ENGINE.increaseTime(Duration.ofHours(2));

  // Await the first timer activation
  RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_ACTIVATED)
      .withProcessInstanceKey(processInstanceKey)
      .withElementId("timer")
      .await();

  // Set variable to make the cycle expression evaluate to an invalid value on rescheduling
  ENGINE
      .variables()
      .ofScope(processInstanceKey)
      .withDocument(Map.of("shouldFail", true))
      .update();

  // when - advance time to trigger the rescheduling of the timer
  ENGINE.increaseTime(Duration.ofHours(2));

  // then - expect an incident due to failure to reschedule the timer
  Assertions.assertThat(
          RecordingExporter.incidentRecords(IncidentIntent.CREATED)
              .withProcessInstanceKey(processInstanceKey)
              .getFirst()
              .getValue())
      .hasElementId("timer")
      .hasErrorMessage(
          "Expected to reschedule repeating timer for element with id 'timer', but an error occurred");
}
```

The following exception is logged:

```
18:36:44.856 [StreamProcessor-1] ERROR io.camunda.zeebe.broker.process - Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=TIMER, intent=TRIGGER, authorization={"format":"UNKNOWN","authData":"***","claims":"***"}}, value={"elementInstanceKey":2251799813685272,"processInstanceKey":2251799813685267,"dueDate":1768937805420,"targetElementId":"timer","repetitions":-1,"processDefinitionKey":2251799813685266,"tenantId":"<default>"}}' without errors, but exception occurred with message 'Expected to reschedule repeating timer for element with id 'timer', but an error occurred: Cron expression contains 1 parts but we expect one of [6]'.
java.lang.IllegalStateException: Expected to reschedule repeating timer for element with id 'timer', but an error occurred: Cron expression contains 1 parts but we expect one of [6]
	at io.camunda.zeebe.engine.processing.timer.TimerTriggerProcessor.rescheduleTimer(TimerTriggerProcessor.java:163)
	at io.camunda.zeebe.engine.processing.timer.TimerTriggerProcessor.processRecord(TimerTriggerProcessor.java:137)
	at io.camunda.zeebe.engine.Engine.process(Engine.java:179)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:387)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$0(ProcessingStateMachine.java:287)
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:128)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:287)
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:244)
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:84)
	at io.camunda.zeebe.scheduler.ActorJob.execute$$$capture(ActorJob.java:43)
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java)
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:125)
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:127)
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:104)
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:224)
```

And finally we see a log indicating that the process instance has been banned.

```
18:36:44.862 [StreamProcessor-1] WARN  io.camunda.zeebe.broker.logstreams - Ban process instance 2251799813685267, due to previous errors.
```

</p>
</details>

**Comment by marcosgvieira** [comment]
🔄 **Status updated automatically (Core Features)**

**From:** Backlog  
**To:** Ready  

**Reason:** The issue already has an assignee.

**Comment by remcowesterhoud** [comment]
I had a look into this issue and whilst the bug is valid. The solution to it is too complex to tackle this as a normal bug.

Timers don't have an element instance on which we can create the incident. This means the incident has to live on the element instance the timer is attached to. Creating an incident would then mean creating an incident on this element instance. This raises a bunch of questions:

1. Should the attached element instance be blocked by this incident? Eg. no jobs can be activated due to the incident of the timer?
    - If it shouldn't block, which seems sensible to me for a non-interrupting timer, should it really be considered an incident? It's more of a warning at this point. If we'd make it an incident anyways we'd have different behaviors depending on the incident which will likely cause confusion.
3. What if the timer is in an event sub-process? Would the incident be created on the process instance level?

To me it feels like we need warnings next to incident. They'd be non-blocking incidents that will warn users that something is off, but that the process is not in some definitive error state. Of course that expands the scope of this bug massively. We'd need to introduce this warnings concept, export the data, show it in Operate and maybe Optimize.

All in all, whatever direction we'd go, it's a lot of work for a 6 year old bug that no customer has ever complained about 😅. I'd question the priorty of fixing this.

**Comment by lev-safro** [comment]
@remcowesterhoud thank you for analysis! I think this is very valid point:

> it's a lot of work for a 6 year old bug that no customer has ever complained about

IMO we should close it and concentrate on something that has customer impact. On the other hand, if we want to fix that it seems that we'll need a feature request with Product and Design input. 

@remcowesterhoud @aleksander-dytko WDYT?

**Comment by remcowesterhoud** [comment]
Closing as something we won' fix as it's not worth the effort at this time (and hasn't been in the last 6 years). [See discussion here](https://camunda.slack.com/archives/C08G19SQ1BM/p1776756570801919) (internal).
