### ISSUE TITLE
MessagingException$NoRemoteHandler: No remote message handler registered for this message

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#5518]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/COeS4vn5-Je6jwE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by Zelldon** [comment]
Seems the issue name is wrong. It actually references to `MessagingException$NoRemoteHandler: No remote message handler registered for this message`

**Comment by Zelldon** [comment]
Stacktrace for activation:

```
  exception: "io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:64) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:37) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:836) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
"   
  logger: "io.zeebe.gateway"   
  message: "Failed to activate jobs for type benchmark-task from partition 3" 
```
For other command:

```
exception: "io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:64) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:37) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:836) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
"   
  logger: "io.zeebe.gateway"   
  message: "Expected to handle gRPC request, but an unexpected error occurred" 
```

[Happening in 0.25.1](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:33:58.980000000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:29.082802000Z&pinnedLogId=1f2hxblg2ub45fo&pinnedLogTimestamp=2020-11-25T01:33:26.200935Z)

**Comment by Zelldon** [comment]
[It looks like as there are inconsistency in the topology:](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:33:58.980000000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:25.971270000Z&pinnedLogId=1dog1vsfvxkv8i&pinnedLogTimestamp=2020-11-25T01:33:25.971270Z)

```
  context: {
   actor-name: "Broker-0-ManagementRequestHandler"    
   loggerName: "io.zeebe.broker.workflow.repository"    
   reportLocation: {…}    
   threadId: 32    
   threadName: "Broker-0-zb-actors-1"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.workflow.repository"   
  message: "Rejecting deployment 2251799813884161 for partition 3 as not leader" 
```

**Comment by Zelldon** [comment]
[Broker 2 seems to be leader for partition 3](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:33:58.980000000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:21.429139000Z&pinnedLogId=1f2a3hzg22z63pb&pinnedLogTimestamp=2020-11-25T01:33:21.429139Z)

```
  context: {
   actor-name: "Broker-2-HealthCheckService"    
   loggerName: "io.zeebe.broker.system"    
   threadId: 32    
   threadName: "Broker-2-zb-actors-1"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.system"   
  message: "Partition-3 recovered, marking it as healthy" 
```

[But itself sends deployments to wrong endpoints:](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:33:58.980000000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:24.954592000Z&pinnedLogId=1mu2viug2v5pgc1&pinnedLogTimestamp=2020-11-25T01:33:24.954592Z)


```
context: {
   actor-name: "Broker-2-StreamProcessor-1"    
   loggerName: "io.zeebe.broker.workflow.repository"    
   threadId: 31    
   threadName: "Broker-2-zb-actors-0"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.workflow.repository"   
  message: "Pushed deployment 2251799813884161 to all partitions." 

```

[Which get be rejected by Broker-0, since he is not the leader for partition 3](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:33:58.980000000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=%0AlogName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:24.955076000Z&pinnedLogId=1dog1vsfvxkv88&pinnedLogTimestamp=2020-11-25T01:33:24.955076Z)

```
  context: {
   actor-name: "Broker-0-ManagementRequestHandler"    
   loggerName: "io.zeebe.broker.workflow.repository"    
   reportLocation: {…}    
   threadId: 32    
   threadName: "Broker-0-zb-actors-1"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.workflow.repository"   
  message: "Rejecting deployment 2251799813884161 for partition 3 as not leader" 
```
Sender prints `Received partition leader mismatch error from partition 3 for deployment 2251799813884161. Retrying.`, follow up issue https://github.com/zeebe-io/zeebe/issues/5918 to improve the message.

I assume that all other error messages like 
```
exception: "io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:64) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:37) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:836) ~[atomix-cluster-0.25.1.jar:0.25.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.53.Final-linux-x86_64.jar:4.1.53.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.53.Final.jar:4.1.53.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
"   
  logger: "io.zeebe.gateway"   
  message: "Failed to activate jobs for type benchmark-task from partition 3" 
```

are related to the issue of inconsistent topology.

**Comment by Zelldon** [comment]
[We can see several leader changes around this time:](https://grafana-ultrachaos.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=6897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe&var-pod=All&var-partition=All&from=1606267200000&to=1606268242000)

![atomix](https://user-images.githubusercontent.com/2758593/100236875-83225b00-2f2e-11eb-95ad-94a1da7dcb89.png)

**Comment by Zelldon** [comment]
[At the end Broker-0 wins and becomes leader
](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:35:33.319389000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=logName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0AjsonPayload.context.loggerName!%3D%22io.zeebe.logstreams.snapshot%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:29.369122000Z&pinnedLogId=1f2hxblg2ub45h4&pinnedLogTimestamp=2020-11-25T01:33:29.369122Z)
```
context: {
   actor-name: "Broker-0-ZeebePartition-3"    
   loggerName: "io.zeebe.broker.system"    
   threadId: 34    
   threadName: "Broker-0-zb-actors-3"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.system"   
  message: "Partition 3 transition complete, installed 11 resources!" 
```
[
And we are able to write the deployment to partition 3](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-11-25T01:35:33.319389000Z&dateRangeStart=2020-11-25T00:33:58.980Z&dateRangeEnd=2020-11-25T02:33:58.980Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=logName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%226897f1b0-2cdf-44c7-84df-61ae048b811e-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0AjsonPayload.context.loggerName!%3D%22io.zeebe.logstreams.snapshot%22&interval=JUMP_TO_TIME&scrollTimestamp=2020-11-25T01:33:29.389468000Z&pinnedLogId=1f2hxblg2ub45h7&pinnedLogTimestamp=2020-11-25T01:33:29.389468Z)

```
  context: {
   actor-name: "Broker-0-ManagementRequestHandler"    
   loggerName: "io.zeebe.broker.workflow.repository"    
   threadId: 33    
   threadName: "Broker-0-zb-actors-2"    
   threadPriority: 5    
  }
  logger: "io.zeebe.broker.workflow.repository"   
  message: "Deployment CREATE command for deployment 2251799813884161 was written on partition 3" 
```

So I would say this is an intermediate issue which can happen and is expected but should recover after sometime.

@npepinpe the only thing we can do here is to lower the log level in the gateway. Idk you need to decide whether we want to do that.

**Comment by npepinpe** [comment]
In general in the transport `NoRemoteHandler` should be logged as a warning, as these are expected transient errors that are most likely recoverable, but may indicate something is wrong if they persist.

So the expected outcome here would be to lower the level to WARN for these errors.

**Comment by younes-io** [comment]
I have the same issue:

```bash
Mar 28 10:19:35 cwa-prod-zeebe-gateway-7c5458bb47-dxd9d zeebe-cluster-helm [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-scheduler-zb-actors-0] WARN 
      io.zeebe.gateway - Failed to activate jobs for type rpa-worker from partition 3
io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:64) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:37) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:852) ~[atomix-cluster-0.26.3.jar:0.26.3]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar:4.1.55.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.55.Final-linux-x86_64.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Zeebe: 0.26

**Comment by npepinpe** [comment]
Had a look again at this. It shouldn't be logged anymore except as a cause for warnings. So as an error (at least in this context of the gateway) I would close this.

**Comment by Zelldon** [comment]
Happened again.

[zeebe:8.0.15-SNAPSHOT-stable-8.0-3f321e21](https://console.cloud.google.com/errors/detail/COeS4vn5-Je6jwE;service=zeebe;version=8.0.15-SNAPSHOT-stable-8.0-3f321e21;time=P7D?project=camunda-saas-int-chaos)

[zeebe:8.0.15-SNAPSHOT-stable-8.0-8d5aa08d](https://console.cloud.google.com/errors/detail/COeS4vn5-Je6jwE;service=zeebe;version=8.0.15-SNAPSHOT-stable-8.0-8d5aa08d;time=P7D?project=camunda-saas-int-chaos)

[zeebe:8.3.0-SNAPSHOT-main-bc9de50d](https://console.cloud.google.com/errors/detail/COeS4vn5-Je6jwE;service=zeebe;version=8.3.0-SNAPSHOT-main-bc9de50d;time=P7D?project=camunda-saas-int-chaos)

Error group https://console.cloud.google.com/errors/detail/COeS4vn5-Je6jwE;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**Comment by npepinpe** [comment]
The error may be logged on start up or shutdown, that's normal, as the handler may or may not be registered during that time, but requests may still be coming in. When everything is running, depending on the topic, it may indicate an error or not (e.g. for command-api, it's an error, but for something transient it wouldn't be).

Have we noticed any impact on the system in these cases? I guess it just shouldn't be logged as error.

**Comment by korthout** [comment]
>The error may be logged on start up or shutdown, that's normal, as the handler may or may not be registered during that time, but requests may still be coming in.

@npepinpe Would it be possible to change the log level of these exceptions depending on the broker's phase. For example, during startup/shutdown it simply logs these at WARN and otherwise at ERROR?

**Comment by npepinpe** [comment]
If we have a good way to detect it :thinking:

**Comment by korthout** [comment]
@npepinpe Startup and Shutdown should be detectable right?

**Comment by npepinpe** [comment]
Precisely, the remote broker is the one returning this error. It could return a different one if it knows it's starting up/shutting down, I guess, but I don't know we have a good mechanism to query this anywhere in the application.

But for no remote handler tbh, this could be a warning in general instead of error.

**Comment by korthout** [comment]
>But for no remote handler tbh, this could be a warning in general instead of error.

Would be nice to adjust, as I've seen this error reported often in the past, and it's always been noise.

**Comment by korthout** [comment]
This is logged as a warning nowadays. So closing.
