### ISSUE TITLE
AsyncSnapshotDirector. onCommitCheck throws NPE

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#5775]
**Describe the bug**
A NullPointerException was thrown in AsyncSnapshotDirector. onCommitCheck. 

Considering that code the only case is that `currentCommitPosition` is null, which can happen when the future was completed exceptionally.

Looking at the logs it appears that the `Broker-1-SnapshotDirector-1` started closing just before this happened. It was closing because the logstream raft partition became unhealthy just before.

![Screenshot 2020-11-06 at 14 47 27](https://user-images.githubusercontent.com/3511026/98373064-ff680380-203e-11eb-87af-59a8af99954f.png)

**To Reproduce**
Link to error: https://console.cloud.google.com/errors/CPyG3vDQsrvydQ?service=zeebe&time=P1D&refresh=auto&project=camunda-cloud-240911&authuser=1

See [logs](https://console.cloud.google.com/logs/query;query=logName:%22zeebe%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultratest%22%0Aresource.labels.namespace_name%3D%22ff073a96-1bd3-4dee-a0f7-00c194bb0bfd-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2020-11-05T16:23:45.420Z%2F2020-11-05T17:23:45.420Z;pinnedLogId=2020-11-05T16:53:15.418394Z%2Fbxv3m6f2e8onc?authuser=1&project=camunda-cloud-240911)

**Expected behavior**
- AsyncSnapshotDirector. onCommitCheck should be able to deal with an exceptional completion instead of throwing NPE
- Closing the AsyncSnapshotDirector should be a blocking call and should not be able to race with other actions in the AsyncSnapshotDirector.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: null
	at io.zeebe.engine.processor.AsyncSnapshotDirector.lambda$onCommitCheck$7(AsyncSnapshotDirector.java:230) ~[zeebe-workflow-engine-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) ~[zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.4.jar:0.23.4]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.4.jar:0.23.4]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Environment: ultratest
 - Zeebe Version: 0.23.6

**Comment by npepinpe** [comment]
Impact greatly lowered once we fix https://github.com/zeebe-io/zeebe/issues/5117

**Comment by npepinpe** [comment]
Closing as it has not reoccurred, and we fixed the related issue.
