### ISSUE TITLE
BpmnProcessingException: Expected to activate the none start event of the process but not found

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#7669]
**Describe the bug**
I deployed a process with a timer start event that triggers every 10 seconds. The process worked fine for some time. But at some point, I saw the following failures in the log:

```
io.camunda.zeebe.engine.processing.bpmn.BpmnProcessingException: 
Expected to activate the none start event of the process but not found. 
[context: {intent=ELEMENT_ACTIVATED, elementId=timer-event-process, bpmnElementType=PROCESS, 
elementInstanceKey=2251799987594468, flowScopeKey=-1, processInstanceKey=2251799987594468, 
parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=timer-event-process, 
processVersion=2, processDefinitionKey=2251799813814592}]
```

Looking at Operate, it seems that the duration between two timers increases over time:

![image](https://user-images.githubusercontent.com/4305769/130397765-e9ad16ed-3de1-4af4-a354-e2704b336239.png)

![image](https://user-images.githubusercontent.com/4305769/130397815-8eae6ccf-1cb7-4363-93d7-4f0c5bc0116a.png)

![image](https://user-images.githubusercontent.com/4305769/130397847-34e59e6a-d8ef-4b94-a1af-bbfa00d0eb88.png)

![image](https://user-images.githubusercontent.com/4305769/130397913-e046b62c-3f85-47b3-9459-8226ab3a1b41.png)

![image](https://user-images.githubusercontent.com/4305769/130397965-897286e2-fda0-4fbc-945b-41bb9eb3c8b4.png)

Until it takes minutes to trigger the next timer.

![image](https://user-images.githubusercontent.com/4305769/130398106-bdd7086a-1803-45e4-b487-74983317afc3.png)

**To Reproduce**
It is not clear what causes the problem.

The process has one timer start event with a timer cycle `R/PT10S`. See the [BPMN](https://github.com/zeebe-io/camunda-cloud-smoke-test/blob/main/src/main/resources/bpmn/timer-event.bpmn) (from our smoke-test project :wink:)

![image](https://user-images.githubusercontent.com/4305769/130395559-e85a2ab9-a993-484a-9e52-9b59db027a8d.png)

**Expected behavior**
It creates a new instance of the process every 10 seconds.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.engine.processing.bpmn.BpmnProcessingException: Expected to activate the none start event of the process but not found. [context: {intent=ELEMENT_ACTIVATED, elementId=timer-event-process, bpmnElementType=PROCESS, elementInstanceKey=2251799982896084, flowScopeKey=-1, processInstanceKey=2251799982896084, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=timer-event-process, processVersion=2, processDefinitionKey=2251799813814592}]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateNoneStartEvent(ProcessProcessor.java:116) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$activateStartEvent$7(ProcessProcessor.java:106) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateStartEvent(ProcessProcessor.java:103) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$onActivate$2(ProcessProcessor.java:61) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:60) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:27) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$3(BpmnStreamProcessor.java:202) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:201) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$1(BpmnStreamProcessor.java:133) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:238) ~[zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:130) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:295) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:285) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:219) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:210) ~[zeebe-workflow-engine-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.1.0.jar:1.1.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.1.0.jar:1.1.0]
```

</p>
</details>

[Error Reporing Tool](https://console.cloud.google.com/errors/CIPtl7imgone7AE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911)

[Log Entry](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22integration-worker-1%22%0Aresource.labels.namespace_name%3D%2229c3ebf3-393e-447b-b739-5a56e64e74b5-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2021-08-20T09:00:00.078Z%2F2021-08-20T09:00:00.078Z--PT1H;pinnedLogId=2021-08-20T09:52:44.254185Z%2F3huvuu6oia0xrm2b;cursorTimestamp=2021-08-20T09:52:44.254185Z?project=camunda-cloud-240911)

[Grafana Dashboard](https://grafana-worker-1.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=29c3ebf3-393e-447b-b739-5a56e64e74b5-zeebe&var-pod=All&var-partition=All&from=1629410400000&to=1629496800000)

Camunda Cloud Cluster-Id: [29c3ebf3-393e-447b-b739-5a56e64e74b5](https://console.cloud.ultrawombat.com/org/1b8b19aa-3cf4-4cff-8a25-f3dd46efca4d/cluster/29c3ebf3-393e-447b-b739-5a56e64e74b5)

**Environment:**
 - OS: Camunda Cloud 1.1.0
 - Zeebe Version: `1.1.0`
 - Configuration: GA Hardware Package

**Comment by korthout** [comment]
Marking priority as `later` because improving timer behavior is not our main priority right now.

Please comment if you think this should have a higher priority.

**Comment by korthout** [comment]
Also, marking severity as `high` because there is no known workaround

**Comment by korthout** [comment]
@saig0 Can you elaborate? Where did you see this failure?

**Comment by saig0** [comment]
@korthout the failure was reported in the error reporting tool [here](https://console.cloud.google.com/errors/detail/CNXi0K3g7or5kwE;filter=%5B%22BpmnProcessingException%22%5D?project=zeebe-io). It was caused by our Zeebe benchmark on running the [msg_one_task.bpmn](https://github.com/camunda/zeebe/blob/main/benchmarks/project/src/main/resources/bpmn/msg_one_task.bpmn) process.

Stack trace:
```
io.camunda.zeebe.engine.processing.bpmn.BpmnProcessingException: Expected to activate the none start event of the process but not found. [context: {intent=ELEMENT_ACTIVATED, elementId=msg_one_task, bpmnElementType=PROCESS, elementInstanceKey=2251799826058417, flowScopeKey=-1, processInstanceKey=2251799826058417, parentProcessInstanceKey=-1, parentElementInstanceKey=-1, bpmnProcessId=msg_one_task, processVersion=1, processDefinitionKey=2251799813686384}]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateNoneStartEvent(ProcessProcessor.java:119) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.lambda$activateStartEvent$5(ProcessProcessor.java:109) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.activateStartEvent(ProcessProcessor.java:106) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:59) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.container.ProcessProcessor.onActivate(ProcessProcessor.java:27) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2(BpmnStreamProcessor.java:102) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:101) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:84) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:381) ~[zeebe-util-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:81) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:347) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:98) ~[zeebe-db-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:203) [zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT] 
```

**Comment by korthout** [comment]
Encountered on production ([error](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-07-05T13:10:39.214233479Z;query=error_group%2528%22CNXi0K3g7or5kwE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22ea41386c-4386-4d27-b988-345414a3c5fa-zeebe%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Atimestamp%3D%222023-07-05T13:10:39.214233479Z%22%0AinsertId%3D%226myh0bzoq82rdo1j%22;timeRange=2023-07-05T12:41:09.214Z%2F2023-07-05T13:41:09.214Z?project=camunda-cloud-240911))

**Comment by korthout** [comment]
Depending on the `maxCommandsInBatch` setting, the publish message command is rejected or not:
- By default, this is set to `100`, and then the publish message command is rejected with status `INTERNAL`. It's up to the user to handle errors and they should not expect that this message led to a created process instance
- When set to `1`, the publish message command is accepted, but the created process instance cannot be executed correctly. This results in banning the created instance.

**Comment by korthout** [comment]
Root cause:
- No EventTrigger was found for the process definition key
- An EventTrigger was found but it refers to a different process instance (for example when the EventTriggers are not in the same order as the `Process:ACTIVATE_ELEMENT` command)

https://github.com/camunda/zeebe/blob/c613d577c00da92baf3a800820633bc5a8d621f3/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/container/ProcessProcessor.java#L100-L109

**Comment by korthout** [comment]
How [this situation](https://github.com/camunda/zeebe/issues/7669#issuecomment-1686525907) can actually occur is unclear. The only EventTriggers that are created in the `processDefinitionKey`'s eventscope are the message/signal/timer start events.

**Comment by aleksander-dytko** [comment]
ZPA Planning: 
- It's a complicated bug and we don't know how to fix that 
- It occurred in prod but we don't understand how it happened
- Customers didn't raise that

**Comment by korthout** [comment]
Unassigning as no-one is working on this right now

**Comment by koevskinikola** [comment]
Issue occurred again:
- Environment: Camunda SaaS (prod)
- Zeebe version: 8.6.6
- GCP downloaded logs: [internal link](https://drive.google.com/file/d/1l_tSkYiyq_FN8a_GVIG2fWkARgQ1nCvF/view?usp=sharing)
- GCP log viewer: [internal link](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22dd03e7fe-415f-453a-a096-225447caff2e-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2024-12-15T09:33:47.869338983Z%2Fuppeylsmr0y2wtiv;cursorTimestamp=2024-12-15T09:33:47.869338983Z;startTime=2024-12-15T09:04:17.869Z;endTime=2024-12-15T10:04:17.869Z?inv=1&invt=AbkROQ&project=camunda-cloud-240911)

**Comment by remcowesterhoud** [comment]
Likely caused by https://github.com/camunda/camunda/issues/33952#issuecomment-3000445486
