### ISSUE TITLE
Unsupported Operation Exception - ClosedQueue during Shutdown

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#8025]
**Describe the bug**
Observed in production logs: https://console.cloud.google.com/errors/CNz0k4bXsqi5PA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

Happened during shutdown of broker.

**Expected behavior**
No exceptions. Maybe implement methods `isEmpty(), size()` methods so they are neutral. Or maybe separate class into uninitialized queue which is installed by default and throws exceptions and closed queue which is installed after shutdown and is silent - maybe except for methods like `add` and `offer`

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.UnsupportedOperationException: null
	at io.camunda.zeebe.util.sched.ClosedQueue.isEmpty(ClosedQueue.java:24) ~[zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorTask.tryWait(ActorTask.java:353) ~[zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorTask.onAllJobsDone(ActorTask.java:213) ~[zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:162) ~[zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.2.1.jar:1.2.1]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.2.1.jar:1.2.1]
```

</p>
</details>

<details><summary>Log</summary>
 <p>

```
I 2021-10-19T06:11:18.164832Z Closing Broker-0 [1/10]: upgrade manager 
I 2021-10-19T06:11:18.169577Z Closing Broker-0 [2/10]: register diskspace usage listeners 
I 2021-10-19T06:11:18.169933Z Closing Broker-0 [3/10]: zeebe partitions 
I 2021-10-19T06:11:18.177133Z Transition to INACTIVE on term -1 requested. 
I 2021-10-19T06:11:18.178461Z Transition to INACTIVE on term -1 requested. 
I 2021-10-19T06:11:18.179131Z Received cancel signal for transition to LEADER on term 1 
I 2021-10-19T06:11:18.179220Z Received cancel signal for transition to FOLLOWER on term 1 
I 2021-10-19T06:11:18.179609Z Cleanup of transition to LEADER on term 1 starting (in preparation for new transition to INACTIVE) 
I 2021-10-19T06:11:18.180162Z Cleanup of transition to FOLLOWER on term 1 starting (in preparation for new transition to INACTIVE) 
I 2021-10-19T06:11:18.182945Z Cleanup of transition to FOLLOWER on term 1 - executing ExporterDirector 
I 2021-10-19T06:11:18.183710Z Cleanup of transition to LEADER on term 1 - executing ExporterDirector 
I 2021-10-19T06:11:18.188002Z Cleanup of transition to FOLLOWER on term 1 - executing SnapshotDirector 
I 2021-10-19T06:11:18.196295Z Exporter closed 
I 2021-10-19T06:11:18.197092Z Cleanup of transition to FOLLOWER on term 1 - executing StreamProcessor 
I 2021-10-19T06:11:18.197632Z Cleanup of transition to LEADER on term 1 - executing SnapshotDirector 
I 2021-10-19T06:11:18.198239Z Cleanup of transition to LEADER on term 1 - executing StreamProcessor 
I 2021-10-19T06:11:18.198734Z Cleanup of transition to FOLLOWER on term 1 - executing QueryService 
I 2021-10-19T06:11:18.199613Z Cleanup of transition to FOLLOWER on term 1 - executing ZeebeDb 
I 2021-10-19T06:11:18.200782Z Cleanup of transition to LEADER on term 1 - executing QueryService 
I 2021-10-19T06:11:18.215322Z Cleanup of transition to LEADER on term 1 - executing ZeebeDb 
I 2021-10-19T06:11:18.215764Z Cleanup of transition to LEADER on term 1 - executing LogStream 
I 2021-10-19T06:11:18.216951Z Cleanup of transition to FOLLOWER on term 1 - executing LogStream 
I 2021-10-19T06:11:18.218038Z Close appender for log stream logstream-raft-partition-partition-2 
I 2021-10-19T06:11:18.223181Z On closing logstream logstream-raft-partition-partition-2 close 2 readers 
I 2021-10-19T06:11:18.224779Z Close appender for log stream logstream-raft-partition-partition-1 
I 2021-10-19T06:11:18.225288Z On closing logstream logstream-raft-partition-partition-1 close 1 readers 
E 2021-10-19T06:11:18.226138Z Unexpected error occurred in task Broker-0-LogStream-2 NOT_SCHEDULED phase: CLOSED 
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud, Producation, 1.2.1

**Comment by Zelldon** [comment]
Happened again https://console.cloud.google.com/errors/detail/CN-poOuxjc3g_QE;service=zeebe;time=P7D?project=camunda-saas-prod

8.3.0-alpha1


```
Unexpected error occurred in task Broker-1-SnapshotStore-2 NOT_SCHEDULED phase: CLOSED
java.lang.UnsupportedOperationException: null

at io.camunda.zeebe.scheduler.ClosedQueue.isEmpty ( [io/camunda.zeebe.scheduler/ClosedQueue.java:24](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FClosedQueue.java&line=24&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorTask.tryWait ( [io/camunda.zeebe.scheduler/ActorTask.java:351](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorTask.java&line=351&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorTask.onAllJobsDone ( [io/camunda.zeebe.scheduler/ActorTask.java:184](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorTask.java&line=184&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorTask.execute ( [io/camunda.zeebe.scheduler/ActorTask.java:159](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorTask.java&line=159&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( [io/camunda.zeebe.scheduler/ActorThread.java:106](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=106&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( [io/camunda.zeebe.scheduler/ActorThread.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=87&project=camunda-saas-prod) )
at io.camunda.zeebe.scheduler.ActorThread.run ( [io/camunda.zeebe.scheduler/ActorThread.java:198](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.scheduler%2FActorThread.java&line=198&project=camunda-saas-prod) )
Recent samples [Learn more](https://cloud.google.com/error-reporting/docs/managing-errors?hl=en_GB#error_samples)
```

**Comment by korthout** [comment]
https://github.com/camunda/zeebe/issues/8025#issuecomment-1581996397

Happened again in [`medic-y-2023-cw-34-19b8456-benchmark-mixed`](https://console.cloud.google.com/errors/detail/CN-poOuxjc3g_QE;service=zeebe;time=P7D?project=zeebe-io)

**Comment by npepinpe** [comment]
Closing until next time, as we should save the logs when it happens.

**Comment by berkaycanbc** [comment]
Occurred again on SaaS DEV: [LINK](https://console.cloud.google.com/errors/detail/CIG-_5ShoKbxKQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev)
GCP Logs: [LINK](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CIG-_5ShoKbxKQ%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.namespace_name%3D%22986d8024-f5c1-4938-ab34-d0a55de9ab61-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-saas-dev%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-2%22;cursorTimestamp=2025-10-25T23:23:07.410118338Z;startTime=2025-10-25T22:53:37.410Z;endTime=2025-10-25T23:53:37.410Z?project=camunda-saas-dev)
GCP Logs Downloaded: [LINK](https://drive.google.com/file/d/1GjC7OUHQ8bE5PTPeMtIQC5q-nsH7lzfK/view?usp=sharing)

**Comment by berkaycanbc** [comment]
Occurred again on SaaS Int Chaos `zeebe:SNAPSHOT`:

GCP Error: [LINK](https://console.cloud.google.com/errors/detail/CIG-_5ShoKbxKQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int-chaos)
GCP Logs: [LINK](https://console.cloud.google.com/logs/query;query=error_groups.id%3D%22CIG-_5ShoKbxKQ%22%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%229f76b2e9-0cf8-406d-bee9-81b658cfb52a-zeebe%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22;cursorTimestamp=2025-10-28T15:42:51.779417048Z;startTime=2025-10-28T15:13:21.779Z;endTime=2025-10-28T16:13:21.779Z?project=camunda-saas-int-chaos)

**Comment by korthout** [comment]
Also on SaaS Int `zeebe:SNAPSHOT`
- GCP Error: https://console.cloud.google.com/errors/detail/CIG-_5ShoKbxKQ;service=zeebe;time=P7D;locations=global?project=camunda-saas-int
- Saved logs: https://drive.google.com/file/d/1SIeOrSuP-d7FfkhuTNTtR-lwyLgDDQrl/view?usp=drive_link

**Comment by entangled90** [comment]
Closed by #40687
