### ISSUE TITLE
Fail to throw/catch error if the job is based by a message throw event

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#8662]
**Describe the bug**

User has thrown an error command. Upon searching for the for available catch events Zeebe runs into an exception.

**To Reproduce**

**Expected behavior**

Zeebe should not run in an exception. If it is possible for this event to have catch events, it should be able to search for them. If not, it should not try to find them.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

https://console.cloud.google.com/errors/detail/CJzvqeyl3ZbT1QE;service=zeebe;time=P7D?project=camunda-cloud-240911

```
java.lang.RuntimeException: Expected element with id 'Event_1armv9z' to be instance of class 'ExecutableActivity', but it is an instance of 'ExecutableIntermediateThrowEvent'
	at io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(ExecutableProcess.java:79) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.state.analyzers.CatchEventAnalyzer.findCatchEventInScope(CatchEventAnalyzer.java:120) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.state.analyzers.CatchEventAnalyzer.findCatchEventInProcess(CatchEventAnalyzer.java:94) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.state.analyzers.CatchEventAnalyzer.findCatchEvent(CatchEventAnalyzer.java:56) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.job.JobThrowErrorProcessor.acceptCommand(JobThrowErrorProcessor.java:115) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.job.JobThrowErrorProcessor.lambda$new$0(JobThrowErrorProcessor.java:70) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.job.DefaultJobCommandPreconditionGuard.onCommand(DefaultJobCommandPreconditionGuard.java:54) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.job.DefaultJobCommandPreconditionGuard.onCommand(DefaultJobCommandPreconditionGuard.java:43) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.job.JobThrowErrorProcessor.onCommand(JobThrowErrorProcessor.java:80) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessor.onCommand(CommandProcessor.java:32) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:73) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:290) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:280) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:248) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:208) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:189) ~[zeebe-workflow-engine-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) [zeebe-util-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.3.1.jar:1.3.1]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.3.1.jar:1.3.1]
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud 
 - Zeebe Version: 1.3.1 
 - Configuration:

**Comment by saig0** [comment]
### Context

A message throw event can be used to represent a job, as an alternative to service tasks. If the job worker throws an error event then the error should be caught in the process. But the processor fails with an exception because it is not aware that the element of the job can be a message throw event (i.e. different base class to other job-related tasks. As a result, the process instance is blacklisted and can be continued.

![image](https://user-images.githubusercontent.com/4305769/151300219-6cc4f9f7-c607-4834-9fab-93ddba376bfb.png)

**Comment by npepinpe** [comment]
Hopefully once we've fixed some other bugs we have time for this one before the next release. In the meantime, current work around is to swap our your message throw event for a service task. Not ideal, but it should allow you to keep similar behavior and throw errors as well.

**Comment by korthout** [comment]
Another workaround is to use an [Error End Event](https://docs.camunda.io/docs/next/components/modeler/bpmn/error-events/#throwing-the-error). 

TBH, throwing an error from an **intermediate** message throw event seems unexpected because throwing an error would likely mean that you'd want to terminate that flow. 

@saig0 Is this really a valid use case?

**Comment by saig0** [comment]
@korthout I understand your point but yes, it is. From a process, it is the same as a send task, for example, to send an HTTP request. Since the action can fail, we want to handle the failure by catching an error event. 

Some users may prefer throwing events over (send) tasks. But both elements should work the same.

**Comment by korthout** [comment]
Marking priority as `later` because there is a workaround available, but we should improve this along with improved BPMN symbol support.

Please comment if you think this should have a higher priority.

**Comment by korthout** [comment]
Occurred in https://console.cloud.google.com/errors/detail/CJWf2o7n1-2ipwE;service=zeebe;time=P7D?project=camunda-cloud-240911

**Comment by lenaschoenburg** [comment]
Very similar issue here: https://console.cloud.google.com/errors/detail/CJWf2o7n1-2ipwE;service=zeebe;time=P7D;locations=global?inv=1&invt=Absm_A&project=camunda-saas-prod-sin

```
 java.lang.RuntimeException: Expected element with id '[redacted]' to be instance of class 'ExecutableActivity', but it is an instance of 'ExecutableEndEvent' 
```

**Comment by entangled90** [comment]
**[It happened again](https://console.cloud.google.com/errors/detail/CJWf2o7n1-2ipwE;service=zeebe;time=P7D;locations=global?inv=1&invt=AbwHzw&project=camunda-saas-prod-sin)** in `8.6.11`

**Comment by panagiotisgts** [comment]
Occurred again in prod [incident](https://jira.camunda.com/browse/SUPPORT-30917) 8.4.7

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | ⚠️ Mid |
| **Likelihood** | 🔥 High |
| **Confidence** | 0.95 |

---

### 📝 Rationale

The issue describes a runtime exception in Zeebe when an error is thrown from a message throw event, with clear expected vs actual behavior and reproduction steps. This is a bug per Core Features Bug Triage rules. The impact is noticeable in production (process instance is blacklisted and can't be continued), but there are workarounds (e.g., using a service task or error end event), so severity is MID. The issue has recurred multiple times across versions and environments, including recent production incidents, so likelihood is HIGH. The problem is within Core Features team boundaries (Zeebe Engine and execution).

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by berkaycanbc** [comment]
Happened again on [zeebe:8.8.14](https://console.cloud.google.com/errors/detail/CKuj8Oe64ZH0sgE;service=zeebe;version=8.8.14;time=P7D;locations=global?project=camunda-cloud-240911).

**Comment by ce-dmelnych** [comment]
🔁 Regression tests to add to [JobThrowErrorTest.java](https://github.com/camunda/camunda/blob/1ad8e537084babce9d554a2355f730dda65f5c4e/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/JobThrowErrorTest.java#L42) that reproduce this issue:
<details><summary><code> JobThrowErrorTest.java</code></summary>

```java
public final class JobThrowErrorTest {
// ...
  @Test
  public void shouldCatchErrorThrownFromMessageIntermediateThrowEventInSubprocess() {
    // given — message throw event inside a subprocess, error caught on the subprocess
    final var process =
        Bpmn.createExecutableProcess(PROCESS_ID)
            .startEvent()
            .subProcess(
                "subprocess",
                s ->
                    s.embeddedSubProcess()
                        .startEvent()
                        .intermediateThrowEvent(
                            "message-throw", e -> e.message("msg").zeebeJobType(jobType))
                        .endEvent())
            .boundaryEvent("error-boundary", b -> b.error(ERROR_CODE))
            .endEvent("error-end")
            .done();

    ENGINE.deployment().withXmlResource(process).deploy();
    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    // when — throw error from the message throw event's job
    ENGINE
        .job()
        .ofInstance(processInstanceKey)
        .withType(jobType)
        .withErrorCode(ERROR_CODE)
        .throwError();

    // then — the error should propagate to the subprocess boundary event
    assertThat(
            RecordingExporter.processInstanceRecords()
                .withProcessInstanceKey(processInstanceKey)
                .limitToProcessInstanceCompleted())
        .extracting(r -> r.getValue().getElementId(), Record::getIntent)
        .contains(
            tuple("error-boundary", ProcessInstanceIntent.ELEMENT_ACTIVATED),
            tuple("error-end", ProcessInstanceIntent.ELEMENT_COMPLETED),
            tuple(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETED));
  }

  @Test
  public void shouldCatchErrorThrownFromMessageEndEvent() {
    // given — error event subprocess catches error from message end event's job
    final var process =
        Bpmn.createExecutableProcess(PROCESS_ID)
            .eventSubProcess(
                "error-subprocess",
                s ->
                    s.startEvent("error-start")
                        .error(ERROR_CODE)
                        .interrupting(true)
                        .endEvent("error-subprocess-end"))
            .startEvent()
            .endEvent("message-end", e -> e.message("msg").zeebeJobType(jobType))
            .done();

    ENGINE.deployment().withXmlResource(process).deploy();
    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(PROCESS_ID).create();

    // when
    ENGINE
        .job()
        .ofInstance(processInstanceKey)
        .withType(jobType)
        .withErrorCode(ERROR_CODE)
        .throwError();

    // then
    assertThat(
            RecordingExporter.processInstanceRecords()
                .withProcessInstanceKey(processInstanceKey)
                .limitToProcessInstanceCompleted())
        .extracting(r -> r.getValue().getElementId(), Record::getIntent)
        .contains(
            tuple("error-start", ProcessInstanceIntent.ELEMENT_ACTIVATED),
            tuple("error-subprocess-end", ProcessInstanceIntent.ELEMENT_COMPLETED),
            tuple(PROCESS_ID, ProcessInstanceIntent.ELEMENT_COMPLETED));
  }
// ...
```
</details>
