### ISSUE TITLE
RejectedExecutionException during shutdown

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#9177]
**Describe the bug**

```
Uncaught exception in 'io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter' in phase 'STARTED'. Continuing with next job.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6b090dcf[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@4ad8daad[Wrapped task = io.atomix.cluster.messaging.impl.NettyMessagingService$$Lambda$1143/0x00000008012c91e0@58b2e8ae]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@791509b1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 46206]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Unknown Source) ~[?:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:226) ~[zeebe-atomix-cluster-8.0.0.jar:8.0.0]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:196) ~[zeebe-atomix-cluster-8.0.0.jar:8.0.0]
	at io.atomix.cluster.messaging.MessagingService.sendAndReceive(MessagingService.java:135) ~[zeebe-atomix-cluster-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:159) ~[zeebe-transport-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2(AtomixClientTransportAdapter.java:88) ~[zeebe-transport-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:68) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]

```

The broker was shutting down before this error.

```
2022-04-20T02:35:53.695752719Z  Broker shut down.
2022-04-20T02:35:53.696042088Z  Closing actor thread ground 'Broker-2-zb-fs-workers'
2022-04-20T02:35:53.696847777Z  Closing actor thread ground 'Broker-2-zb-fs-workers': closed successfully
2022-04-20T02:35:53.697082412Z  Closing actor thread ground 'Broker-2-zb-actors'
2022-04-20T02:35:58.986755736Z  Uncaught exception in 'io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter' in phase 'STARTED'. Continuing with next job.

```

**Comment by npepinpe** [comment]
Let's leave it in the backlog for now, as it's mostly noise, since this occurred because we shutdown the executor when shutting down the whole broker.

**Comment by nicpuppa** [comment]
Hey @npepinpe @deepthidevaki , do you think this error is the same that we can see here ([internal] (https://cloudlogging.app.goo.gl/43Q6ax3v76Y4mZmM6)) ?

**Comment by deepthidevaki** [comment]
@nicpuppa Do you mean this?
```
reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
	at reactor.core.Exceptions.failWithRejected(Exceptions.java:283) ~[reactor-core-3.6.1.jar:3.6.1]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP GET "/ready" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at reactor.core.Exceptions.failWithRejected(Exceptions.java:283) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.scheduler.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:257) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.MonoSubscribeOn.subscribeOrReturn(MonoSubscribeOn.java:55) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:63) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.1.jar:3.6.1]
```

This is different from the error in this issue.

**Comment by nicpuppa** [comment]
> This is different from the error in this issue.
Ok, so I will open another issue 👍

**Comment by npepinpe** [comment]
Closing, please reopen if it occurs and save the logs/error link.
